### ISSUE TITLE
Advanced MappingConfig 

### ISSUE THREAD

**Issue by valinha** [kobylynskyi/graphql-java-codegen#1]
It would be great to offer the possibility to have an advanced customization of scalar types. For this feature could be a good idea to have something like:

1. Be able to create custom mappings in an external file, for example a XML file. 

2. Possibility to create rules for a particular input field. For example, if a project has the type "Price" with the field "amount: Float" it can be a good idea the possibility to configure a rule only for this field in order to map this Float to a java.math.BigDecimal.

**Comment by kobylynskyi** [comment]
Version 1.1 was released:
https://github.com/kobylynskyi/graphql-java-codegen/releases/tag/v1.1

Will release maven and gradle plugins today as well.

**Comment by kobylynskyi** [comment]
@valinha, let's keep track of externalizing custom types definition in #2.
