### ISSUE TITLE
Generate Builder for model classes

### ISSUE THREAD

**Issue by kobylynskyi** [kobylynskyi/graphql-java-codegen#10]
https://www.vogella.com/tutorials/DesignPatternBuilder/article.html

**Comment by timbonicus** [comment]
This would be a great enhancement. I'm replacing an interface/builder model using [AutoMatter](https://github.com/danielnorberg/auto-matter) with the maven plugin. I was spelunking around the repo trying to discover if I could generate the same interface/builder.

For my use case the ideal generated output would be:
```
package com.mycompany.model;

import io.norberg.automatter.AutoMatter;

@AutoMatter
public interface MyClass {
  String field1();
  String field2();
}
```

Then AutoMatter could take care of the builder/validation.

**Comment by valinha** [comment]
Another option is use Lombok @Builder ( i prefer lombok 😉 )

**Comment by kobylynskyi** [comment]
I also prefer Lombok. But in order to satisfy everyone I think that it will be better to have it configurable via mapping config. 
E.g.:
`<customModelAnnotations>lombok.Builder,lombok.Data</customAnnotationsMapping>`
or
`<customModelAnnotations>io.norberg.automatter.AutoMatter</customAnnotationsMapping>`
