### ISSUE TITLE
rest-assured example - Cannot resolve method 'as(TypeRef<GraphQLResult<Map<String, 

### ISSUE THREAD

**Issue by premkh9** [kobylynskyi/graphql-java-codegen#1008]
Hi,  While using the rest assured approach, I see -' Cannot resolve method 'as(TypeRef<GraphQLResult<Map<String, ' error.
I used the latest version of rest assured dependency. Any help would be much appreciated.

![image](https://user-images.githubusercontent.com/14880073/193997677-48321226-671d-4b44-a63c-4afe285776ba.png)

**Comment by jxnu-liguobin** [comment]
`TypeRef` constructor is not public. Because its version is different from this repo.


The version in test of this repo is :
```
      <dependency>
            <groupId>io.rest-assured</groupId>
            <artifactId>rest-assured</artifactId>
            <version>4.3.3</version>
        </dependency>
```

**Comment by premkh9** [comment]
Is it possible to post the solution for the latest version of rest assured changes? I tried all possibilities but couldn't fix the issue.

**Comment by jxnu-liguobin** [comment]
@premkh9 sorry, It depends on your build tool. Please check the version of rest-assured. Or find the transfer dependency through dependency analysis tools
