### ISSUE TITLE
custom annotations to the generated resolver classes

### ISSUE THREAD

**Issue by GuoXingyou** [kobylynskyi/graphql-java-codegen#1010]
**Is your feature request related to a problem? Please describe.**
I need to add custom annotations to the generated resolver classes

**Describe the solution you'd like**
Provides a custom annotation for the resolver's configuration parameters

**Describe alternatives you've considered**
nothing.

**Comment by eduarddrenth** [comment]
Perhaps this wish can also be used to support `jakarta.validation` instead of the old `javax.validation`

**Comment by eduarddrenth** [comment]
Sorry. missed `modelValidationAnnotation`
