### ISSUE TITLE
CustomAnnotationsMapping is not generated with the maven plugin

### ISSUE THREAD

**Issue by kjholzapfel** [kobylynskyi/graphql-java-codegen#1015]
### Issue Description

When using maven with the latest version 5.5.0 with a CustomAnnotationsMapping configuration in the pom, the mapping isn't generated when compiling.

### Steps to reproduce
1. Clone this repository
2. Select the project https://github.com/kobylynskyi/graphql-java-codegen/tree/master/plugins/maven/example-client
3. Compile with maven

### Expected result
Classes annotated with the annotations defined in CustomAnnotationsMapping.

### Actual result
None of the generated classes are annotated with the annotations defined in CustomAnnotationsMapping.

**Comment by kobylynskyi** [comment]
@kjholzapfel please provide more details - how are you specifying config inside your `pom.xml`?
The expected format is the following:
```xml
                        <customAnnotationsMapping>
                            <YourGraphQLTypeName>
                                <annotation>com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = com.example.json.Deserializer.class)</annotation>
                            </YourGraphQLTypeName>
                        </customAnnotationsMapping>
```
