### ISSUE TITLE
Support migration to Jakarta by allowing customization of `@Generated` annotation

### ISSUE THREAD

**Issue by blaenk** [kobylynskyi/graphql-java-codegen#1016]
**Is your feature request related to a problem? Please describe.**

With upgrading to Spring Boot 3 and its accompanying Jakarta migration, I would like to switch to using `jakarta.annotation.*` over `javax.annotation.*`.

For `@NotNull` annotations this can be done with the `modelValidationAnnotation` codegen option but there is no such option for the `@Generated` annotation short of disabling that feature altogether with `addGeneratedAnnotation`.

**Describe the solution you'd like**

Add a `generatedAnnotation` codegen option or something like it?

**Describe alternatives you've considered**

Can't think of any but I defer to you.

**Comment by kobylynskyi** [comment]
Added a new config `generatedAnnotation`: #1036 
Also modified the logic of setting a default value for `@Generated` annotation (**if value for `generatedAnnotation` config is empty**):
* if `@jakarta.annotation.Generated` is present in the classpath then use it
* else if `@javax.annotation.processing.Generated` is present in the classpath then use it
* else if `@javax.annotation.Generated` is present in the classpath then use it
* else skip adding `@Generated` annotation on top of the class.

**Comment by kobylynskyi** [comment]
Will include this feature in the upcoming release. Stay tuned.

**Comment by atrozzo** [comment]
Hi Guys , thanks for this add , can you please instruct me on how to use properly your new feature ? We use with maven , goal generate , and the javax annotation get generated automatically for each  field declared mandatory. How can I change this to use jakarta ?Thanks

**Comment by kobylynskyi** [comment]
@atrozzo you can add the following config to build.gradle/pom.xml:
`generatedAnnotation = jakarta.annotation.Generated`
