### ISSUE TITLE
Union array type in interfaces generated wrong

### ISSUE THREAD

**Issue by hlege** [kobylynskyi/graphql-java-codegen#1018]
## Issue Description

Union array types in interfaces now generate the exact type e.g.: `List<UnionType>`, but it should be `List<? extends UnionType>`

## Steps to Reproduce

```
union FooOrBar = Foo | Bar

type Foo {
  id: ID!
}

type Bar {
  id: ID!
}

interface ResultObject {
  list: [FooOrBar!]
}

type MyFooResult implements ResultObject {
  list: [Foo!]
}

type MyBarResult implements ResultObject {
  list: [Bar!]
}

```

## Expected Result

The code should compile. 
```
public interface ResultObject {

    java.util.List<? extends FooOrBar> getList();

}
```

## Actual Result
```
public interface ResultObject {

    java.util.List<FooOrBar> getList();

}
```

`io.github.kobylynskyi.bikeshop.graphql.model.MyFooResult is not abstract and does not override abstract method getList() in io.github.kobylynskyi.bikeshop.graphql.model.ResultObject`

## Your Environment and Setup

* **graphql-java-codegen version**: *5.5.0*
* **Build tool**: *E.g.: Maven*

**Comment by kobylynskyi** [comment]
@hlege sorry for a long response. Here's the PR which addresses your issue: #1030

**Comment by kobylynskyi** [comment]
Will include the fix in the next upcoming release
