### ISSUE TITLE
Default collections initialization

### ISSUE THREAD

**Issue by klvnnsrikanth** [kobylynskyi/graphql-java-codegen#1026]
I am using this plugin for generating pojos for my graphql schema, while it works great I found that the collections are not initialized. Looking to see if there is a property setting to do it, if no is there a way to add this feature in the future?

**Comment by kobylynskyi** [comment]
Default values in generated classes are driven only by a schema.
Please take a look at the example:
Schema: https://github.com/kobylynskyi/graphql-java-codegen/blob/7102be5d2d8bf82fec503b7afe9647e6e27f4a12/src/test/resources/schemas/defaults.graphqls#L12
Generated class: https://github.com/kobylynskyi/graphql-java-codegen/blob/7102be5d2d8bf82fec503b7afe9647e6e27f4a12/src/test/resources/expected-classes/defaults/InputWithDefaults.java.txt#L25

**Comment by klvnnsrikanth** [comment]
Thanks for your input

**Comment by klvnnsrikanth** [comment]
@kobylynskyi 
How about for output types? can we also define them to be empty by default?
