### ISSUE TITLE
Avoid unused imports

### ISSUE THREAD

**Issue by benmccann** [kobylynskyi/graphql-java-codegen#103]
## Issue Description

There are some unused imports in the generated code. This causes warnings in Eclipse that it's complaining about.

## Steps to Reproduce

There are three ways that this happens:
1. Create a model `type` in a GraphQL schema that has no collections. The generated model will `import java.util.*;` but it is not needed
2. Create a model `type` in a GraphQL schema that has no references to other user defined types. The generated model will `import your.generated.output.package.*;` but it is not needed
3. Create a query in a GraphQL schema that has no collections. The generated model will `import java.util.*;` but it is not needed

## Expected Result
It'd be great if the generator could check if the imports will be needed. This is more work, but luckily the logic doesn't seem too complex

## Actual Result
>Description	Resource	Path	Location	Type
The import com.benmccann.sample.graphql.types.api is never used	PostResponse.java	/play-modern-monolith-seed/target/scala-2.13/src_managed_graphql/com/benmccann/sample/graphql/types/model	line 4	Java Problem
The import com.benmccann.sample.graphql.types.api is never used	UserResponse.java	/play-modern-monolith-seed/target/scala-2.13/src_managed_graphql/com/benmccann/sample/graphql/types/model	line 4	Java Problem
The import java.util is never used	GetPostQuery.java	/play-modern-monolith-seed/target/scala-2.13/src_managed_graphql/com/benmccann/sample/graphql/types/api	line 3	Java Problem
The import java.util is never used	GetUserQuery.java	/play-modern-monolith-seed/target/scala-2.13/src_managed_graphql/com/benmccann/sample/graphql/types/api	line 3	Java Problem
The import java.util is never used	PostResponse.java	/play-modern-monolith-seed/target/scala-2.13/src_managed_graphql/com/benmccann/sample/graphql/types/model	line 3	Java Problem

## Your Environment and Setup

* **graphql-java-codegen**: *1.6.0*
* **Build tool**: *Maven*

**Comment by joffrey-bion** [comment]
I believe that an easy way of avoid all import-related problems is just to not use them at all.
Imports are useful for source code that we read and maintain, but for generated code they bring no value.

If we simply generated code with fully qualified names everywhere, it would make things clean and easy.
@kobylynskyi do you have any thoughts on this?

**Comment by kobylynskyi** [comment]
That’s a totally valid point. 
Initially I added ‘import java.util.*;” as a quick and dirty solution. Which for sure can be easily fixed by fully-qualified names.

**Comment by benmccann** [comment]
Full qualified names sounds fine to me. Good idea. I think that will be easier to implement
