### ISSUE TITLE
GenerateJacksonTypeIdResolver should be applied to interface as well.

### ISSUE THREAD

**Issue by esfomeado** [kobylynskyi/graphql-java-codegen#1033]
**Is your feature request related to a problem? Please describe.**
Right now the Jackson annotations are only generated for union types and not interfaces. This results in having to create a custom object mapper to deal with this.

**Describe the solution you'd like**
The configuration `generateJacksonTypeIdResolver` should generate the Jackson annotations as well for interfaces.

**Describe alternatives you've considered**
N/A

**Comment by kobylynskyi** [comment]
@esfomeado thanks for the contribution. I will include your change in the next upcoming release.
