### ISSUE TITLE
Would you be interested in an sbt plugin?

### ISSUE THREAD

**Issue by benmccann** [kobylynskyi/graphql-java-codegen#104]
I'm using Play Framework, which is a Java & Scala web framework that uses sbt as the build system. I setup Maven alongside sbt as a test of the plugin to prove that it generates useful code, but I can't really integrate it into my project. If I write an sbt plugin would you be interested in having it in this repo to keep it alongside the Maven and Gradle plugins or should I create my own repo?

**Comment by kobylynskyi** [comment]
I think it is better to have all plugins in a single repo for multiple reasons:
* Release all plugins at the same time.
* Easier to maintain the code/README.
