### ISSUE TITLE
Generated sources from 5.5.0 are not compatible with dependency on 5.6.0

### ISSUE THREAD

**Issue by idegroot** [kobylynskyi/graphql-java-codegen#1043]
## Issue Description
When updating the dependency on graphql-java-codegen to 5.6.0 in a project using a library that was generated using version 5.5.0 the code will not start because the super implementation of the field "fields" has changed. The error is in a generated subclass of GraphQLResponseProjection: 

Error creating bean XXX (with static response projection definition)
Caused by: java.lang.NoSuchFieldError: fields

```
public xxxResponseProjection code(String alias) {
    fields.add(new GraphQLResponseField("code").alias(alias));
    return this;
}
```
We currently do not use transitive dependencies of the generated artifact (which would eliminate the issue) but a dedicated dependency on graphql-java-codegen. 

This is a minor issue as we can keep the old version of graphql-java-codegen but for this project we use a renovate configuration which will always try to update to the latest version of a dependency so this lib needs to be excluded until the generated package is updated too. 

## Steps to Reproduce
Generate code with version 5.5.0. Use generated code with graphql-java-codegen:5.6.0.

## Expected Result
We would expect a minor version update of the lib to be compatible with code generated by a previous version.

## Actual Result
The generated code is not usable with a newer version of the lib.

## Your Environment and Setup

* **graphql-java-codegen version**: *5.5.0* for generating AND *5.6.0* for using the generated code
* **Build tool**: *Maven*
* **Mapping Config**: *N/A*

**Comment by kobylynskyi** [comment]
This is not an issue since the code generated by 5.6.0 plugin is fully compatible with 5.6.0 dependency and you don't need to change any build configuration or the way how you use your generated classes.
