### ISSUE TITLE
Version 5.7.0 seems to break customAnnotationsMapping for fields in input types

### ISSUE THREAD

**Issue by dsilva** [kobylynskyi/graphql-java-codegen#1055]
## Issue Description

Version 5.7.0 is omitting the annotations configured in customAnnotationsMapping for fields in input types.

## Steps to Reproduce

Repro at https://github.com/dsilva/repro-graphql-java-codegen-missing-annotations

1. Clone the repo
2. Run `./gradlew graphqlCodegen`
3. Look at `build/generated/ReproInput.java`

## Expected Result

The output up to version 5.6.0 was

```java
    @javax.validation.constraints.NotNull
    @com.fasterxml.jackson.annotation.JsonProperty("reproField")
    private java.util.List<String> reproField;
```

## Actual Result

The output with version 5.7.0 of the gradle plugin includes this:

```java
    @javax.validation.constraints.NotNull
    private java.util.List<String> reproField;
```

## Your Environment and Setup

* **graphql-java-codegen version**: *5.7.0*
* **Build tool**: *Gradle*
* **Mapping Config**: *E.g.:*

```kotlin
tasks.named<io.github.kobylynskyi.graphql.codegen.gradle.GraphQLCodegenGradleTask>("graphqlCodegen").configure {
  graphqlSchemaPaths = listOf(
    "$projectDir/schema.graphqls"
  )
  outputDir = File("$buildDir/generated")

  customAnnotationsMapping = mutableMapOf(
    Pair("ReproInput.reproField", listOf("""@com.fasterxml.jackson.annotation.JsonProperty("reproField")"""))
  )

  generatedAnnotation = "javax.annotation.Generated"
}
```

**Comment by kobylynskyi** [comment]
@dsilva thanks for reporting this!
Looks like only Gradle plugin was impacted.
I've fixed it in #1056.
Will release 5.7.1 shortly today.
Sorry for the inconveniences.

**Comment by kobylynskyi** [comment]
5.7.1 was released.

**Comment by dsilva** [comment]
By the way, should those annotations land on the field or on the getter?  If a Jackson annotation lands on the field, I think it ends up writing json with two keys (one for the getter, another for the field).

**Comment by dsilva** [comment]
> 5.7.1 was released.

Thank you -- that was quick!

**Comment by kobylynskyi** [comment]
> By the way, should those annotations land on the field or on the getter? If a Jackson annotation lands on the field, I think it ends up writing json with two keys (one for the getter, another for the field).

In my projects we use just field-level annotation and it is sufficient. We don't add Jackson annotation to getters.
