### ISSUE TITLE
Client-side codegen fails if there are multiple queries with same name

### ISSUE THREAD

**Issue by kobylynskyi** [kobylynskyi/graphql-java-codegen#106]
## Issue Description
Code generation fails for the following schema:
```graphqls
    smthng(param1: String!): ResponseType
    smthng(param1: String!, param2: String!): ResponseType
```
config:
```groovy
graphqlCodegen {
    outputDir = new File("$buildDir/generated-client")
    generateRequests = true
    generateApis = false
}
```

Output:

> java.nio.file.FileAlreadyExistsException: File already exists: .../build/generated-client/SmthngQueryRequest.java

**Comment by jyjyj** [comment]
Hi @kobylynskyi, will this be part of version 1.7.3 or later? I do see this issue up to 1.7.2. Thank you!

**Comment by kobylynskyi** [comment]
Hi @jyjyj 
The fix was a part of 1.7.0.
What exact issue do you see? Please provide sample schema.
Thanks!

**Comment by jyjyj** [comment]
Hi @kobylynskyi, I see the errors that I previously mentioned in #141. In particular, my schema looks like

`
assignUsersToTask(taskId: String!, userId: String!, workerIdList: [String!]!): Boolean!
assignUsersToTask(taskId: String!, userId: String!, workerIdList: AddRemoveWorkerList!): Boolean!
`

After renaming one of them, there were no errors. `AddRemoveWorkerList` is a custom defined input looking like `
input AddRemoveWorkerList {
	add: [String!]!
	remove: [String!]!
}`. Thanks!

**Comment by kobylynskyi** [comment]
That's an expected error. 
Because you have two mutations with the same name **and** same parameter names.

**Comment by jyjyj** [comment]
@kobylynskyi, my bad for missing that. Thought I did rename them differently but I guess I only did so for the parameter type. Correct me if I'm wrong, but Java is not able to differentiate multiple functions with the same signature except of different parameter types? Either way, thank you for pointing it out!

**Comment by kobylynskyi** [comment]
@jyjyj Well, Java allows overloading methods: with the same name and same parameter names (but parameters should have a different type).
The thing is that graphql-java-codegen creates a separate class for each Query/Mutation/Subscription based on the name of GraphQL query/mutation/subscription.
If that name is used twice, then we are taking into account parameter names while generating a class. And if the pair [QueryName+ParameterNames] occurs twice within the same type, then it is an error.
I hope it helps in some way.

**Comment by jyjyj** [comment]
Hi @kobylynskyi, if method overloading is allowed for the same name and same parameter type, and if 2 resolvers were created with the same name, would they not just be generated in the same interface as 2 different methods?

**Comment by kobylynskyi** [comment]
@jyjyj 
Actually these methods are being properly generated in `Query.java`, `Mutation.java`, etc. 
But the problem comes when generating a separate class for each query/mutation.
