### ISSUE TITLE
Consider increasing the minimum Java version to 11

### ISSUE THREAD

**Issue by yeikel** [kobylynskyi/graphql-java-codegen#1064]
See https://www.graphql-java.com/blog/java-11-required/

**Comment by kobylynskyi** [comment]
graphql-java-codegen is used as a "plugin" for graphql-java users. So once graphql-java updates its min version to 11 then we will also do. Until then I don't think it makes too much sense, considering the fact that we don't require any language features.

**Comment by yeikel** [comment]
`graphql-java ` does require Java starting with v21

From the link above 

> starting with version 21 you need to use at least Java 11 to run GraphQL Java

**Comment by kobylynskyi** [comment]
Correct, at it is not yet released :)

**Comment by yeikel** [comment]
> Correct, at it is not yet released :)

My bad, you're right. I thought that v21 was the latest version when it is v20.1 :)
