### ISSUE TITLE
Consider running Sonar for pull requests

### ISSUE THREAD

**Issue by yeikel** [kobylynskyi/graphql-java-codegen#1065]
Consider reverting the following pull request https://github.com/kobylynskyi/graphql-java-codegen/pull/997

In my opinion, Sonar must run during pull requests as that's where issues are usually introduced. 

The moment tech debt lands in `main` or `develop`  is too late and the point of Sonar is to stop issues before they are introduced

**Comment by kobylynskyi** [comment]
I had sonar enabled for a very long time. But then reverted it because it fails for PRs created by other users due to invalid token error.
