### ISSUE TITLE
Consider consolidating development to a single branch

### ISSUE THREAD

**Issue by yeikel** [kobylynskyi/graphql-java-codegen#1067]
Hi all, 

Currently, we have two branches

- Develop - Where all the development happens
- Master  - The release branch

While this model is a well-known model in the industry, most popular open-source projects are opting to create a single branch and to use something very similar to the [Github Flow](https://docs.github.com/en/get-started/quickstart/github-flow) where all the code lives in a single `main` branch and releases are created from it when the maintainers see the need for it. 

The main benefit of using this workflow is that: 

- Simplifies maintainer's effort as there is now a single branch to track
- Reduces confusion for contributors as all changes will target the default branch
- Changes are always tested against the latest known version

Example projects using this workflow : 

Most Apache projects 

Including but not limited to : 

https://github.com/apache/maven
https://github.com/apache/spark
https://github.com/apache/kafka

All projects under openrewrite: https://github.com/openrewrite

Jackson : https://github.com/FasterXML/jackson

And many many others

**Comment by kobylynskyi** [comment]
Done. Thanks for the suggestion!
