### ISSUE TITLE
Option names are wrong in README?

### ISSUE THREAD

**Issue by benmccann** [kobylynskyi/graphql-java-codegen#110]
https://github.com/kobylynskyi/graphql-java-codegen/blob/master/plugins/maven/README.md calls the options `apiPackage` and `modelPackage`

However in https://github.com/kobylynskyi/graphql-java-codegen/blob/master/plugins/maven/graphql-java-codegen-maven-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/GraphQLCodegenMojo.java they're called `apiPackageName` and `modelPackageName`

I'm wondering if the README is outdated or if I missed somewhere a translation is happening

**Comment by kobylynskyi** [comment]
The correct name is what's defined in `GraphQLCodegenConfiguration` class (by the way it would be good if you can also implement it in your plugin)
I will fix README files in maven/gradle plugins. Thank you so much for finding this!

**Comment by benmccann** [comment]
Thanks!

It might be a bit tricky to implement `GraphQLCodegenConfiguration` in the sbt plugin. E.g. one challenge is that I think sbt plugins have to be written in Scala which has it's own collections API
