### ISSUE TITLE
Generated client model class doesn't contain query type as a property

### ISSUE THREAD

**Issue by TonyOuyangGit** [kobylynskyi/graphql-java-codegen#1148]
## Issue Description

Hi, I have a schema file defined as follows:
```
type IngestionSource {
  """
  The display name of the Ingestion Source
  """
  name: String!

  """
  Previous requests to execute the ingestion source
  """
  executions(start: Int, count: Int): IngestionSourceExecutionRequests
}

type IngestionSourceExecutionRequests {
  """
  The starting offset of the result set
  """
  start: Int

  """
  The number of results to be returned
  """
  count: Int

  """
  The total number of results in the result set
  """
  total: Int
}
```

and I generate using gradle and set `generateApis = true` and `generateClient = true`, the class generated for `IngestionSource` is:
```
public class IngestionSource implements java.io.Serializable {

    private static final long serialVersionUID = 1L;

    @javax.annotation.Nonnull
    private String name;
}
```

which doesn't contain the `executions` as a property, I think this query type doesn't get set as a property, am I missing any config that I should set?
## Steps to Reproduce

*List in detail the exact steps to reproduce the unexpected behavior.*

## Expected Result

I expect the generated class `IngestionSource` would have the property `executions` which the type is `IngestionSourceExecutionRequests`

## Actual Result

The generated class only contains property fields

## Your Environment and Setup

* **graphql-java-codegen version**: *5.6.0*
* **Build tool**: *Gradle*
* **Mapping Config**: * generateApis = true, generateClient = true*

```xml

<configuration>
    <outputDir>${project.build.directory}/generated-sources/graphql</outputDir>
    <packageName>io.github.kobylynskyi.graphql.model</packageName>
</configuration>
```

**Comment by kobylynskyi** [comment]
Hi,
This is related to #676
<https://github.com/kobylynskyi/graphql-java-codegen/issues/676> #476
<https://github.com/kobylynskyi/graphql-java-codegen/issues/476> #221
<https://github.com/kobylynskyi/graphql-java-codegen/issues/221>

Set generateParameterizedFieldsResolvers to false
Hope this helps.

ср, 5 квіт. 2023 р. о 7:11 пп Tony Ouyang ***@***.***> пише:

**Comment by TonyOuyangGit** [comment]
Great, thank you so much!
