### ISSUE TITLE
Generated models dont include fields with arguments

### ISSUE THREAD

**Issue by codezisland** [kobylynskyi/graphql-java-codegen#1149]
## Issue Description

We're trying to generate POJO classes from a schema that contains a field with arguments, something like this:

```
query {
    getPeople(id: String): [Person]
}

type Person {
    name: String
    movies(limit: Int!): [Movie]
}
```

The issue is that the generated model for **Person** is not including the fields **movies**.

## Steps to Reproduce

Generate models from a schema like the example

## Expected Result

```
class Person {
    String name;
    List<Movie> movies;
}
```

## Actual Result

```
class Person {
    String name;
}

```

## Your Environment and Setup

* **graphql-java-codegen version**: *5.6.0*
* **Build tool**: *E.g.: Maven*
* **Mapping Config**: *E.g.:*
custom_types_mapping = {"JSON" : "java.util.Map<java.lang.String, java.lang.String>"}
generate_equals_and_hashCode = True
generate_client = True

For the rest of the option we're using the default values.

```xml

<configuration>
    <outputDir>${project.build.directory}/generated-sources/graphql</outputDir>
    <packageName>io.github.kobylynskyi.graphql.model</packageName>
</configuration>
```

**Comment by kobylynskyi** [comment]
Hi, This is related to #1148 #676 #476 #221 Set generateParameterizedFieldsResolvers to false Hope this helps.

**Comment by codezisland** [comment]
It works perfectly, sorry for missing that in the documentation
