### ISSUE TITLE
Usage of class JavaPluginConvention should be replaced with JavaPluginExtension

### ISSUE THREAD

**Issue by bmuschko** [kobylynskyi/graphql-java-codegen#1150]
## Issue Description

You are using the class `JavaPluginConvention` in a [Gradle task implementation](https://github.com/kobylynskyi/graphql-java-codegen/blob/main/plugins/gradle/graphql-java-codegen-gradle-plugin/src/main/java/io/github/kobylynskyi/graphql/codegen/gradle/GraphQLCodegenGradleTask.java#L20). This class has been deprecated and will be removed from Gradle's API soon. All consumers of Gradle version's that removed the class will break.

From the [Gradle API](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/JavaPluginConvention.html):

> Deprecated.
Replaced by [JavaPluginExtension](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/JavaPluginExtension.html). This class is scheduled for removal in Gradle 9.0.
Is mixed into the project when applying the [JavaBasePlugin](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/JavaBasePlugin.html) or the [JavaPlugin](https://docs.gradle.org/current/javadoc/org/gradle/api/plugins/JavaPlugin.html).

## Steps to Reproduce

Apply Gradle plugin, run with `--warning-mode all`.

## Expected Result

No warning message is rendered for plugin.

## Actual Result

When build is run with `--warning-mode all`, the corresponding warning message is rendered.

## Your Environment and Setup

* **graphql-java-codegen version**: *[v5.7.1](https://github.com/kobylynskyi/graphql-java-codegen/releases/tag/v5.7.1)*
* **Build tool**: *Gradle 8.0*

**Comment by bmuschko** [comment]
Is this something you are planning to fix soon or would you rather want to receive a pull request?

**Comment by kobylynskyi** [comment]
There is already a PR created by @esfomeado for the same.
Can you take a look at it as let me know if the fix looks good to you as well?
Thanks

**Comment by bmuschko** [comment]
@kobylynskyi Perfect. LGTM!
