### ISSUE TITLE
Codegen tack error ('grammar' tokens limit)

### ISSUE THREAD

**Issue by portal-S** [kobylynskyi/graphql-java-codegen#1216]
I'm trying to generate code from a big schema file (about 5000 lines) , but i get an error:
More than 15,000 'grammar' tokens have been presented. To prevent Denial Of Service attacks, parsing has been cancelled.

io.github.kobylynskyi.graphql.codegen version 5.7.2

How can i resolve it? thank you

**Comment by portal-S** [comment]
just raised MAX_TOKENS value in graphql via graphqlCodegen task in build.gradle :

```
graphqlCodegen {
    ParserOptions.setDefaultParserOptions(ParserOptions.newParserOptions().maxTokens(30000).build())
    ..(your params)...

}
```

**Comment by nyas-spins** [comment]
@portal-S What gradle version did you run with?

**Comment by portal-S** [comment]
> @portal-S What gradle version did you run with?
sorry for late reply
gradle version 8.0
