### ISSUE TITLE
sbt plugin release discussion

### ISSUE THREAD

**Issue by benmccann** [kobylynskyi/graphql-java-codegen#124]
Probably the easiest way to publish would be to setup the [sbt-release](https://github.com/sbt/sbt-release) and [sbt-bintray](https://github.com/sbt/sbt-bintray) plugins. I think that will set it up to have a release process similar to Maven where it asks you for the release version and next development version and then do the release for you. The plugin should be available to all sbt users after publishing to bintray.

I'm not quite ready to release yet because I'd like to do some testing first. It also will require a new version of the core library to be released before we can release the first version of the sbt plugin. But I though I'd share since we can setup the bintray repo, update the build file, etc. in the meantime. In order to publish to the sbt bintray organization we have to follow these steps: https://www.scala-sbt.org/1.x/docs/Bintray-For-Plugins.html

Would you like to manage the bintray account and run the release commands (I'll setup the build file) so that you can release everything together when cutting a new version? Or do you want me to manage the releases for this plugin?

**Comment by kobylynskyi** [comment]
@benmccann thanks for bringing this up!
Sure, I can do the release process for all plugins together.
I will appreciate if you prepare all the required plugin files while I will setup the bintray organization. 
If everything will not be ready till that time, then we will release sbt-plugin separately some time afterward.

**Comment by benmccann** [comment]
I just learned that the company that develops sbt had a round of layoffs and the guy who helped me get this plugin setup was included (https://twitter.com/eed3si9n/status/1251246172779528195). So I'm kind of thinking about using a different web framework that will work with Maven or Gradle since I'm just setting up my new project. I'm not sure I want to tie myself to sbt if it doesn't have longevity. I'm not sure which direction I'll go yet, but I thought it was fair to let you know before we did a first release. I don't know if you'd want to keep the sbt plugin if I'm not using it and actively maintaining it? The code isn't too complicated as it's really just one file that calls the core library, but I'm not sure if you want to manage it. Thanks again for all your help in getting this all setup. Either way, I'll continue to use `graphql-java-codegen` it's just a question of which build system should I use it with

**Comment by kobylynskyi** [comment]
@benmccann Thanks for the update!
So do you suggest postponing sbt-plugin release?

I will release 1.7.0 version of Maven/Gradle plugins today. Please let me know if you decide using sbt so that I will release it too (not yet sure how, but will try)

**Comment by benmccann** [comment]
I've gotten a GraphQL server up using the Gradle plugin together with Micronaut, so at this point it seems unlikely I'll use the sbt-plugin. If you want to keep it for other users that's fine. If you want to delete it that's also fine.

**Comment by kobylynskyi** [comment]
Thanks for the update, @benmccann.
I will keep the code in the repo for some time. Maybe someone will be interested.
