### ISSUE TITLE
Mistake in Gradle README?

### ISSUE THREAD

**Issue by benmccann** [kobylynskyi/graphql-java-codegen#130]
## Issue Description

I'm trying out the Gradle plugin, but having some difficulty. 

## Steps to Reproduce
Create a Gradle project with the sample configuration from the README: https://github.com/kobylynskyi/graphql-java-codegen/tree/master/plugins/gradle#buildgradle

`outputDir = "$buildDir/generated/graphql"`

## Expected Result
Expected project to successfully build

## Actual Result
```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred evaluating root project 'micronaut-example'.
> Cannot cast object 'build/generated/graphql' with class 'org.codehaus.groovy.runtime.GStringImpl' to class 'java.io.File'
```

## Your Environment and Setup

* **graphql-java-codegen**: *1.7.0*
* **Build tool**: *Gradle 6.3*
* **Java tool**: *1.8*

## Additional context
Something else I noticed is that I'd expect there to be a default value for `outputDir`. The readme says the the default is `None`, so does that mean the plugin does nothing unless you set it?

**Comment by kobylynskyi** [comment]
@benmccann thanks for reporting this!
README was fixed.
And yes, `outputDir` is the mandatory field.

**Comment by benmccann** [comment]
Thanks! One more question. Is it right that these directories in the README don't match each other?

```
   outputDir = new File("$buildDir/generated/graphql")
sourceSets.main.java.srcDir "$buildDir/generated"
```

**Comment by kobylynskyi** [comment]
@benmccann It is fixed now. Thanks!
Please let me know if you will see some more inconsistencies.
