### ISSUE TITLE
parametrizedResolverAnnotations is not working

### ISSUE THREAD

**Issue by asndevever** [kobylynskyi/graphql-java-codegen#1329]
## Issue Description

During code generation Gql Resolvers are not enhanced with parametrizedResolverAnnotations  value.

## Steps to Reproduce
Run graphqlCodegen gradle task against below schema.

schema.graphqls

type Query {
    btecById(id: String!): Btec!
}

type Btec {
    activeStudentCount: Int!
}

## Expected Result
As per https://github.com/kobylynskyi/graphql-java-codegen/blob/main/docs/codegen-options.md
parametrizedResolverAnnotations should add method level annotation to codegen resolver.

public interface QueryResolver {
	@org.springframework.graphql.data.method.annotation.SchemaMapping(typeName = "Query")
    BtecGql btecById(@org.springframework.graphql.data.method.annotation.Argument String id);
}

## Actual Result

public interface QueryResolver {
    BtecGql btecById(@org.springframework.graphql.data.method.annotation.Argument String id);
}

## Your Environment and Setup

* **graphql-java-codegen version**: *5.8.0*
* **Build tool**: *Gradle 8.2*
* **Mapping Config**:

```xml

graphqlCodegen {
	graphqlSchemaPaths = ["$projectDir/src/main/resources/graphql/schema.graphqls".toString()]
	outputDir = new File("$buildDir/generated")
	apiPackageName = "io.test.graphql.api"
	modelPackageName = "io.test.model"
	customTypesMapping = [
			DateTime: "java.util.Date"
	]

	parametrizedResolverAnnotations = ["org.springframework.graphql.data.method.annotation.SchemaMapping(typeName=\"{{TYPE_NAME}}\")"]
	resolverArgumentAnnotations = ["org.springframework.graphql.data.method.annotation.Argument"]
	modelValidationAnnotation = ""
	modelNameSuffix = "Gql"
	generateApis = true
	generateApisWithThrowsException = false
	supportUnknownFields = false
	unknownFieldsPropertyName = "additionalFields"
}
```

**Comment by kobylynskyi** [comment]
@asndevever this annotation is added only to the methods for parametrized resolvers, and not for the queries.
In your example `btecById(id: String!): Btec!` is part of a `Query` type. It's a query, and therefore, not considered as a parametrized field.
