### ISSUE TITLE
"...on" is skipped in all$ methods for union and interface projections

### ISSUE THREAD

**Issue by sdaurea** [kobylynskyi/graphql-java-codegen#1375]
## Issue Description

Currently the generated method `all$` for projections does not include fields that start with "on" prefix.

## Steps to Reproduce

It is already reproduced by the test [here](https://github.com/kobylynskyi/graphql-java-codegen/blob/b13e0591cd2831e1eb9cfd2d30751ed97e312a1e/src/test/resources/expected-classes/response/LocationResponseProjection.java.txt#L39). The same can be reproduced for the union, but there is no such test for the union.

## Expected Result

It is expected that `onCustomerLocation` and `onDealerLocation` will be included into the `all$` method.

## Actual Result

Only `id`, `locationType` and `typename` are included.

## Your Environment and Setup

* **graphql-java-codegen version**: *5.8.0*
* **Build tool**: *Gradle*

**Comment by jxnu-liguobin** [comment]
Thank you for discovering it. This is a known legacy work!

**Comment by kobylynskyi** [comment]
The PR was merged. Will be released in 5.9.0. Stay tuned.
