### ISSUE TITLE
parameterized @external field resolver should not generate resolver methods

### ISSUE THREAD

**Issue by gzak** [kobylynskyi/graphql-java-codegen#1383]
## Issue Description

Take a look at the following [example](https://www.apollographql.com/docs/federation/entities-advanced#using-requires-with-fields-that-take-arguments) in the Apollo documentation.

Currently, this would generate a set of classes as follows:
```
class Product {
  id, shippingEstimate; // lazy shorthand
}

interface IQueryResolver {
  Product someRootResolver(...);
}

interface IProductResolver {
  Integer weight(Product product);
}
```

But it should not generate a separate `IProductResolver` interface for the `weight` field since it is marked `@external`, meaning this subgraph cannot resolve it. Instead, it should just generate a plain old field as part of the `Product` class, and assume that some other subgraph will resolve it:
```
class Product {
  id, weight, shippingEstimate; // lazy shorthand
}

interface IQueryResolver {
  Property someRootResolver(...);
}
```

**Comment by kobylynskyi** [comment]
@gzak please change the value of `generateParameterizedFieldsResolvers` to `false`.
There's a ticket planned in 6.0.0 to change the default value for this parameter (currently = `true`).
Hope this works. Otherwise, please reopen the ticket.
