### ISSUE TITLE
Codegen for graphql-java-tools

### ISSUE THREAD

**Issue by benmccann** [kobylynskyi/graphql-java-codegen#139]
## Where I am

I've got a basic GraphQL server up and running at this point. But I've only done the basics. There's a lot I haven't setup:

* Field selection - right now I just fetch all fields from a table from the database even if only some are returned to the user
* Batching / data loaders - I don't really understand how exactly to set this up yet
* Complex where clauses - I just have simple queries with zero or one arguments at the moment
* Error handling
* Any kind of security - authorization and limiting query depth/complexity or whitelisting persisted queries

## Ideas

It seems like you guys are both using graphql-java-tools? I stumbled across it as well and must say it's far easier to to use than core Java GraphQL library. I'm wondering how you guys solve some of the above challenges or if you've bothered yet

I'm wondering if we couldn't build some templates specifically for graphql-java-tools to make things easier with some of these.

**RDBMS query building**
E.g. at the moment my GraphQL and database fields have the same names, so I should be able to pass them from the query to the database for better DB query performance. Basically we need to take the fields listed in `DataFetchingEnvironment.getSelectionSet()` (btw, thanks for the `generateDataFetchingEnvironmentArgumentInApis` option :wink:) and pass them to the DB.

For where clauses we could generate a set of filters based on the fields and field types. [graphql-java-filter](https://github.com/gentics/graphql-java-filter) seems to do something along these lines, but looks to be code-first as opposed to schema-first

For pagination and order, we could come up with a standard way of representing these and also convert to the query automatically.

`GraphQLResolver` and `BatchLoader` are the easiest to generate because they just look up entities by their keys.

Then when we get the result back, we basically do the reverse mapping to copy fields from the result set to the GraphQL response.

I'm not doing any [look ahead](https://www.graphql-java.com/documentation/v14/fieldselection/) by doing joins to other tables. It would add complexity, the performance improvement is probably only 5ms per level (I haven't benchmarked), and it makes it easier to deal with situations like moving the data to another DB or microservice.

**Safety**

The danger of course is that a field is named slightly differently in the database than GraphQL schema, gets renamed, etc.

I'm generating Typesafe query builders by connecting to the DB already. So I could build a class that takes the generated fields from the DB and the generated fields from the GraphQL schema and matches them up to make sure everything compiles and there's nothing amiss. 

For field names that don't match in the DB and schema the user could provide a mapping

**Authorization, validation, business logic, etc.**

Obviously we'll need to include app-specific stuff. So probably we don't want the whole `GraphQLQueryResolver` to be generated. But we could, for example, generate classes for each type that take a `DataFetchingEnvironment` can return a response object with all the appropriate field selection, etc. so that each resolver is just a couple lines of code in the simple case. Or alternatively generate the file just once if it doesn't exist and then the user can modify from there though that would mean more work if you add a new field.

## Approaches

This probably should be a new library though could possibly live in this repo. I haven't dug much into the core library, but we could make it possible to provide user-provided templates perhaps if it's not already. Would love your thoughts on any of the above

**Comment by kobylynskyi** [comment]
@benmccann, thanks for your ideas. Really appreciate your input.
But I don't think we should do it in this library. If you want to create one - I would be happy to assist you!
