### ISSUE TITLE
Subscription methods with wrong return type

### ISSUE THREAD

**Issue by Smolli** [kobylynskyi/graphql-java-codegen#14]
Having a subscription in the schema generates a Subscription class with methods that have the wrong return type. Subscriptions have to return `org.reactivestreams.Publisher<T>`.

Given schema:

```graphql
schema {
  subscription: Subscription
}
type Subscription {
 projectsSub: Project!
}
type Project {
  id: String!
  name: String!
}
```

Generated class:
```java
public interface ProjectsSubSubscription {
    @javax.validation.constraints.NotNull
    Project projectsSub() throws Exception;
}
```

Expected:
```java
public interface ProjectsSubSubscription {
    @javax.validation.constraints.NotNull
    org.reactivestreams.Publisher<Project> projectsSub() throws Exception;
}
```

**Comment by kobylynskyi** [comment]
@Smolli please provide more info:
* Your schema
* Actually generates class
* What’s expected

**Comment by Smolli** [comment]
Hi @kobylynskyi,

I updated my description

**Comment by kobylynskyi** [comment]
@Smolli, done in https://github.com/kobylynskyi/graphql-java-codegen/releases/tag/v1.3.0
Will release maven and gradle plugins later today.
