### ISSUE TITLE
How to deploy offline?

### ISSUE THREAD

**Issue by jyjyj** [kobylynskyi/graphql-java-codegen#143]
Hi, how do I deploy this for an offline project? I will be using an offline Nexus repository, but do not have experience with handling Java dependencies offline. Thanks!

**Comment by kobylynskyi** [comment]
Have you tried [this](https://stackoverflow.com/a/49172777/668148)?

**Comment by jyjyj** [comment]
I'll take a look there, thanks @kobylynskyi!
