### ISSUE TITLE
Question around Query and Mutation Type Resolvers

### ISSUE THREAD

**Issue by JustinBlandford** [kobylynskyi/graphql-java-codegen#144]
Hi @kobylynskyi  @joffrey-bion 

I have a GraphQL schema which has the form:-

schema {
    query: QueryType
    mutation: MutationType
}

type QueryType {
	queries
}

type MutationType {
	mutations
}

When I run the Maven plugin, it generates interfaces called QueryTypeResolver and MutationTypeResolver which contains each query and mutation.  In your sample client code, the spec is in the format:-

schema {
    query: Query
    mutation: Mutation
}

type Query {
	queries
}

type Mutation {
	mutations
}

This then generates individual Mutation classes which can be used as shown in your example.  

Can you post an example of how to run the client side mutation using the  MutationTypeResolver interface as opposed to using the individual mutation classes?

**Comment by kobylynskyi** [comment]
@JustinBlandford Resolver classes are mainly used for fields resolving on the server side.
Could you please provide more details on how you want to use them?
Thanks.

**Comment by JustinBlandford** [comment]
@kobylynskyi I want to use the client code to invoke mutations.  In your sample code, the Mutation classes are generated if the Graph QL schema has Query and Mutation keywords in the schema.  As I mentioned above, if the types are defined as QueryType and MutationType, the mutations classes aren't being generated?  In order to get it to work, I had to modify the GraphQl schema to change the keywords back to Query and mutation in order for it to autogenerate the mutation classes.  I'd rather not have to modify the GraphQL schema at all if possible.

**Comment by kobylynskyi** [comment]
Oh, I see what you mean.
As of now, the plugin supports only types named `Query`, `Mutation`, `Subscription`.

**Comment by JustinBlandford** [comment]
No problem @kobylynskyi

**Comment by klowandev** [comment]
Hello! Any updates on this?
