### ISSUE TITLE
Methods returning interface cause compilation error (Version: [1.7.3])

### ISSUE THREAD

**Issue by ClaudiuGuja** [kobylynskyi/graphql-java-codegen#145]
The issue:
    Code generated from the following SDL generates the interface Foo with `Collection<Bar> getBars()` method and the implementation Foo1 with `Collection<Bar1> getBars()` method. Since the interface method is not overwritten, a compilation error takes place.

Proposed solution:
Perhaps the interface can be generated like this: `Collection<? extends Bar> getBars()` if the return type of the method would be an interface

The SDL:
```
interface Foo {
    id: ID!
    bars: [Bar]
}

interface Bar {
    id: ID!
}

type Foo1 implements Foo{
    id: ID!
    bars: [Bar1]
}

type Bar1 implements Bar{
    id: ID!
}

```

**Comment by kobylynskyi** [comment]
@ClaudiuGuja 
Fixed in [1.7.4](https://github.com/kobylynskyi/graphql-java-codegen/releases/tag/v1.7.4)
Please create another issue if you see any problems.
