### ISSUE TITLE
Use lombok to reduce boilerplate code in generated model files

### ISSUE THREAD

**Issue by jyjyj** [kobylynskyi/graphql-java-codegen#146]
Currently the model files generated are full of the typical OO-stuff: private variables and public getter/setters. Would it be helpful to generate less code by simply using lombok to annotate the generated classes?

**Comment by kobylynskyi** [comment]
Hey @jyjyj 
I don't see any sense doing this because this boilerplate code is auto-generated.
Moreover, lombok annotations do not work for generated sources (I already tried 😄)
