### ISSUE TITLE
Immutability

### ISSUE THREAD

**Issue by lorenzleutgeb** [kobylynskyi/graphql-java-codegen#149]
I'd like the DTOs generated by `graphql-java-codegen` to optionally be "immutable".

By "immutable" I mean that the generated classes do not have any setters. Very similar to to what Lombok does with its `@Value` annotation.

A generated class with this feature enabled should look like:
```java
public class Person {
    // Everything as usual, except...
    // NO SETTERS IN HERE
}
```

If you approve the addition of this feature, I am happy to implement and PR it.

**Comment by kobylynskyi** [comment]
Hi @lorenzleutgeb 
We can have another mapping config option (something like `generateModelsImmutable` with default = `false`)
We need to also consider that `get()` methods that return collection should return a copy of the collection.
If you would like to work on this feature, then please assign it to yourself. Thanks!

**Comment by lorenzleutgeb** [comment]
You're right. I might do it, but not today...

**Comment by joffrey-bion** [comment]
> We need to also consider that get() methods that return collection should return a copy of the collection.

Maybe they could simply make an immutable copy of the collection at construction time?
That would avoid creating new objects at every `get` call (but it would eagerly duplicate collection properties even if never accessed).

**Comment by lorenzleutgeb** [comment]
@joffrey-bion it would be interesting to see benchmarks... My uneducated guess would be to favour eager duplication in the constructor, because that would already break even in the case where every property is accessed at least once, right?

**Comment by xenoterracide** [comment]
I'm mostly looking for setter-less DTO's first, not too worried about the Array itself

**Comment by xenoterracide** [comment]
though maybe this code generator, could integrate with another code generator like immutables, don't know if that's possible.

**Comment by lorenzleutgeb** [comment]
Since this project already depends on Lombok, I quickly checked whether Lombok's `@Value` could be used. Turns out that it [does not generate unmodifiable copies of collections, and even though requested, this feature will not be implemented](https://github.com/rzwitserloot/lombok/issues/1504). So, I'd like to say "let's just do what Lombok does" and propose to implement the feature without the rather complicated requirement of making collections unmodifiable.

**Comment by joffrey-bion** [comment]
@xenoterracide Yeah I wouldn't worry too much about defensive copies of collections, either.

@lorenzleutgeb Just to clarify a bit, the fact that this project depends on Lombok should be irrelevant, because we're talking about the generated code that will belong to the target project. 
Also, Lombok is mostly a tool to help write and maintain more easily the code that people write by hand. Generating code that contains Lombok annotations is sort of pointless because it would need to then go through Lombok's generation, adding an extra step for no added maintainability.

**Comment by lorenzleutgeb** [comment]
> Also, Lombok is mostly a tool to help write and maintain more easily the code that people write by hand. Generating code that contains Lombok annotations is sort of pointless because it would need to then go through Lombok's generation, adding an extra step for no added maintainability.

Yeah I'm aware. I didn't mean to suggest to generate code with Lombok annotations, but to generate code that is essentially equivalent to what Lombok would generate if `@Value` would be present.

**Comment by joffrey-bion** [comment]
@lorenzleutgeb Yes, I was just answering the first part of your comment. But I agree with you on your conclusion ;)

**Comment by kobylynskyi** [comment]
Hey, @lorenzleutgeb 
In the description of this feature request, you mentioned that you might work on it. Do you still want to do that? I would appreciate your contribution. Thanks.

**Comment by lorenzleutgeb** [comment]
Yeah, I'd do it if you drop the requirement of instantiating unmodifiable collections and instead allow me to do it "the Lombok way", effectively just dropping setters but not having special getter implementations.

**Comment by kobylynskyi** [comment]
I am fine with Lombok approach

**Comment by lorenzleutgeb** [comment]
In order to avoid changes later on, let's also fix the "user interface": How would you like the configuration parameter to be called? I'd call it `generateValue` which might be a bit unintuitive.

**Comment by kobylynskyi** [comment]
How about ‘generateImmutableModels’ or ‘generateModelsImmutable’?

**Comment by lorenzleutgeb** [comment]
I think that `generateImmutableModels` (verb, adjective, noun) better fits other, already existing, names such as `generateAsyncApi`, so I'll choose that.

**Comment by lorenzleutgeb** [comment]
Just to confirm: Together with the feature described in #148, mapping MapStruct can now target immutable DTOs and will instantiate them with a builder :confetti_ball:
