### ISSUE TITLE
Generate custom queries using graphql-codegen-maven-plugin

### ISSUE THREAD

**Issue by xxpta** [kobylynskyi/graphql-java-codegen#1576]
## Issue Description

Hi graphql-codegen-maven,

I like your plugin and chose this for a big graphql integration project we are working on but currently unable to generate code for custom graphql queries like 

```
# Query to lookup Employee
query GetEmployeeByUuid($uuid: UUID!) {
  employees(filter: { uuids: [$uuid] }) {
    objects {
      current {
        name
      }
    }
  }
}
```

## Steps to Reproduce

1. Configure plugin in pom.xml
```
        <!-- GraphQL Dependencies -->
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-graphql</artifactId>
        </dependency>
        <dependency>
            <groupId>io.github.kobylynskyi</groupId>
            <artifactId>graphql-java-codegen</artifactId>
            <version>5.10.0</version>
        </dependency>
```
```
             <plugin>
                <groupId>io.github.kobylynskyi</groupId>
                <artifactId>graphql-codegen-maven-plugin</artifactId>
                <version>5.10.0</version>
                <executions>
                    <execution>
                        <id>os2mo-code-generation</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <!-- https://github.com/kobylynskyi/graphql-java-codegen/blob/main/docs/codegen-options.md -->
                            <graphqlSchemaPaths>
                                <graphqlSchemaPath>src/main/resources/graphql/schema.graphql</graphqlSchemaPath>
                                <path>src/main/resources/graphql/queries/sdmo.graphql</path>
                            </graphqlSchemaPaths>
                            <outputDir>${project.build.directory}/generated-sources/graphql</outputDir>
                            <packageName>dk.eg.sd.loen.functionhierarchy.os2mo.model</packageName>
                            <generatedAnnotation>jakarta.annotation.Generated</generatedAnnotation>
                            <modelValidationAnnotation>@jakarta.validation.constraints.NotNull</modelValidationAnnotation>
                            <generateClient>true</generateClient>
                            <generateToString>true</generateToString>
                            <generateEqualsAndHashCode>true</generateEqualsAndHashCode>
                            <modelNameSuffix>TO</modelNameSuffix>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```
3. Execute mvn compile
4. Look for generated GetEmployeeByUuidRequest/Response in target/generated-sources/graphql/dk/eg/sd/loen/functionhierarchy/os2mo/model

## Expected Result

I was expecting a Request/Response object being generated GetEmployeeByUuidRequest/Response from the sdmo.graphql but nothing happens, it just ignores the query.

## Actual Result
```
[INFO] --- graphql-codegen:5.10.0:generate (os2mo-code-generation) @ function-hierarchy ---
[INFO] Added the following path to the source root: C:\projects\organisation\function-hierarchy\target\generated-sources\graphql
Generated 712 classes from 2 schema(s) in folder C:\projects\organisation\function-hierarchy\target\generated-sources\graphql, took 2716 ms
```
## Your Environment and Setup

graphql-java-codegen version: 5.10.0
Apache Maven 3.9.6 (bc0240f3c744dd6b6ec2920b3cd08dcc295161ae)
Maven home: C:\Program Files\JetBrains\IntelliJ IDEA 2024.1.3\plugins\maven\lib\maven3
Java version: 17.0.10, vendor: Oracle Corporation, runtime: C:\tools\java\jdk-17.0.10
Default locale: en_US, platform encoding: Cp1252
OS name: "windows 11", version: "10.0", arch: "amd64", family: "windows"

```xml

<plugin>
                <groupId>io.github.kobylynskyi</groupId>
                <artifactId>graphql-codegen-maven-plugin</artifactId>
                <version>5.10.0</version>
                <executions>
                    <execution>
                        <id>os2mo-code-generation</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <!-- https://github.com/kobylynskyi/graphql-java-codegen/blob/main/docs/codegen-options.md -->
                            <graphqlSchemaPaths>
                                <graphqlSchemaPath>src/main/resources/graphql/schema.graphql</graphqlSchemaPath>
                                <path>src/main/resources/graphql/queries/sdmo.graphql</path>
                            </graphqlSchemaPaths>
                            <outputDir>${project.build.directory}/generated-sources/graphql</outputDir>
                            <packageName>dk.eg.sd.loen.functionhierarchy.os2mo.model</packageName>
                            <generatedAnnotation>jakarta.annotation.Generated</generatedAnnotation>
                            <modelValidationAnnotation>@jakarta.validation.constraints.NotNull</modelValidationAnnotation>
                            <generateClient>true</generateClient>
                            <generateToString>true</generateToString>
                            <generateEqualsAndHashCode>true</generateEqualsAndHashCode>
                            <modelNameSuffix>TO</modelNameSuffix>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by xxpta** [comment]
If I search chatGPT for "how to create a custom graphql query with variables for code generation using kobylynskyi graphql-codegen-maven-plugin" it comes up with the following response:

![image](https://github.com/user-attachments/assets/33d1433a-2a30-4b47-9fa9-0cada4c25593)

Which is confusing since the plugin does not provide the graphqlQueryPaths property and if I use graphqlSchemaPath/path the query is ignored.

Ive tried to debug the plugin (in Intellij) and notice it is excluded from code generation since the OperationDefinition is not instanceof NamedNode (in com.kobylynskyi.graphql.codegen.parser.GraphQLDocumentParser#processDefinition)...

**Comment by rwo-trackunit** [comment]
Hi. Yea, ChatGPT is unhelpful as always.

It seems to me you are conflating `.graphql` and `.graphqls` files. So client side vs server side. Or maybe I'm just missing the whole point. I have only used/worked on this project as server side.

I would expect you to have something like
```
schema {
    query: Query
}

type Query {
    employees(
        filters: FilterInput
```
in a `.graphqls` file, which defines the server side.

By setting  `<generateClient>true</generateClient>` it also generates projections that work as a client. That should enable you to use Java objects as client.

See fx. the [client example](https://github.com/kobylynskyi/graphql-java-codegen/blob/main/plugins/maven/example-client/src/test/java/io/github/kobylynskyi/order/service/CreateProductIntegrationTest.java#L30)

**Comment by xxpta** [comment]
thanks for clarifying @rwo-trackunit :-)

The graphql-codegen-maven seems unfit for my project requirements which is looking for a code generated schema first client plugin and the DGS Codegen (https://github.com/Netflix/dgs-codegen) seems to be match .

Issue can be closed!
