### ISSUE TITLE
Mapping and accessing "partial" responses

### ISSUE THREAD

**Issue by philipp-schmidt** [kobylynskyi/graphql-java-codegen#159]
I'm having trouble wrapping my head around the mapping between whatever GraphQLResult returns after a successful query and the generated classes.

I'm executing a mutation and fetch only a single field "access_token" from the response by setting the appropriate projection. The autogenerated response object "LoginUserResponse" has another field "user", which I'm not interested in.

```java
public void login() throws IOException, GraphQLException {
    LoginUserInput input = new LoginUserInput();
    input.setUsername(this.username);
    input.setPassword(this.password);

    LoginUserMutationRequest query = new LoginUserMutationRequest();
    query.setUser_data(input);

    // Only fetch field access_token, ignore all other fields
    LoginUserResponseResponseProjection projection = new LoginUserResponseResponseProjection().access_token();

    GraphQLResult<Map<String, LoginUserResponse>> result = this.queryEntity(query, projection);
    System.out.println(result.getData().get(query.getOperationName()).getAccess_token());
}

public <Q extends GraphQLOperationRequest, P extends GraphQLResponseProjection, R> GraphQLResult<Map<String, R>> queryEntity(Q query, P projection)  throws GraphQLException {
    GraphQLRequest request = new GraphQLRequest(query, projection);
    GraphQLResult<Map<String, R>> result = restTemplate.exchange(URI.create(this.endpoint + "/***/api/graphql"),
        HttpMethod.POST,
        new HttpEntity<String>(request.toHttpJsonBody(), createHeaders(request)),
        new ParameterizedTypeReference<GraphQLResult<Map<String, R>>>() {})
        .getBody();
    if (result.hasErrors()) {
        throw new GraphQLException(result.getErrors());
    }
    return result;
}
```

This leads to this error:

`java.lang.ClassCastException: class java.util.LinkedHashMap cannot be cast to class com.***.***.model.LoginUserResponse (java.util.LinkedHashMap is in module java.base of loader 'bootstrap'; com.***.***.model.LoginUserResponse is in unnamed module of loader 'app')`

Which makes sense, as the class LoginResponse would expect the field 'user' to be not null, but I'm not fetching this field, so constructing an instance of LoginResponse is impossible.

Could anyone give me a hint on how to properly access the fields I fetched? I can see that there are Mapper definitions in the examples, but I'm a little confused regarding the differences between ProductTO and Product, as I can not find two different classes for an entity in my autogenerated code.

Any help very much appreciated!

**Comment by philipp-schmidt** [comment]
This of course works perfectly fine:

```java
GraphQLResult<Map<String, LinkedHashMap<String, String>>> result = this.queryEntity(query, projection);
System.out.println(result.getData().get(query.getOperationName()).get("access_token"));
```

**Comment by kobylynskyi** [comment]
Hi @philipp-schmidt 
Could you please try the following approach:
```java
public void login() throws IOException, GraphQLException {
    LoginUserInput input = new LoginUserInput();
    input.setUsername(this.username);
    input.setPassword(this.password);

    LoginUserMutationRequest query = new LoginUserMutationRequest();
    query.setUser_data(input);

    // Only fetch field access_token, ignore all other fields
    LoginUserResponseResponseProjection projection = new LoginUserResponseResponseProjection().access_token();

    LoginUserResponseGraphQLResult result = queryEntity(query, projection, LoginUserResponseGraphQLResult.class);
    System.out.println(result.getData().get(query.getOperationName()).getAccess_token());
}

public <Q extends GraphQLOperationRequest, P extends GraphQLResponseProjection, R extends GraphQLResult<?>> R queryEntity(Q query, P projection, Class<R> responseType)  throws GraphQLException {
    GraphQLRequest request = new GraphQLRequest(query, projection);
    R result = restTemplate.exchange(URI.create(this.endpoint + "/***/api/graphql"),
        HttpMethod.POST,
        new HttpEntity<String>(request.toHttpJsonBody(), createHeaders(request)),
        responseType).getBody();
    if (result.hasErrors()) {
        throw new GraphQLException(result.getErrors());
    }
    return result;
}

private static class LoginUserResponseGraphQLResult extends GraphQLResult<Map<String, LoginUserResponse>> {}
```

Please let me know how it works out.

**Comment by philipp-schmidt** [comment]
That did the trick!
So I guess the generics were causing the problem? 
Anyway, thank you very much for the help, very much appreciated!

**Comment by kobylynskyi** [comment]
Yeah, genetics caused that problem.
I should probably add this “hack” to the example project.

**Comment by philipp-schmidt** [comment]
Is there maybe a way to avoid having to declare the static class?
Or maybe even derive the response type from R? R.class does not work obviously.

Its fully functional at this point, but having to declare the static class GraphQL wrapper means an additional manual definition per response type...

**Comment by kobylynskyi** [comment]
Probably it makes sense to generate this kind of class by the library.
What do you think?

**Comment by philipp-schmidt** [comment]
Frankly, I lack the overview about the project to make the decision, but from my point of view this would make perfect sense :)

**Comment by kobylynskyi** [comment]
@philipp-schmidt I've already started working on this.
Here's the additional class that will be generated:
```java
import com.kobylynskyi.graphql.codegen.model.graphql.GraphQLResult;

import java.util.Map;

public class LoginUserResponseGraphQLResult extends GraphQLResult<Map<String, LoginUserResponse>> {

    public LoginUserResponse loginUser() {
        Map<String, LoginUserResponse> data = getData();
        return data != null ? data.get(LoginUserMutationRequest.OPERATION_NAME) : null;
    }
}
```

So that in the client code it will look a bit simplified:
```java
    LoginUserResponseGraphQLResult result = queryEntity(query, projection, LoginUserResponseGraphQLResult.class);
    result.loginUser().getAccess_token();
```

Please let me know what you think

**Comment by philipp-schmidt** [comment]
Looks good to me. Having the operation name being resolved automatically is a nice plus!
Will this work with Lists?

**Comment by kobylynskyi** [comment]
@philipp-schmidt [version 1.8.1](https://github.com/kobylynskyi/graphql-java-codegen/releases/tag/v1.8.1) was released today.
It should generate an additional class as described above or in [example-client](https://github.com/kobylynskyi/graphql-java-codegen/blob/master/plugins/gradle/example-client/src/main/java/io/github/kobylynskyi/order/external/ProductServiceGraphQLClient.java)
