### ISSUE TITLE
Union query requests in client code with conditional fragments

### ISSUE THREAD

**Issue by philipp-schmidt** [kobylynskyi/graphql-java-codegen#164]
I am trying to run a query returning a union type (e.g. the union Vehicle = Car | Bike).

Is there a way to run this query with the current library? In a raw GraphQL call this would be achieved using conditional fragments like so:

```graphql
query allVehicles {
    allVehicles {
        ...on Car {
            brand
        }
        ...on Bike {
            weight
        }
    }
}
```

I can't seem to find a way to run the query allVehicles with the current library. Car and Bike both extend the class Vehicle, but Vehicle is a completely empty stub class.

I would expect to have a VehicleUnionResponseProjection with builder options like ".onCar(_CarResponseProjection_)" and ".onBike(_BikeResponseProjection_). Would this be possible? Or is there even currently a way to achieve this with a different apporach?

**Comment by philipp-schmidt** [comment]
I think it would even be sufficient if it was possible to select a single fragment only.
I don't think there is a nice solution in Java to return instances of different classes. So having Car and Bike being returned by the query is probably a nightmare to cast the classes or even putting them together in a List.
Maybe something like "VehicleUnionCarResponse" is enough? This could then only return instances of Car from queries returning the Vehicle union, ignoring all other types (by checking __typename__, the default GraphQL field returned by unions).

**Comment by kobylynskyi** [comment]
@philipp-schmidt thanks for your feature request. That's a really nice feature to have.
Basically we will need to:
1. Add `__typename` (by default) to the response projection of the union.
2. Generate custom serializers for union types (which will take into account `__typename` from the response). Something like [this](https://stackoverflow.com/a/34128468/668148). But we should consider various serializer libraries that the client will use (Jackson.
 gson, json-simple, etc). Maybe by specifying it in the plugin options:
```xml
          <!-- Generate GraphQL client classes from schema. -->
          <plugin>
            <groupId>io.github.kobylynskyi</groupId>
            <artifactId>graphql-codegen-maven-plugin</artifactId>
            <version>1.8.1</version>
            <executions>
                <execution>
                    ...
                    <configuration>
                        <generateClient>true</generateClient>
                        <serializer>jackson</serializer> <!-- gson, etc-->
                        ...
```

Please let me know what you think.

**Comment by philipp-schmidt** [comment]
Having multiple serializer options would be nice to have. However, for many users this might be a "just use the default" situation.

What would the result type of the query look like? A list of instances of the interface type? So the user will have to _instanceof_ typecheck?

**Comment by elebeaup** [comment]
@kobylynskyi It is already possible to define custom serializer with `customAnnotationsMapping` (but I may be wrong).

For instance, the configuration
```
<customAnnotationsMapping>
  <Vehicle>com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = com.test.jackson.VehiclesDeserializer.class</Vehicle>
</customAnnotationsMapping>
```

generate the following code :
```
public class Query implements java.io.Serializable {

    @com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = com.test.jackson.VehicleDeserializer.class)
    private Vehicle allVehicles;
```

So, the only need is to add `__typename` to the projection of the union and generate the union class.
For instance, like :
```
public class VehicleUnionResponseProjection extends GraphQLResponseProjection {

    public VehicleUnionResponseProjection() {
    }

    public VehicleUnionResponseProjection car(CarResponseProjection subProjection) {
        return car(null, subProjection);
    }

    public VehicleUnionResponseProjection car(String alias, CarResponseProjection subProjection) {
        fields.add(new GraphQLResponseField("...on Car").alias(alias).projection(subProjection));
        return this;
    }

    public VehicleUnionResponseProjection bike(BikeResponseProjection subProjection) {
        return bike(null, subProjection);
    }

    public VehicleUnionResponseProjection bike(String alias, BikeResponseProjection subProjection) {
        fields.add(new GraphQLResponseField("...on Bike").alias(alias).projection(subProjection));
        return this;
    }
}
```

**Comment by kobylynskyi** [comment]
The feature will be released next week. Stay tuned! :)
