### ISSUE TITLE
Field aliases support for client generator

### ISSUE THREAD

**Issue by lmartellotto** [kobylynskyi/graphql-java-codegen#173]
**Is your feature request related to a problem? Please describe.**
GraphQL supports aliases: https://graphql.org/learn/queries/#aliases. For queries, it allows to rename fields as the client want. Moreover, it allows to query two same fields (with differents parameters) in a same query. For example, if my schema looks like:

```
type Query {
    itemById(id: Int!): Item!
}

type Item {
  name: String
}
```

I can write the following query:

```
query { 
  itemById(id: 1) {
     name
     amazingName: name
   }
}
```

But currently, we cannot generate this query with the client code generator. 

**Describe the solution you'd like**
I think about a simple solution: generate additive method(s) in generated GraphQLResponseProjection classes, which take an `String` parameter. For example, in my `ItemResponseProjection`, I will have:

```java
public class ItemResponseProjection extends GraphQLResponseProjection {

    public ItemResponseProjection() {
    }

    public ItemResponseProjection name() {
        ...
    }

    public ItemResponseProjection name(String alias) {
        ...
    }
```

Of course, it multiplies generated methods by two. Specially for fields which have also `GraphQLParametrizedInput`.

In order to simplify the string serialization (`GraphQLResponseProjection.toString()`), I think it could be a good idea to create a `GraphQLResponseField` class, which contains all information about a queried field, for example (largely simplified class) :

```java
    class GraphQLResponseFied {
        String alias;
        String fieldName;
        GraphQLParametrizedInput input;
        GraphQLResponseProjection projection;
    }
```

Each method in `GraphQLResponseProjection` classes will create an `GraphQLResponseFied` and put it in a simple list (instead of two maps `fields` and `parametrizedInputs`).

In a future, we can imagine that this class could contain other information about a field, like query directives.

What do you think?

**Comment by kobylynskyi** [comment]
I like the idea

**Comment by lmartellotto** [comment]
Ok, cool! Can I make a PR?

**Comment by kobylynskyi** [comment]
That would be great! Thanks.
But please create a fork from 2.0.0 branch (I haven’t merged it to master yet)

**Comment by kobylynskyi** [comment]
Thanks @lmartellotto for implementing this.
I will release it as part of 2.0.0 this week.
