### ISSUE TITLE
Code generation using gradle plugin fails for NonNullType of List with empty list as default value (Version: graphql-java-codegen 1.7.3)

### ISSUE THREAD

**Issue by IntiG** [kobylynskyi/graphql-java-codegen#177]
## Issue Description

Code generation using gradle plugin from graphql schema fails with this message:
`Unexpected array default value for non-list type`

Here is a snippet of the schema, I actually identified the part that fails:
```
type Query {
  "Select error events"
  select_error(
    "Maximum number of objects to return"
    first: Int! = 1000, 
    "List of possible options for the group by"
    group_by: [bus_error_groupby_enum!]! = []
  ): [error_activity]
```

the part that causes the issue is this:
`group_by: [bus_error_groupby_enum!]! = []`
 changing it to this, gets rid of the issue:
`group_by: [bus_error_groupby_enum!] = []`

I tried the code to understand where it came from and apparently it is in 
src/main/java/com/kobylynskyi/graphql/codegen/mapper/DefaultValueMapper.java

```
  private static String mapArray(MappingContext mappingContext, ArrayValue defaultValue, Type<?> graphQLType) {
        if (!(graphQLType instanceof ListType)) {
            throw new IllegalArgumentException("Unexpected array default value for non-list type");
        }
```
the defaultValue is a list while the type is actually not a ListType but a NonNullType

## Steps to Reproduce
Add this to your schema and try to generate the code
`group_by: [bus_error_groupby_enum!]! = []`

## Expected Result
I would expect a NonNullType of List to accept a default value of type List

## Actual Result
Code generation using gradle plugin from graphql schema fails with this message:
`Unexpected array default value for non-list type`

## Your Environment and Setup

* **graphql-java-codegen**: *1.7.3*
* **Build tool**: *Gradle*
* **Java tool**: *AdoptOpenJdk 11.0.6.10-hotspot*
* **Mapping Config**: 

```
graphqlCodegen {
    graphqlSchemaPaths = ["$projectDir/generated_schema.graphqls".toString()]
    outputDir = new File("$buildDir/generated")
    generateApis = true
    generateToString = true
    modelValidationAnnotation = ""
    generateRequests = true
}

```

**Comment by kobylynskyi** [comment]
@IntiG, thanks for a very explanatory description!
The fix is on the way and should be available this week as part of version 2.0.0.

**Comment by kobylynskyi** [comment]
Please also note that `generateRequests` was deprecated in favor of `generateClient` (see #169)

**Comment by IntiG** [comment]
@kobylynskyi thanks for this very cool plugin of yours, I like how readable and easy it is to build queries with the generated code :)
I'll switch to using `generateClient` thanks for letting me know.

On a side note, may I ask if you plan on supporting sbt plugin again? I know that there was one but not published and with a bit less "capabilities".
