### ISSUE TITLE
Generated types should be annotated with javax.annotation.processing.Generated

### ISSUE THREAD

**Issue by lorenzleutgeb** [kobylynskyi/graphql-java-codegen#178]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Any generated type (class, interface, enum, ...) should be annotated with [`Generated`](https://docs.oracle.com/en/java/javase/11/docs/api/java.compiler/javax/annotation/processing/Generated.html).

**Describe alternatives you've considered**
I have not considered any alternative solutions.

**Additional context**
Other code generation libraries do this. Examples:

##### MapStruct

```java
@Generated(
  value = "org.mapstruct.ap.MappingProcessor",
  date = "2020-06-16T13:43:26+0200",
  comments = "version: 1.3.1.Final, compiler: javac, environment: Java 11.0.2 (Oracle Corporation)"
)
public class MyMapperImpl implements MyMapper {}
```

##### Hibernate JPA Model Generation

```java
@Generated(value = "org.hibernate.jpamodelgen.JPAMetaModelEntityProcessor")
@StaticMetamodel(MyEntity.class)
public abstract class MyEntity_  {}
```

##### OpenAPI Tools

See [here](https://github.com/OpenAPITools/openapi-generator/blob/32adeddd8fd6e217eca2092f4bf370e6d6e7ea33/samples/openapi3/client/petstore/java/jersey2-java8/src/main/java/org/openapitools/client/model/Pig.java#L58).

**Comment by kobylynskyi** [comment]
We could do something similar to what mapstruct does:
https://github.com/mapstruct/mapstruct/pull/1625/files
```java
        if (versionInformation.isSourceVersionAtLeast9() &&
            typeFactory.isTypeAvailable( "javax.annotation.processing.Generated")) {
            generatedType = typeFactory.getType("javax.annotation.processing.Generated");
        } else if (typeFactory.isTypeAvailable("javax.annotation.Generated")) {
            generatedType = typeFactory.getType("javax.annotation.Generated");
        } else {
            generatedType = null;
        }
```

**Comment by lorenzleutgeb** [comment]
Good idea. However, at the moment release 2 should take priority, and this can be done anytime, since it's just added-value and backward-compatible.

**Comment by kobylynskyi** [comment]
Agree
