### ISSUE TITLE
Maven plugin url incorrect in Readme.md

### ISSUE THREAD

**Issue by valinha** [kobylynskyi/graphql-java-codegen#19]
In Readme.md file the url of grapqhl-java-codegen-maven-plugin is incorrect. 

Incorrect url:
https://github.com/kobylynskyi/grapqhl-java-codegen-maven-plugin

Fixed url:
https://github.com/kobylynskyi/graphql-java-codegen-maven-plugin

**Comment by kobylynskyi** [comment]
Thanks for fixing this
