### ISSUE TITLE
GraphQL Float is supposed to be double-precision

### ISSUE THREAD

**Issue by joffrey-bion** [kobylynskyi/graphql-java-codegen#22]
**Describe the bug**
By default, GraphQL `Float` type result in a `Float` in Java.
However, the specification states that Float in GraphQL is a double-precision floating point value, and should therefore be a `Double` instead (at least by default).

**Expected behavior**
The property type should be `Double` in Java for a GraphQL field declared as `Float`.

**Steps to reproduce**
Use this schema:
```
type MyType {
    someFloat: Float
}
```

**Comment by kobylynskyi** [comment]
@joffrey-bion, thanks for creating this issue.
Will you have time to work on it? If no, then I can pick it up.

**Comment by joffrey-bion** [comment]
I'm taking it, it shouldn't be too long I think. I'll wait for you to merge https://github.com/kobylynskyi/graphql-java-codegen/pull/21 first, though, as I'll need to update the float default literal as well
