### ISSUE TITLE
Pagination support

### ISSUE THREAD

**Issue by elebeaup** [kobylynskyi/graphql-java-codegen#220]
## Issue Description

First of all thank you for the great job you have done.
GraphQL supports pagination (https://graphql.org/learn/pagination/). But, I can't find a way to get the response with the client code generator.

## Steps to Reproduce
Generate the code for the schema :
```
type Search {
    cities(first: Int): [String]
}

type Query {
    search: Search
}
```

## Expected Result
I would expect to have a Search class with a getCities method but this is not the case.

## Actual Result
No getCities method.

## Your Environment and Setup

* **graphql-java-codegen**: *2.1.0*
* **Build tool**: *Maven*

**Comment by kobylynskyi** [comment]
hi @elebeaup 
by default the value of `generateParameterizedFieldsResolvers` is true. Which means that all fields that have parameters will not be added to the type, but instead, they will be added to Resolver interface.
So please try to setting this parameter to `false`:
```xml
<generateParameterizedFieldsResolvers>false</generateParameterizedFieldsResolvers>
```
So that Search class will have `List<String> cities;`
Please let me know how it goes.

**Comment by elebeaup** [comment]
Thank you very much. It works.

**Comment by ChopperlaAditya** [comment]
Hi @elebeaup and @kobylynskyi 
I want to implement pagination and tried <generateParameterizedFieldsResolvers>false</generateParameterizedFieldsResolvers> but it didn't help me. We can see generated DTO's but from where I can send the cursor value for pagination.

I too used same version 2.1.0, if possible can you share me your working sample, so I can use that and give a try.

Please check the detailed issue at [SO](https://stackoverflow.com/questions/68374501/generate-dto-classes-using-graphql-codegen-maven-plugin-when-sub-type-has-argume)
