### ISSUE TITLE
Model object is missing objects (Version: 2.1.0)

### ISSUE THREAD

**Issue by ShenduNL** [kobylynskyi/graphql-java-codegen#221]
## Issue Description
I'm working on the same project xtroce from issue #176 (if this information is of any help)

I've generated code based on an introspection query with the latest version of the maven plugin.
In some models it seems that there are some objects missing.
These objects do appear in the ResponseProjection objects of the same name.

For instance I am missing the lineitems object.

The schema I use can be found here: https://pastebin.com/XF9yxKBc

## Steps to Reproduce
Run the maven install.

## Expected Result
The class OrderMyClientModel has all the variables/objects specified in the graphqlschema

## Actual Result
The class OrderMyClientModel does not contain a lineitems object
(also missing are ordertransaction, suggestedrefund, eventconnection, draftfulfillment, discountapplicationconnection, fulfillment, metafield, metafieldconnection and orderrisk objects). 
Though at the moment the lineitems are needed the most.

## Your Environment and Setup

* **graphql-java-codegen**: *2.1.0*
* **Build tool**: *Maven*
* **Java tool**: *openJDK 14*
* **Mapping Config**:  

```
<configuration>
                            <graphqlSchemaPaths>
                                <graphqlSchemaPath>${project.basedir}/src/main/resources/schema.graphqls
                                </graphqlSchemaPath>
                            </graphqlSchemaPaths>
                            <outputDir>${project.basedir}/src/gen/java</outputDir>
                            <apiPackageName>test.graphql.client.api</apiPackageName>
                            <modelPackageName>test.graphql.client.model</modelPackageName>
                            <customTypesMapping>
                                <Date>java.util.Date</Date>
                                <DateTime>java.util.Date</DateTime>
                                <Decimal>java.math.BigDecimal</Decimal>
                                <FormattedString>java.lang.String</FormattedString>
                                <HTML>java.lang.String</HTML>
                                <JSON>org.json.JSONObject</JSON>
                                <Money>java.math.BigDecimal</Money>
                                <StorefrontID>java.lang.String</StorefrontID>
                                <UnsignedInt64>java.lang.Long</UnsignedInt64>
                                <URL>java.net.URI</URL>
                                <UtcOffset>java.lang.String</UtcOffset>
                            </customTypesMapping>
                            <modelNameSuffix>MyClientModel</modelNameSuffix>
                            <requestSuffix>MyClientRequest</requestSuffix>
                            <responseProjectionSuffix>MyClientResponseProjection</responseProjectionSuffix>
                            <parametrizedInputSuffix>MyClientParametrizedInput</parametrizedInputSuffix>
                            <generateClient>true</generateClient>
                            <generateApis>true</generateApis>
                            <generateModelsForRootTypes>true</generateModelsForRootTypes>
                            <typeResolverSuffix>MyTypeResolver</typeResolverSuffix>
                        </configuration>
```

## Additional context
I don't know how to describe my problem any better, if more info is needed please ask.

**Comment by kobylynskyi** [comment]
Hi @ShenduNL 
That’s because by default parametrized fields are not being added to types. Instead, Resolver interface is being created for such fields.
See description of parameter “generateParameterizedFieldsResolvers” on [codegen options page](https://github.com/kobylynskyi/graphql-java-codegen/blob/master/docs/codegen-options.md).

If you want to disable this, just set this parameter to false.
Please let me know if it works for you.

**Comment by ShenduNL** [comment]
That did the trick, thank you.
And thanks for the fast reaction. :)

I'm quite new to GraphQL and didn't know exactly where to ask my question.
