### ISSUE TITLE
Response projections do not support GraphQL interfaces

### ISSUE THREAD

**Issue by jdarc** [kobylynskyi/graphql-java-codegen#226]
## Issue Description
Generated response projection classes do not appear to support fields that implement interfaces. There does not appear to be a mechanism to specify sub-projections on these fields. Attempting to use the interface field on a projection results in an error: `Sub selection required for type Location`

## Steps to Reproduce
Run the code generation agains the following schema:
```graphql
schema {
    query: Query
}

type Query {
    vehicleById(vehicleId: ID!): Vehicle
}

interface Location  {
    id: ID!
    locationType: String!
}

type CustomerLocation implements Location  {
    id: ID!
    locationType: String!
    postCode: String!
}

type DealerLocation implements Location {
    id: ID!
    locationType: String!
    dealerCode: String!
}

type Vehicle {
    vehicleId: ID!
    registrationNumber: String!
    location: Location!
}
```

## Expected Result
The generated VehicleResponseProjection class should have the ability to specify a LocationResponseProjection sub-projection:
```java
public VehicleResponseProjection location(LocationResponseProjection subProjection) {
    return location(null, subProjection);
}

public VehicleResponseProjection location(String alias, LocationResponseProjection subProjection) {
    fields.add(new GraphQLResponseField("location").alias(alias).projection(subProjection));
    return this;
}
```

LocationResponseProjection should allow specification of base fields and specialised fields:
```java
locationResponseSubProjection
    .id()
    .locationType()
    .onCustomerLocation(new CustomerResponseProjection().postCode())
    .onDealerLocation(new DealerResponseProjection().dealerCode())
```

## Actual Result
The generated VehicleResponseProjection class does not have the ability to specify a Location response sub-projection:
```java
public VehicleResponseProjection location() {
    return location(null);
}

public VehicleResponseProjection location(String alias) {
    fields.add(new GraphQLResponseField("location").alias(alias));
    return this;
}
```

## Your Environment and Setup

* **graphql-java-codegen**: *2.2.0*
* **Build tool**: *Gradle 6.3*
* **Java tool**: *openjdk version "11.0.7"*
 
```groovy
graphqlCodegen {
    graphqlSchemaPaths = ["$projectDir/src/main/resources/vehicle.graphqls".toString()]
    outputDir = new File("$projectDir/src/main/generated")
    packageName = 'uk.co.mo.demo.graphql'
    customTypesMapping = [DateTime: 'java.util.Date']
    modelNameSuffix = 'TO'
    generateClient = true
    generateApis = false
}
```

**Comment by kobylynskyi** [comment]
@jdarc thanks for reporting this issue.
I fixed it in #227 and planning to release it tomorrow as part of v2.2.1.
Stay tuned!
