### ISSUE TITLE
support sbt plugin

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#232]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kobylynskyi** [comment]
Thanks, @jxnu-liguobin.
@benmccann already created similar request some time back: #124
There are several notes from my side:
1. Will you be able to maintain the plugin (support all available config options)? Since I don't have an expertise in Scala.
2. I'd prefer to first add support of all config options in sbt-plugin and then make it available in this repository.
3. We will need to set-up the infrastructure to publish it to some repo (Bintray probably).

**Comment by jxnu-liguobin** [comment]
On，it support all options

**Comment by jxnu-liguobin** [comment]
In addition to not implementing graphqlcodegenconfiguration, because I don't know what the relationship between this implementation and option is, I can use the plugin's option without implementation graphqlcodegenconfiguration. like i have show it to me. Of course, if there is a problem, I will fix it. I mainly write Scala

**Comment by kobylynskyi** [comment]
It's not a big deal in not implementing `GraphQLCodegenConfiguration`. The main purpose was just to keep all plugins in sync using this interface. But if it is not really possible to implement such interface, then it's fine.

**Comment by jxnu-liguobin** [comment]
OK, i will do

**Comment by kobylynskyi** [comment]
@jxnu-liguobin as part of #236 #228 I added two new config parameters: `apiAsyncReturnType` and `apiAsyncReturnListType`.
Please update the sbt plugin implementation as well as readme.
Thanks1

**Comment by jxnu-liguobin** [comment]
I have update pr, contains 
1. add key apiAsyncReturnType and apiAsyncReturnListType,
2. refactor some codes
3. update sbt-test with two options version is 2.2.2-SNAPSHOT

**Comment by kobylynskyi** [comment]
The only thing pending is to update the release dependency to `2.4.0` and set plugin version to the next release version - `2.4.1-SNAPSHOT`.
Thanks for your contribution.

**Comment by kobylynskyi** [comment]
Appreciate the work you have done.
Since the plugin was released, I think we can close this issue.

To keep all plugin releases in-sync in the future, I will open the separate ticket (assigned to you) to release the sbt-plugin (once I release the core library and maven/gradle plugins).
