### ISSUE TITLE
Support for async resolvers

### ISSUE THREAD

**Issue by ReneBL** [kobylynskyi/graphql-java-codegen#24]
At the moment, we already have the possibility of defining a reactive approach for Subscriptions using the _subscriptionReturnType_ in the configuration.

It would be a great idea to define some configuration property to specify the need for a reactive approach for the rest of the resolvers too. Currently, libraries like [graphql-java-spring-webflux](https://github.com/graphql-java/graphql-java-spring/tree/master/graphql-java-spring-webflux) or [graphql-kickstart-spring-webflux](https://github.com/graphql-java-kickstart/graphql-spring-boot/tree/master/graphql-kickstart-spring-webflux) allows us to return CompletableFuture<?> from the resolvers.

What do you think about generating resolvers returning _Mono_ or _CompletableFuture_ in order to get the most out of that facility?

**Comment by kobylynskyi** [comment]
Released in v1.4.1.
@ReneBL thank you for the contribution! I've added you as a collaborator to the repository..
