### ISSUE TITLE
Support multiple annotations used on the same class or field in a native way instead of string concatenation

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#248]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
customAnnotationsMapping 
```
  val mapping = new util.HashMap[String, Set[String]]

  val annotationsA = new util.HashSet[String]
  val annotationsB = new util.HashSet[String]

  annotationsA.add(annotionA)
  annotationsA.add(annotionB)

  annotationsB.add(annotionC)
  annotationsB.add(annotionD)

  mapping.put(fieldA,  annotationsA)
  mapping.put(fieldB,  annotationsB)

```

**Describe alternatives you've considered**

**Additional context**

**Comment by kobylynskyi** [comment]
@jxnu-liguobin Thanks for this feature request.
I've implemented it in **develop** branch (version 3.0.0). So feel free to update sbt-plugin implementation. Thanks!

**Comment by jxnu-liguobin** [comment]
> So feel free to update sbt-plugin implementation.

ok

**Comment by kobylynskyi** [comment]
@jxnu-liguobin I've created a separate issue to track sbt-plugin changes: #276

**Comment by kobylynskyi** [comment]
Version 3.0.0 was released today.
