### ISSUE TITLE
Changed enum capitalization when using java reserved words (Version: 2.4.0)

### ISSUE THREAD

**Issue by Nithanim** [kobylynskyi/graphql-java-codegen#249]
## Issue Description

Using reserved java words as enum names results in capitalization which is then used in the query. This results in a rejected request (by AWS Appsync) because the enum is not defined in the schema.

## Steps to Reproduce

Let's assume the following graphql schema:

```graphql
type Mutation {
    updateTest(message: TestEnum): String
}

enum TestEnum {
    long,
    short,
    high,
    low
}
```

and generate the model and client from it. We use it like this:

```java
public static void main(String[] args) {
    UpdateTestMutationRequest mutReq = new UpdateTestMutationRequest();
    mutReq.setMessage(TestEnumTO.Long);
    GraphQLRequest req = new GraphQLRequest(mutReq);
    String json = GraphQLRequestSerializer.toHttpJsonBody(req);
    System.out.println(json);
}
```
The printed line is the query later sent to the server. 

## Expected Result
```
{"query":"mutation { updateTest(message: long) }"}
```

## Actual Result
```
{"query":"mutation { updateTest(message: Long) }"}
```
Since the query is generated [by the serializer using #toString()](https://github.com/kobylynskyi/graphql-java-codegen/blob/03e6b5cc12a5a729676222f49dae21d7ecbe5c9a/src/main/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLRequestSerializer.java#L98) the capitalized name is used.

## Your Environment and Setup

* **graphql-java-codegen**: 2.4.0
* **Build tool**: Maven
* **Java tool**: openjdk version "1.8.0_252"; OpenJDK Runtime Environment (build 1.8.0_252-8u252-b09-1ubuntu1-b09)

* **Mapping Config**:

```xml
<configuration>
    <graphqlSchemas>
        <rootDir>${project.basedir}/schema</rootDir>
    </graphqlSchemas>
    <outputDir>${project.build.directory}/generated-sources/graphql</outputDir>
    <packageName>test.model</packageName>
    <modelNameSuffix>TO</modelNameSuffix>
    <generateClient>true</generateClient>
</configuration>
```

## Additional context

- The problem seems similar to https://github.com/kobylynskyi/graphql-java-codegen/issues/237.
- I only looked at the client side when building the query. There might be a problem when receiving a response as well.
- I temporarily worked around this problem using https://github.com/Nithanim/graphql-java-codegen/commit/b8f5c0085e4c41e63f3764f7c50492d7b702b2ad which seemed to work flawlessly.
- Thank you for the awesome generator!
- [Minimal maven test project](https://github.com/kobylynskyi/graphql-java-codegen/files/4976562/minimal.zip)

**Comment by kobylynskyi** [comment]
@Nithanim thank you so much for reporting this issue and providing your workaround (which I used a reference).
You can take a look at the fix at the referenced PR. Once it is merged, I will release 2.4.1 on the same day.
