### ISSUE TITLE
Support parameterized fields resolvers

### ISSUE THREAD

**Issue by joffrey-bion** [kobylynskyi/graphql-java-codegen#25]
**Is your feature request related to a problem? Please describe.**
In the GraphQL specification, some fields may have arguments:
https://graphql.org/learn/queries/#arguments

This schema for instance:
```
type Query {
    users: [Person]!
}
type Person {
    name: String!
    height(unit: Unit): Int!
}
enum Unit {
    METERS, FEET
}
```

Currently, `graphql-java-codegen` generates a `Person` class with both `name` and `height` fields. However, the height field is parameterized and should be defined in a separate resolver (with the parameters as method arguments).

**Describe the solution you'd like**
A solution that would match the https://github.com/graphql-java-kickstart/graphql-java-tools approach would be to avoid generating the `height` field as a field/getter/setter on the `Person` type, but instead generate a `PersonResolver` interface with a method to resolve that field, as [defined by the GraphQL Java Tools project](https://www.graphql-java-kickstart.com/tools/schema-definition/#resolvers-and-data-classes).

The method should look like:
```java
import graphql.schema.DataFetchingEnvironment;

interface PersonResolver {
    public Integer height(Person person, Unit unit, DataFetchingEnvironment env);
}
```

**Describe alternatives you've considered**
Alternatively, or in the meantime, an option to exclude parameterized fields from the generated classes would be a start.

**Comment by joffrey-bion** [comment]
@kobylynskyi What are your thoughts on this?

I could maybe contribute something for this too (because I do need that 😄) but it seems to be a bit more complicated and I may have to touch a bigger part of the code.

Would you be ok with that, or would you prefer making the changes yourself?

**Comment by kobylynskyi** [comment]
@joffrey-bion thanks for the follow-up. I can take a look at it today.

**Comment by kobylynskyi** [comment]
@joffrey-bion, do you think it's worth having a boolean property in MappingConfig that will enable/disable this feature? Something like `parameterizedFieldsResolvers = true/false`.
If we go with this approach, then I would keep it enabled by default.

**Comment by joffrey-bion** [comment]
I was just mentioning this configuration param for backwards compatibility reasons, to be honest.

But now that I think of it, if some users are not using [GraphQL Java tools](https://github.com/graphql-java-kickstart/graphql-java-tools), or if they're not generating operations at all, maybe they will need this field to be part of their POJOs.
So maybe this needs to be a configurable parameter.

That being said, if we're willing to introduce a breaking change, I think it makes sense to enable it by default.

Maybe even better, we could by default use the value of `generateApis`. If that one is enabled, it makes sense to generate resolvers for parameterized fields resolvers; if `generateApis==false`, we may want to generate the whole POJOs by default, including parameterized fields, assuming the user is resolving stuff independently anyway.

**Comment by joffrey-bion** [comment]
I gave this issue some more thought and realized that we should also allow to define some of the non-parameterized fields as separately resolved.
*All* parameterized fields *have to* be resolved separately, but *some* fields could be the result of a special query even if they're not parameterized.

Now, how to decide which ones to generate or not is a whole other story.

One way would be to use custom directives, but that leaks implementation into the schema, and I'n not a great fan of that. Any other ideas?

**Comment by kobylynskyi** [comment]
Good points, @joffrey-bion.
As an addition to config `generateParameterizedFieldsResolvers` (which will generate resolvers for all parametrized fields across all types), we can define another config `fieldsResolvers` where users can define a list of fields for which we will generate resolvers.

**Example schema:**
```
type Person {
    name: String!
    height(unit: Unit): Int!
    friends: [Person!]
}
enum Unit { METERS, FEET }
```

**MappingConfig**:
* `generateParameterizedFieldsResolvers = true`
* `fieldsResolvers = ["Person.friends"]`

**So the generated classes will look like:**
```
public interface PersonResolver {
    Integer height(Person person, Unit unit, graphql.schema.DataFetchingEnvironment env);
    java.util.Collection<Person> height(Person person, graphql.schema.DataFetchingEnvironment env);
}
```
```
public class Person {
    private String name;
    public String getName() { return name; }
    public void setName(String name) { this.name = name; }
}
```

What do you think?

**Comment by kobylynskyi** [comment]
Reopening this feature request because the following parameters should be added to Maven/Gradle plugins:
- `Boolean generateParameterizedFieldsResolvers`
- `Set<String> fieldsResolvers`
