### ISSUE TITLE
Compilation error on generated classes (Version: 2.4.1)

### ISSUE THREAD

**Issue by ClaudiuGuja** [kobylynskyi/graphql-java-codegen#259]
When generating code from schema.graphqls, the response projections have a compilation error caused by `fields.put("nameOfField", null)`. The method put is not available on the ArrayList fields from GraphQLResponseProjection, but it was available on an earlier version (1.8.1) when fields was declared of type LinkedHashMap.

Proposed solutions: 
- use LinkedHashMap once more inside GraphQLResponseProjection
- make the code generation of response projections use a different method than put, one compatible with ArrayList

**Comment by kobylynskyi** [comment]
@ClaudiuGuja please make sure you update both plugin version and dependency version in your project.

**Comment by kobylynskyi** [comment]
If you use the latest version of generator, it will generate something like:
src/test/resources/expected-classes/response/LocationResponseProjection.java.txt
Which internally refers to src/main/java/com/kobylynskyi/graphql/codegen/model/graphql/GraphQLResponseProjection.java

**Comment by ClaudiuGuja** [comment]
Indeed, the issue was a mismatch between the dependency version and the plugin version. Thank you for your support.
