### ISSUE TITLE
Support descriptions in Javadoc rather than comments

### ISSUE THREAD

**Issue by mhuffman-r7** [kobylynskyi/graphql-java-codegen#267]
**Is your feature request related to a problem? Please describe.**
As a part of issue #84 support was added to take GraphQL schema comments and output them into generated types. This does not currently support descriptions.

**Describe the solution you'd like**
According to the [GraphQL Spec: §2.1.4](https://spec.graphql.org/June2018/#sec-Comments) comments are not intended for proper documentation of the API.

> Comments behave like white space and may appear after any token, or before a line terminator, and have no significance to the semantic meaning of a GraphQL Document.

The proposed change is to use descriptions instead for Javadoc documentation, as this is consistent with [GraphQL Spec: §3.3](https://spec.graphql.org/June2018/#sec-Descriptions) and the usage of introspection.

>To allow GraphQL service designers to easily publish documentation alongside the capabilities of a GraphQL service, GraphQL descriptions are defined using the Markdown syntax.

**Describe alternatives you've considered**
It is possible that a generation flag could allow customizing between whether comments or descriptions are used for the Javadoc (and to allow backwards compatibility).

**Comment by kobylynskyi** [comment]
@mhuffman-r7 Thanks for your feature request.
Version 3.0.0 was released today.
GraphQL descriptions are now considered when generating Javadoc.
Please note: If no GraphQL description is present for the given GraphQL type/field/interface/union/etc then GraphQL comment will be used.

**Comment by mhuffman-r7** [comment]
@kobylynskyi Awesome. Thanks so much for the speedy turn-around.
