### ISSUE TITLE
Union type members don't implement union interface if declared in separate file

### ISSUE THREAD

**Issue by joffrey-bion** [kobylynskyi/graphql-java-codegen#27]
**Describe the bug**
If the types that are part of a union type are declared in other files than the union itself, they don't implement the union interface in the generated code.

**To Reproduce**

`schema1.graphqls`:
```
type A {
    fieldA: String
}
```
`schema2.graphqls`:
```
type B {
    fieldB: String
}
union U = A | B
```
This will generate `class B implements U` but a `class A` that does not implement `U`.

**Expected behavior**
All members of the union type should implement the interface.

I believe this has to do with the schema files being processed independently instead of reading all schema files to populate a common registry and then generating code from the common registry.

**Comment by kobylynskyi** [comment]
@joffrey-bion I can't reproduce the issue.

schema:
`union Assignee = Bot | Mannequin | Organization | User`

Generated classes:
`public class Bot implements Assignee`
`public class Mannequin implements Assignee`
`public class Organization implements Assignee`
`public class User implements Assignee`

**Comment by joffrey-bion** [comment]
Mmmh interesting. Maybe it has to do with the order of the files, then? I don't know how that could be though.
I'll try to reproduce again.

**Comment by joffrey-bion** [comment]
I added a test case for multi-file unions and it does reproduce the problem.

Please take a look at the pull request https://github.com/kobylynskyi/graphql-java-codegen/pull/28 for the fix.

**Comment by kobylynskyi** [comment]
@joffrey-bion Thank you! Will take a look within an hour
