### ISSUE TITLE
Ability to generate only root interface with all queries/mutations/subscriptions

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#270]
## Issue Description

*Describe your bug in detail.*
option `ApiRootInterfaceStrategy ` default value is `SINGLE_INTERFACE `.  literally, only one resolver query and resolver mutation will be generated.
I tried both gradle and SBT, and the results were the same.there have generated resolver for every graphql query.
As a result, I have too many useless classes under the API package, because I only need a resolver that contains all interfaces.

## Steps to Reproduce
*List in detail the exact steps to reproduce the unexpected behavior.*

## Expected Result
when set `apiRootInterfaceStrategy := com.kobylynskyi.graphql.codegen.model.ApiRootInterfaceStrategy.SINGLE_INTERFACE`, only a query resolver java file will generate.

So, can I not generate other resolvers?
## Actual Result
*Explain in detail what behavior actually happened.*

## Your Environment and Setup

* **graphql-java-codegen**: *E.g.: 2.4.1*
* **Build tool**: *E.g.: Maven*
* **Java tool**: *E.g.: Oracle 8u241*
* **Mapping Config**: *E.g.:* 

```xml
<configuration>
    <outputDir>${project.build.directory}/generated-sources/graphql</outputDir>
    <packageName>io.github.kobylynskyi.graphql.model</packageName>
</configuration>
```

**Comment by kobylynskyi** [comment]
@jxnu-liguobin it's not a but.
Property `apiRootInterfaceStrategy` is about generating a **root** interface only.

**Comment by jxnu-liguobin** [comment]
> @jxnu-liguobin it's not a but.
> Property `apiRootInterfaceStrategy` is about generating a **root** interface only.
> If you want not to generate a other api interfaces, then there should be a separate property (e.g.: `apiInterfaceStrategy`)

thanks

**Comment by kobylynskyi** [comment]
I will introduce a new config `apiInterfaceStrategy` which will accept two values:
* `INTERFACE_PER_OPERATION` **(default)** - Generate separate interface classes for each GraphQL operation.
* `DO_NOT_GENERATE` - Do not generate separate interfaces classes for GraphQL operation.

Plus, I will add another enum option to `apiRootInterfaceStrategy`:
* `DO_NOT_GENERATE` - Do not generate super interface for GraphQL operations.

**Comment by kobylynskyi** [comment]
@jxnu-liguobin I've created a separate issue to track sbt-plugin changes: #276

**Comment by kobylynskyi** [comment]
Version 3.0.0 was released today.
