### ISSUE TITLE
Update sbt-plugin implementation with new config options

### ISSUE THREAD

**Issue by kobylynskyi** [kobylynskyi/graphql-java-codegen#276]
* #275
  * Add `apiInterfaceStrategy` (default = `MappingConfigConstants.DEFAULT_API_INTERFACE_STRATEGY`)
* #274 
  * Remove `generateAsyncApi`
  * Rename `apiAsyncReturnType -> apiReturnType`
  * Rename `apiAsyncReturnListType -> apiReturnListType`
  * Add `useOptionalForNullableReturnTypes` (default = `MappingConfigConstants.DEFAULT_USE_OPTIONAL_FOR_NULLABLE_RETURN_TYPES`)
* #273 
  * Change type of  `customAnnotationsMapping`: `Map<String, String> -> Map<String, List<String>>`
  * Change type of  `directiveAnnotationsMapping`: `Map<String, String> -> Map<String, List<String>>`

**Comment by kobylynskyi** [comment]
@jxnu-liguobin could you please work on this?

**Comment by jxnu-liguobin** [comment]
ok,

**Comment by jxnu-liguobin** [comment]
> @jxnu-liguobin could you please work on this?

but i find some have updated in #274 ,So I'm going to wait until you merge into the master.

**Comment by kobylynskyi** [comment]
@jxnu-liguobin all my changes for 3.0.0 were merged to master. Please proceed with your changes and feel free to close this issue when you are done.

**Comment by kobylynskyi** [comment]
@jxnu-liguobin you are done with the changes? Once you confirm, I will release 3.0.0

**Comment by jxnu-liguobin** [comment]
> @jxnu-liguobin you are done with the changes? Once you confirm, I will release 3.0.0

yes, ready
