### ISSUE TITLE
If there are many generated classes, it is not convenient to find a matching class for constructing GraphQLRequest

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#289]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**
Hi, I'm here again. This is a small demand.

we provide source code(code generated by graphql-java-codegen) in the form of SDK, it is not convenient to find all models and interfaces in one package.So. if the model and api are stored separately according to some policies, look for `request`,`response`,`projection`,`dto` are easy. i have stored schemas in graphql folder like this :
![image](https://user-images.githubusercontent.com/29496873/90228337-a1b18a00-de48-11ea-81a8-3748c67b50e8.png)
i want to create package like follow:
```
xx.xxx.xxx.model.jobs
xx.xxx.xxx.api.jobs
```
Whenever I need to call the SDK api of jobs, I just need to look at the classes under the` jobs package` to splice the requests.
The policy can be based on the name(or prefix) of the schema or the direct parent directory.

**Describe alternatives you've considered**

**Additional context**

**Comment by kobylynskyi** [comment]
jxnu-liguobin will apiPackageName/modelPackageName solve your issue?

**Comment by jxnu-liguobin** [comment]
> @jxnu-liguobin could you please explain a bit more - what classes you want to have in separate packages?
`request、projection and entity` 
someone can use them by proxy to invoke server automatically. like follow:
```scala
ResolverImplClient.ResolverImplClientBuilder.newBuilder().
setProjection(new FileDescriptorResponseProjection).
setRequest(new JobFilesQueryRequest).build(classOf[JobFilesQueryResolver]).jobFiles(id)
```
so, someone who use proxy, maybe need found classes where classes are stored.
Of course, it's just more convenient.

**Comment by jxnu-liguobin** [comment]
> @jxnu-liguobin for client-side codegen there are:
> 
> * Request
> * Response
> * ResponseProjection
> * Entity
> 
> Which of the classes do you want to be generated separately?
> And can you please explain what's the problem having all of the classes in one package?

**while we publish the generated code publicly for customer use.**
It's going to be close to a thousand class files in the near future, users find class hard.
so we need separate them.

Specifies to separate by folder, not by class type.I think the best way is this.
like follow:  packageA and packageB come from graphql' Resolver prefixName.
package A
```
    RequestA
    ResponseProjectionA
    EntityA
```
```
package B
    RequestB
    ResponseProjectionB
    EntityB
```

**Comment by kobylynskyi** [comment]
It becomes very hard to manage imports because of cross-entity relationships

**Comment by jxnu-liguobin** [comment]
yeah,It's ok. Indeed, this is also a worrying problem. I observed that our protocolbuffer only request(resolver) and dto(model) ware separated.
But Pb can use 
```
package io.growing.events;
option java_package = "io.growing.events.protobuf";
```
to define a package. I wonder if graphql schema can handle it in a similar way, such as defining a special identifier: 
`#package io.growing.events BEGIN#`
`#package io.growing.events END#`  option, if not have, all in one package

Of course, I'm just talking about the possibility. At present, this is not a feature with strong requirements.

**Comment by kobylynskyi** [comment]
It is possible to generate APIs and models in separate packages.
A more granular approach can be done by creating separate `.graphql` schema files and creating separate configurations with its won `packageName`. For example in gradle:
```groovy
task graphqlCodegenService1(type: GraphqlCodegenGradleTask) {
    graphqlSchemas.includePattern = "schema1\\.graphqls"
    outputDir = new File("$buildDir/generated/example1")
    packageName = "com.example1"
}

task graphqlCodegenService2(type: GraphqlCodegenGradleTask) {
    graphqlSchemas.includePattern = "schema2\\.graphqls"
    outputDir = new File("$buildDir/generated/example2")
    packageName = "com.example2"
}
```

Hope that helps
