### ISSUE TITLE
Generate model and interfaces into src directory

### ISSUE THREAD

**Issue by hexwit** [kobylynskyi/graphql-java-codegen#293]
Hi

I wonder is it possible to generate model and api interfaces directly into one of src directories? 
I tried to specify outputDir with package names, but it generates sub-tree of specified packages. 

I am using Spring 5 (not boot) and it is not clear for me why model/api should be generated to the target directory instead of src. In current case IDE does not provide help by default. I have to add generated sources from target directory. A bit strange for me. 

Could you clarify the idea, and how to solve my problem?

**Comment by kobylynskyi** [comment]
@hexwit try using configs:
outputDir - output directory of the codegen. Could be anything (target/build/src/etc)
packageName - package name for both model and api classes unless other is specified in apiPackageName / modelPackageName

Does it solve your problem?

**Comment by kobylynskyi** [comment]
@hexwit I've just tried the following gradle config and it successfull generate **both api and model** classes in **src** directory:
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/2664706/90457009-fd397d00-e0bf-11ea-9b14-433e550c2f24.png">

**Comment by jxnu-liguobin** [comment]
it maybe need to generate the code into the managed classpath instead of the `build folder` like option `generateCodegenTargetPath` in sbt .

**Comment by kobylynskyi** [comment]
@hexwit any luck generating the code based on my suggestion above?
