### ISSUE TITLE
[3.0.0] (No code was generated for the query/mutation type named `Subscription`)

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#294]
## Issue Description

*Describe your bug in detail.*

Not Subscription!! , The Subscription is a mode name in our system.!!, So, It's query/mutation resolver
I use plugin generate code, there are two code blocks:
```graphql
#will success
directive @subscriptions on FIELD_DEFINITION

enum SubscriptionType {
    DASHBOARD
}

type Subscription1 {# if i rename it as Subscription1, then will generate successfully
    id: String,
    name: String,
    status: String,
    children: [Subscription1!] @subscriptions
}

input SubscriptionInput {
    id: String,
    name: String,
    children: [SubscriptionInput]
}


#will failed
directive @subscriptions on FIELD_DEFINITION

enum SubscriptionType {
    DASHBOARD
}

type Subscription { #no model code is generated at all
    id: String,
    name: String,
    status: String,
    children: [Subscription!] @subscriptions
}

input SubscriptionInput {
    id: String,
    name: String,
    children: [SubscriptionInput]
}
```

## Steps to Reproduce
*List in detail the exact steps to reproduce the unexpected behavior.*

## Expected Result
*Explain in detail what behavior you expected to happen.*

## Actual Result
*Explain in detail what behavior actually happened.*

## Your Environment and Setup

* **graphql-java-codegen**: *E.g.: 3.0.0*
* **Build tool**: *E.g.: Maven*
* **Java tool**: *E.g.: Oracle 8u241*
* **Mapping Config**: *E.g.:* 

```xml
<configuration>
    <outputDir>${project.build.directory}/generated-sources/graphql</outputDir>
    <packageName>io.github.kobylynskyi.graphql.model</packageName>
</configuration>
```

**Comment by kobylynskyi** [comment]
@jxnu-liguobin Please set **generateModelsForRootTypes** to true and try again.

**Comment by jxnu-liguobin** [comment]
> @jxnu-liguobin Please set **generateModelsForRootTypes** to true and try again.


I tried to add it `generateModelsForRootTypes:=true` , but also generate error... while execute graphqlCodegen task.
when i remove it `generateModelsForRootTypes:=true`, task will success.
maybe need debug, I'm going to see it again when I'm free.

**Comment by kobylynskyi** [comment]
Please share the error which you are getting when generating using `generateModelsForRootTypes:=true`
Thanks!

**Comment by jxnu-liguobin** [comment]
> Please share the error which you are getting when generating using `generateModelsForRootTypes:=true`

msg: Either disable APIs generation or set different Prefix/Suffix for API classes and type resolver classes.

failed at https://github.com/kobylynskyi/graphql-java-codegen/blob/2faea7c3d293e0a530cedcb9647ecfe4cc2df770/src/main/java/com/kobylynskyi/graphql/codegen/GraphQLCodegen.java#L173 

I added `typeResolverPrefix := Some("GrowingIO")` to solve this problem

and i found need add option `apiRootInterfaceStrategy:= com.kobylynskyi.graphql.codegen.model.ApiRootInterfaceStrategy.DO_NOT_GENERATE`,
Otherwise, a `GrowingQueryresolver` and `QueryResolver` are generated,these two are repeated.

**Comment by kobylynskyi** [comment]
@jxnu-liguobin correct, typeResolverPrefix needs to be changed from Resolver to something else in case `generateModelsForRootTypes=true`.
