### ISSUE TITLE
Allow a directory of schemas to be passed in

### ISSUE THREAD

**Issue by joffrey-bion** [kobylynskyi/graphql-java-codegen#30]
**Is your feature request related to a problem? Please describe.**
When we want to break the schema down into many parts (for scalability), it's very inconvenient to have to maintain a list of schemas to process (either in the code or in a gradle/maven plugin).

**Describe the solution you'd like**
It would be nice to be able to specify a directory so that `graphql-java-codegen` processes all the schema files inside.

A couple of useful related options to consider:
- `recursive`: whether directories should be explored recursively to find schemas
- `schemaFilePattern`: a pattern ([Java style](https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html)) to match the schema files to process (would most likely default to `.*\.graphqls`)
- `excludeFiles`: a list of schema files to exclude

**Describe alternatives you've considered**
The alternatives so far are:
- to list all files manually (most likely in the maven plugin)
- to write custom code (maybe as another plugin/task) to build the list of files

**Comment by kobylynskyi** [comment]
This would be a very useful feature to have!
I hope that I will have time for this one late this week or early-next week (as you know right now I am working on #25 which is quite big :smile:)

**Comment by joffrey-bion** [comment]
Maybe I can contribute this one if you're ok, it should be fairly simple.

**Comment by kobylynskyi** [comment]
@joffrey-bion sure, I would appreciate it if you can work on this feature.
From the implementation POV, I like your option to remove schemas from the constructor and pass them as a parameter to generate() method. We are free to change that because as of now there are only 2 usages of this class (gradle and maven plugins)

**Comment by kobylynskyi** [comment]
@joffrey-bion 
I would like to reopen this feature request in order to track the changes which need to be made in gradle and maven plugins.

**Comment by joffrey-bion** [comment]
Thanks for reopening, let's keep track of the gradle plugin updates here.
