### ISSUE TITLE
Can a constructor be provided to support direct new Graphqloperationrequest

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#303]
**Is your feature request related to a problem? Please describe.**
use  graphql-java-codegen as client:
```scala
val tag = graphQLClient.setProjection(new TagResponseProjection().all$(1)).setRequest(new TagQueryRequest).build(classOf[TagQueryResolver]).tag(tagId)
```
I will invoke TagQueryRequest's `setMethod` at inside:
```scala
  def withParamsByReflect(method: Method, args: Array[AnyRef]): GraphQLOperationRequest = {
    val parameters = method.getParameters.toSeq//at now, method is tag, parameters is Array[id: String]
    if (parameters.nonEmpty) {
      parameters.zip(args).zipWithIndex.foreach {
        case (parameterAndArgsValue, index) =>
         //will add parameter and value
        //In this case, I don't need to think about the order of the parameters, because I can read the parameter's name list of the 
       //method directly
          graphQLOperationRequest.getInput.put(parameterAndArgsValue._1.getName, args(index))
      }
    }
    graphQLOperationRequest
  }
```
but parameter's name list depends on javac option`-parameters`, it only be supported and add while java 1.8+.
if in java 7,I wanted to call the `setMethod` in turn, but I found that the method list returned by reflection is different from the defined property in GraphQLOperationRequest's sub class, so there is no way to call the `setMethod` in turn. 

At the same time, frameworks such as ASM do not seem to support getting parameter names of methods on interfaces

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kobylynskyi** [comment]
@jxnu-liguobin sorry, I don't understand the request.
Can you please provide java sample?

**Comment by jxnu-liguobin** [comment]
> @jxnu-liguobin sorry, I don't understand the request.
> Can you please provide java sample?

In short, I want to put the parameters（resolver' method） into the input field of `GraphQLOperationRequest` so that I can directly instantiate `GraphQLOperationRequest's sub class` without calling the `setXX`.

normal
```java
GraphQLOperationRequest request = new GraphQLOperationRequest();
request.setId("").setName("11");
GraphQLResponseProjection projection = new GraphQLResponseProjection()
GraphQLRequest graphQLRequest = new GraphQLRequest(request, projection.all$)
```
use proxy
```java
ResolverImplClient.ResolverImplClientBuilder humanInvokerBuilder = ResolverImplClient.ResolverImplClientBuilder.newBuilder().
setProjection(new HumanResponseProjection().all$).
setRequest(new HumanQueryRequest()).
build(HumanQueryResolver.class).
human("1001");
```
`1001` should put into `HumanQueryRequest` automatically, so users can  invoke it like a local method.
At present, I have passed the getInput.put to manually add, but only for Java 8+.

example:
```java
public void setId(String id) {
        this.input.put("id", id);
    }
...........
getInput.put(setIdMethod.parameter.getName,  "1001")
```

```java
ResolverImplClient.ResolverImplClientBuilder humanInvokerBuilder = ResolverImplClient.ResolverImplClientBuilder.newBuilder().
setProjection(new HumanResponseProjection().all$).
setRequest(HumanQueryRequest.class).
build(HumanQueryResolver.class).
human("1001");
```
if it can create `HumanQueryRequest` instance with `1001` in ResolverImplClient,then, it doesnot need `getInput.put(setIdMethod.parameter.getName,  "1001")` and doesnot need java8+.

Another way is to add annotations to record parameter names, such as spring and mybatis.

However, all assumptions are based on resolver with the same method parameters as `setXX`, regardless of aliases.
resolver
```java
SlicePaginationDto activeUsers(@Params("timeRange")String timeRange) throws Exception;
//It may cause code redundancy, but we consider using this method after internal review
```
request
```java
public void setTimeRange(String timeRange) {
    this.input.put("timeRange", timeRange); 
}
```
`request.getInput.putAll(getParametersNames zip parameterValues)`
or instance request `new GraphQLOperationRequestSubClass("111")`
or `request.getConstructor(parameterTypes).newInstance("parameterValues")`

**Comment by kobylynskyi** [comment]
@jxnu-liguobin thanks for the detailed explanation. But I think this will overengineer the library.
So this could be done by the client (probably some other plugin?)

**Comment by jxnu-liguobin** [comment]
Yes, I also don't think this library should do this kind of thing. I will consider trying to use ASM to try again. At present, this is not the biggest problem. The problem is all$ we really need. Please evaluate it

**Comment by kobylynskyi** [comment]
Ok, then we can close this one. Thanks anyway for reporting this.
Regarding `all$` - I am still thinking whether this is a way to go. Joffrey had very valid points on why this should not be in place.

**Comment by jxnu-liguobin** [comment]
ok,thanks.

**Comment by jxnu-liguobin** [comment]
> Ok, then we can close this one. Thanks anyway for reporting this.
> Regarding `all$` - I am still thinking whether this is a way to go. Joffrey had very valid points on why this should not be in place.

Hi，i found  ftl template's `fields` was a `LinkedHashMap`, so i will use `builder`'s fields instead of using resolver' method parameter names

**Comment by jxnu-liguobin** [comment]
@kobylynskyi I'm sorry to trouble you, could i add a field in request builder? 

In order to ensure that the order of fields is the same as the order of operations in the schema, I tried many methods and verified them.I even want to use the order of field in builder as the order of parameter of the resolver method.

But result is: In builder class, the compiler and the JVM cannot ensure that they are the same as the defined order and will not store parameter name(exclude java8+ ) in resolver class.
So It seems that there is no other way to save information into bytecode except adding new tags.
1. Use the annotation to specify the order of each field and use compare after getFields
2. Use annotations to record the parameters of resolver's method
3. Create a field to store the order of fields.  I think this way is probably the least expensive and can ensure that the order of fields is reliable, because it is LinkedList when rendering templates.


this is a example after add a field.
```java
 public static class Builder {

 	private List<String> fieldsInOrder = Arrays.asList("timeRange", "offset", "limit")

        private String timeRange;
        private Integer offset;
        private Integer limit;

        public Builder() {
        }

        public Builder setTimeRange(String timeRange) {
            this.timeRange = timeRange;
            return this;
        }

        public Builder setOffset(Integer offset) {
            this.offset = offset;
            return this;
        }

        public Builder setLimit(Integer limit) {
            this.limit = limit;
            return this;
        }


        public ActiveUsersQueryRequest build() {
            ActiveUsersQueryRequest obj = new ActiveUsersQueryRequest();
            obj.setTimeRange(timeRange);
            obj.setOffset(offset);
            obj.setLimit(limit);
            return obj;
        }

    }
```
will add in javaClassGraphqlRequest.ftl
```
<#if fields?has_content>
    <#list fields as field>
        private List<String> fieldsInOrder = Arrays.asList(<#list fields as field>"${field.originalName}"<#if field_has_next>, </#if></#list>);
    </#list>
</#if>
```
