### ISSUE TITLE
Generate primitive types for non-null GraphQL types

### ISSUE THREAD

**Issue by joffrey-bion** [kobylynskyi/graphql-java-codegen#305]
**Is your feature request related to a problem? Please describe.**
Using wrapper classes for primitive types incurs a performance cost.
Wrappers are useful to indicate when a value can be null, but if it is declared as non-null (`!`), we have no reason to use the wrapper type (it's even confusing for readers).

**Describe the solution you'd like**
Non-null primitive GraphQL types should be mapped to non-wrapped primitive Java types.

Note: For backwards compatibility, we could add a config flag to generate boxed types all the time, but I believe Java's autoboxing/unboxing should actually make this change backwards compatible without the need for a config flag.

**Describe alternatives you've considered**
Currently, there is no way to customize the generation, AFAICT.
The `customTypesMapping` argument cannot be used with a `!` (at least in Maven).

**Additional context**

**Comment by kobylynskyi** [comment]
@joffrey-bion good idea. 
Just to confirm, we are talking about:
* GraphQL `Int`
   * Non-null -> Java `int`
   * Nullable -> Java `Integer`
* GraphQL `Float`
   * Non-null -> Java `double`
   * Nullable -> Java `Double`
* GraphQL `Boolean`
   * Non-null -> Java `boolean`
   * Nullable -> Java `Boolean`

**Comment by joffrey-bion** [comment]
@kobylynskyi yes exactly 👍

**Comment by kobylynskyi** [comment]
@joffrey-bion actually I just found out that it is a breaking change.
Suppose you have a graphql schema 
```graphqls
type Query {
    feeds(amount: Int!): [Feed!]
}
```
and corresponding resolver:
```java
public class FeedsQueryResolverImpl implements FeedsQueryResolver {
    @Override
    public List<Feed> feeds(Integer amount) { return null; }
}
```

Now (after my recent changes) `FeedsQueryResolver` will be generated with primitive parameter:
```java
public interface FeedsQueryResolver {
    List<Feed> feeds(int amount);
}
```
and `FeedsQueryResolverImpl` will not compile anymore.

So I might bump the next release version to 4.0.0 (instead of 3.2.0)

**Comment by joffrey-bion** [comment]
Makes sense, it is indeed a breaking change
