### ISSUE TITLE
maven: Support parallel builds

### ISSUE THREAD

**Issue by lorenzleutgeb** [kobylynskyi/graphql-java-codegen#325]
Running `mvn` with [`--threads 1C`](https://maven.apache.org/ref/3.6.3/maven-embedder/cli.html) (i.e. one thread per core) produces the following warning:

```
[WARNING] *****************************************************************
[WARNING] * Your build is requesting parallel execution, but project      *
[WARNING] * contains the following plugin(s) that have goals not marked   *
[WARNING] * as @threadSafe to support parallel building.                  *
[WARNING] * While this /may/ work fine, please look for plugin updates    *
[WARNING] * and/or request plugins be made thread-safe.                   *
[WARNING] * If reporting an issue, report it against the plugin in        *
[WARNING] * question, not against maven-core                              *
[WARNING] *****************************************************************
[WARNING] The following plugins are not marked @threadSafe in [REDACTED]
[WARNING] io.github.kobylynskyi:graphql-codegen-maven-plugin:2.0.0
[WARNING] Enable debug to see more precisely which goals are not marked @threadSafe.
```

Let's get rid of that and enable smooth parallel builds, shall we? I'm happy to take any pointers towards an implementation, but am not sure yet whether I can PR, depending on the complexity of the change.

**Comment by lorenzleutgeb** [comment]
I took a quick look at the implementation of the plugin, and it seems to me that all its operations are "local" to the specific Maven module being built. There might be some inputs that are outside the module (i.e. schema file placed somewhere strange) but there's no output/writes outside of the module. Given this, I think that actually the plugin is thread safe, and it's just a matter of setting the flag.

@kobylynskyi could you please think this through? I.e. what might happen if I have two Maven modules, both using the plugin, living next to each other, being built at the same time? Will this cause trouble? Note that if module A depends on module B, they will of course not be built in parallel, Maven will first build B and then A, so this is no cause for problems.

**Comment by jxnu-liguobin** [comment]
Indeed, I have encountered this problem before,. The plug-in itself needs to support the concurrent execution of multiple projects and modules. The SBT plugin uses `scope` to solve this problem

**Comment by kobylynskyi** [comment]
@lorenzleutgeb thanks for your ticket.
I don't think that right now the plugin is thread-safe because it deletes the output directory prior to code generation. Basically it means that there could be some missing files if module1 and module2 in parallel are asking graphql-java-codegen to generate classes into the same directory.
So the solution to thread-safety could be to remove output directory deletion:
https://github.com/kobylynskyi/graphql-java-codegen/blob/03e6b5cc12a5a729676222f49dae21d7ecbe5c9a/src/main/java/com/kobylynskyi/graphql/codegen/GraphQLCodegenFileCreator.java#L40-L43
But I am not sure whether some clients will expect graphql-java-codegen to delete the content of the output dir prior to generation.

**Comment by jxnu-liguobin** [comment]
> I don't think that right now the plugin is thread-safe because it deletes the output directory prior to code generation. Basically it means that there could be some missing files if module1 and module2 in parallel are asking graphql-java-codegen to generate classes into the same directory.
> So the solution to thread-safety could be to remove output directory deletion:

 May be should provide an environment for `graphqlCodegen ` to execute for each sub module ?

**Comment by kobylynskyi** [comment]
@lorenzleutgeb I've decided to mark a plugin as threadSafe.
The [check-list from maven](https://cwiki.apache.org/confluence/display/MAVEN/Parallel+builds+in+Maven+3#ParallelbuildsinMaven3-Mojothreadsafetyassertionchecklist) passed and I don't see any issues besides "same output directory using by multiple modules" (which is the very unlikely situation and in that case, the user should disable parallel builds).
Will release the change in version 3.2.0 this week.

**Comment by lorenzleutgeb** [comment]
Great, thanks!
