### ISSUE TITLE
Gather plugins and core library in same repo?

### ISSUE THREAD

**Issue by joffrey-bion** [kobylynskyi/graphql-java-codegen#33]
Having different projects/artifacts for the Maven/Gradle plugins and the core library makes total sense. However, they don't need to be in separate GitHub repositories.

Cross-project changes and releases would be easier if they were in the same git repo:
- we could make changes to both the plugins and the library in the same commit, always keeping compatibility
- we wouldn't need to wait for the library release to make changes to the Maven/Gradle plugins
- we could test the plugins against library changes in the CI of the whole multi-project build

What are your thoughts on this?

**Comment by kobylynskyi** [comment]
Hey @joffrey-bion 
I will consider your suggestion.
Thank you!
