### ISSUE TITLE
[Broken link in documentation] (Version: [graphql-java-codegen version])

### ISSUE THREAD

**Issue by logicatmidod** [kobylynskyi/graphql-java-codegen#338]
## Issue Description

If you click below hyperlink on the page : https://github.com/kobylynskyi/graphql-java-codegen/tree/master/plugins/maven#graphql-client-code-generation

Building GraphQL request and parsing response using Spring RestTemplate

However correct file is present : https://github.com/kobylynskyi/graphql-java-codegen/blob/master/plugins/maven/example-client/src/main/java/io/github/kobylynskyi/order/external/product/ProductServiceGraphQLClient.java

The resultant page gives 404 not found

**Comment by kobylynskyi** [comment]
@logicatmidod thanks for reporting the issue. It is fixed now.
