### ISSUE TITLE
Ability to skip "throws Exception" in api method signature

### ISSUE THREAD

**Issue by piotrkav** [kobylynskyi/graphql-java-codegen#339]
Hi, 

is it possible to define own templates? 
```java

 operationsTemplate = configuration.getTemplate("templates/javaClassGraphqlOperations.ftl");
```

I would like to skip adding 

```java
throws Exception;
```

for generating interfaces.

**Comment by kobylynskyi** [comment]
Hi @piotrkav 
At the moment it is not possible

**Comment by piotrkav** [comment]
Thanks for quick response.
Will you consider this as feature in a future or should i close the issue?

**Comment by kobylynskyi** [comment]
I think it is better to do it via plugin configuration. I will consider creating another config - something like `generateApisWIthThrowsException` (exact config name to be defined)

**Comment by piotrkav** [comment]
Do you have any timeline for this feature in nearest future?

**Comment by piotrkav** [comment]
Do you have any timeline for this feature in nearest future?
