### ISSUE TITLE
[3.1.0] On the optimization of package name

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#369]
## Issue Description

If the resolver package is set but the model package is not set, then, the model cannot be referenced in any case due to the Java import mechanism. Because at present, all of our package name settings are optional.
![image](https://user-images.githubusercontent.com/29496873/96839138-571d4100-147b-11eb-9215-e6f9542a72ce.png)

![image](https://user-images.githubusercontent.com/29496873/96838965-250bdf00-147b-11eb-9017-3b0577786cd3.png)

It is recommended that when the package name is not set for resolver and model, at least the top-level package, such as package name, should be set.

## Steps to Reproduce
*List in detail the exact steps to reproduce the unexpected behavior.*

## Expected Result
*Explain in detail what behavior you expected to happen.*

## Actual Result
*Explain in detail what behavior actually happened.*

## Your Environment and Setup

* **graphql-java-codegen**: *E.g.: 3.1.1*
* **Build tool**: *E.g.: Maven*
* **Java tool**: *E.g.: Oracle 8u241*
* **Mapping Config**: *E.g.:* 

```
//modelPackageName := Some("io.github.dreamylost.model")
apiPackageName := Some("io.github.dreamylost.api")
```

**Comment by kobylynskyi** [comment]
@jxnu-liguobin there are 3 properties related to the package name:
* `packageName` - should be used when you want to have all classes (apis and models) in one package
* `apiPackageName` - should be used in conjunction with `modelPackageName` when you want to have apis in one package and models in another package.
* `modelPackageName` - should be used in conjunction with `apiPackageName` when you want to have apis in one package and models in another package.

Based on your configuration, you have `apiPackageName` set to some value, but `modelPackageName` is left empty.
If you expect models to be present in the same package as APIs, then please use `packageName` config instead.
Hope that helps.

**Comment by jxnu-liguobin** [comment]
thanks, api and model should be used at the same time
