### ISSUE TITLE
Source being generated with @javax.annotation.processing.Generated

### ISSUE THREAD

**Issue by mcarlospc** [kobylynskyi/graphql-java-codegen#377]
The project is generating the files with no issue but when I try to execute it I got an error because the generated source files have this in their header:

/**
 * _DEPRECATED_ use Interval or PositionSetInterval instead
 */
@javax.annotation.processing.Generated(
    value = "com.kobylynskyi.graphql.codegen.GraphQLCodegen",
    date = "2020-10-29T16:09:48-0700"
)

I think the generated should have @javax.annotation.Generated for java 1.8 instead?

My config:

            <plugin>
                <groupId>io.github.kobylynskyi</groupId>
                <artifactId>graphql-codegen-maven-plugin</artifactId>
                
                <version>3.1.1</version>
                <executions>
                    <execution>
                        <id>generate-sources-product-client</id>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <graphqlSchemas>
                                <includePattern>schema\.graphqls</includePattern>
                            </graphqlSchemas>
                            <outputDir>${project.build.directory}/generated-sources/client</outputDir>
                            <modelPackageName>com.ompnt.graphql.model</modelPackageName>
                            <customTypesMapping>
                                <DateTime>java.util.Date</DateTime>
                            </customTypesMapping>
                            <generateApis>false</generateApis>
                            <generateClient>true</generateClient>
                            <generateBuilder>true</generateBuilder>
                            <generateToString>true</generateToString>
                            <generateParameterizedFieldsResolvers>false</generateParameterizedFieldsResolvers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            

<plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.8.1</version>
                <configuration>
                    <encoding>UTF-8</encoding>
                    <source>1.8</source>
                    <target>1.8</target>
                    <showDeprecation>true</showDeprecation>
                    <annotationProcessorPaths>
                        <annotationProcessorPath>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                            <version>1.18.12</version>
                        </annotationProcessorPath>
                        <annotationProcessorPath>
                            <groupId>org.mapstruct</groupId>
                            <artifactId>mapstruct-processor</artifactId>
                            <version>1.4.1.Final</version>
                        </annotationProcessorPath>
                    </annotationProcessorPaths>
                </configuration>
            </plugin>

**Comment by kobylynskyi** [comment]
@mcarlospc actually for java8 you should see `@javax.annotation.Generated`.
Are you sure you are on java8?
The logic of the generator is pretty simple:
https://github.com/kobylynskyi/graphql-java-codegen/blob/c25a8aee5d3b4d41f51f9412c6c25a17e3445378/src/main/java/com/kobylynskyi/graphql/codegen/model/GeneratedInformation.java#L35-L45

**Comment by mcarlospc** [comment]
@kobylynskyi , thanks for your reply, it was actually a misconfiguration on my end, intellij IDEA was configured to use java11 runtime instead of java8!

closing this, thanks!
