### ISSUE TITLE
Custom alias for property fields

### ISSUE THREAD

**Issue by jyjyj** [kobylynskyi/graphql-java-codegen#390]
Hi, afaik I see custom annotations for deserialisers, but from my understanding that applies for an entire class. Is there a way to customise individual property fields a la Jackson's Json Alias without writing additional schema?

I hope I'm quoting Json Alias correctly, but basically I have a JSONObjects with a field `xxx_yyy` that I want to have in my schema as `xxxYyy`.

Alternatively, if there's a way to specify naming convention, that would be much appreciated (and much easier, I have quite a few fields that I want to convert from underscores to camelCase). An example would be to remove underscores and convert to camelCase like [here](https://graphql-code-generator.com/docs/plugins/typescript-operations).

For advice please, thanks!

**Comment by erikbjork** [comment]
Yes, you should be able to do that.

Using gradle:
```
customAnnotationsMapping = [
            "ModelClass.propertyName": [
                    "@what.ever.annotation.you.Like"
            ]
    ]
```

**Comment by kobylynskyi** [comment]
@jyjyj, @erikbjork is right. You can do it via `customAnnotationsMapping`
You can specify: 
* class-level annotations
```groovy
customAnnotationsMapping = [
    "ClassName": ["@your.Annotation"]
]
```
* field-level annotations using `ClassName.fieldName`:
```groovy
customAnnotationsMapping = [
    "ClassName.fieldName": ["@your.Annotation"]
]
```
* field-level annotations using field type. All fields with such type (across all graphql inputs/types) will have such annotation:
```groovy
customAnnotationsMapping = [
    "GraphQLTypeName": ["@your.Annotation"]
    // e.g.: "DateTime": ["@com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = your.DateTimeScalarDeserializer.class)"]
]
```

Hope that helps.

**Comment by jyjyj** [comment]
Thanks @erikbjork and @kobylynskyi! That works using JsonAlias for individual fields if anyone else is wondering (`@com.fasterxml.jackson.annotation.JsonAlias`).

Just wondering, would it be possible to have a naming convention as well? Like I mentioned in my OP, I generally will have a bunch of underscores with lowercases that I would like to convert to camelCase e.g. `camel_case` to `camelCase`.

Thanks!
