### ISSUE TITLE
Ability to generate only model

### ISSUE THREAD

**Issue by kobylynskyi** [kobylynskyi/graphql-java-codegen#4]
**Is your feature request related to a problem? Please describe.**
Sometimes developers need to generate only model classes (types/enums/inputs/etc.)

**Describe the solution you'd like**
Extend MappingConfig with 2 new attributes:
- *generateApis* - **true** by default
- *generateModels* - **true** by default

**Comment by PavelSusloparov** [comment]
That's totally my use case.

**Comment by kobylynskyi** [comment]
Done in 1.2
