### ISSUE TITLE
Introduce a code-formatter plugin for repository code

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#403]
**Is your feature request related to a problem? Please describe.**

https://github.com/google/google-java-format

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by kobylynskyi** [comment]
@jxnu-liguobin , I don't think that we need to include it as part of your codegen.
That should be up to the client to use it or not.
What do you think?

**Comment by jxnu-liguobin** [comment]
It may not be described clearly. I mean that we need to unify the code style of the library, not the generated code.

**Comment by kobylynskyi** [comment]
Indeed, the following plugin can be used:
https://github.com/diffplug/spotless/tree/main/plugin-gradle#java

**Comment by jxnu-liguobin** [comment]
Yes, it's better
