### ISSUE TITLE
Refactor library for multi-language support

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#407]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

When I implemented Scala, I found that the existing code is not very convenient to implement multi language, resulting in a lot of judgment logic all over the mapper. Shall we consider refactoring it? (different implementations for different languages, instead of using `if else` in only one mapper). 

**Describe alternatives you've considered**

**Additional context**

**Comment by kobylynskyi** [comment]
@jxnu-liguobin, do you plan to introduce more changes in 4.0.1, or I can release it?

**Comment by jxnu-liguobin** [comment]
> @jxnu-liguobin, do you plan to introduce more changes in 4.0.1, or I can release it?

At present,there are no urgent problems to be solved. I think it can be released. Next time, kotlin should be at least 4.1.0 or 5.0.0.
