### ISSUE TITLE
Contributing guidelines incorrect for gradle plugin

### ISSUE THREAD

**Issue by joffrey-bion** [kobylynskyi/graphql-java-codegen#41]
> cd plugins/graphql-java-codegen-gradle-plugin/graphql-codegen-gradle-plugin
> ./gradlew clean install

These instructions are unfortunately not possible to follow.
1. The gradle wrapper is not present in this subfolder (which is ok, but we need to change the command to simply `gradle` and assume the correct version is installed globally on the machine).
2. There is no install task on the plugin project:

```
Task 'install' not found in project ':graphql-codegen-gradle-plugin'.
```
I guess it should be changed to the `publishToMavenLocal` task instead.

Last thing, the example project can't be built because it is commented out in `settings.gradle`.
However, the plugin's project can't be built the first time if the other one is uncommented, because the dependency is not declared in the build.

Maybe we can improve the projects setup so that the global build tests everything (including example projects) without having to follow a specific order and without changing directories.

**Comment by kobylynskyi** [comment]
I think the issue is with the gradle wrapper version.
`install` task is present in the gradle wrapper of the parent project:
https://github.com/kobylynskyi/graphql-java-codegen/blob/master/gradle/wrapper/gradle-wrapper.properties

wrapper inside gradle-plugin module is outdated.

Will fix it today

**Comment by joffrey-bion** [comment]
I just updated the issue text. I could get it to work using `publishToMavenLocal`.
It's strange that the wrapper adds tasks 😮 never heard of that!

**Comment by kobylynskyi** [comment]
> the example project can't be built because it is commented out in settings.gradle. However, the plugin's project can't be built the first time if the other one is uncommented, because the dependency is not declared in the build.

Yeah. Good point. That's why I commented it out by default.

> Maybe we can improve the projects setup so that the global build tests everything (including example projects) without having to follow a specific order and without changing directories.

Absolutely! Will create an issue to track it.
