### ISSUE TITLE
Null input causes wrong query generation (Version: 4.0.0)

### ISSUE THREAD

**Issue by ClaudiuGuja** [kobylynskyi/graphql-java-codegen#412]
example schema
```
type Query {
  q(filter: Foo): Bar
}

input Foo {
  field: String
}

type Bar {
  field: String
}
```

generated query when Foo is null is 

`query { q: q(){ field} }` instead of `query { q: q{ field} }`

suggested fix in `GraphQLRequestSerializer` method `buildQuery`, line 90

```
Map<String, Object> input = graphQLRequest.getRequest().getInput();
        boolean anyInputIsNotNull = input.values().stream().anyMatch(Objects::nonNull);

        if (anyInputIsNotNull) {
```		
instead of 
```
Map<String, Object> input = graphQLRequest.getRequest().getInput();
        if (input != null && !input.isEmpty()) {
```

**Comment by kobylynskyi** [comment]
@ClaudiuGuja, version [4.0.1](https://github.com/kobylynskyi/graphql-java-codegen/releases/tag/v4.0.1) with this fix was released today.
