### ISSUE TITLE
Is batching or lookahead supported?

### ISSUE THREAD

**Issue by jyjyj** [kobylynskyi/graphql-java-codegen#444]
As mentioned in the title, is there any inbuilt functionality for batching or lookahead?

References: [batching](https://www.graphql-java.com/documentation/v9/batching/), [lookahead](https://www.graphql-java.com/blog/deep-dive-data-fetcher-results/)

**Comment by kobylynskyi** [comment]
Following classes can be generated based on your GraphQL schema (as you can see from the README):
*    Interfaces for GraphQL queries, mutations, and subscriptions.
*    Interfaces for GraphQL unions.
*    POJO classes for GraphQL types and inputs.
*    Enum classes for GraphQL enums.
*    Interface Resolvers for GraphQL type fields (e.g. for parametrized fields).
*    Client Request classes for GraphQL queries, mutations and subscriptions.

`graphql-java-codegen` does not provide you any utils for bathing or lookahead.

Next time feel free to use [Discussions](https://github.com/kobylynskyi/graphql-java-codegen/discussions) if you have some questions.

**Comment by jyjyj** [comment]
@kobylynskyi thank you! Are there any plans for adding batching or lookahead?

Thanks for the Discussions tab, haven't noticed that before, will check that out!

**Comment by kobylynskyi** [comment]
What additional classes you think can be generated for batching/lookahead?
Please provide some example.
Thanks!
