### ISSUE TITLE
Support message for @deprecated directive

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#445]
**Describe the solution you'd like**

 * ```scala.@deprecated```should be used instead of Java's ```@Deprecated```. 
 * Message should be supported in the `deprecated` directive, especially for Kotlin. This value is required, now we've used a default value for it, but that's not a good way. should be replaced.

It may be necessary to refactor `XXDefinition.deprecated`. It involves multilingualism, and it is not sure how to isolate it for the time being. After all, Java doesn't support the message field in Deprecated annotation.

And more considerations for default graphql Directive?

**Comment by kobylynskyi** [comment]
Will be released in 4.1.0

**Comment by kobylynskyi** [comment]
@jxnu-liguobin thanks for the contribution!
