### ISSUE TITLE
Generated model class does not have properties for fields with arguments

### ISSUE THREAD

**Issue by gseifert** [kobylynskyi/graphql-java-codegen#476]
I have a schema with something like:

type BigEvent implements Node {
  activities(includeXyz: Boolean): [Activity!]!
  date: DateTime!
  ...
}

When I generate the model classes from the schema, the BigEvent class does not have an "activities" property due to the argument on the field ("includeXyz"), but only has properties for the fields without arguments (e.g. "date").  If I remove the "includeXyz" argument from the schema (i.e. "activities: [Activity!]!"), then the generated BigEvent class does have an "activities" property.

Is there a way to get the generated model classes to include properties for all the fields defined in the schema, including the ones with arguments defined on them?

Thanks!

**Comment by jxnu-liguobin** [comment]
Hi, The author may not wake up yet. Here's one you can see if it's what you want?


By using ```fieldsWithResolvers``` see at https://github.com/kobylynskyi/graphql-java-codegen/blob/master/docs/codegen-options.md, will generate a resolver named ```BigEventResolver``` which has a method named ```activities ```.Such as
```java
package com.github.graphql;


/**
 * Resolver for BigEvent
 */
@javax.annotation.Generated(
    value = "com.kobylynskyi.graphql.codegen.GraphQLCodegen",
    date = "2020-12-31T23:59:59-0500"
)
public interface BigEventResolver {

    @javax.validation.constraints.NotNull
    java.util.List<Activity> activities(BigEvent bigEvent, Boolean includeXyz) throws Exception;

}
```

**Comment by kobylynskyi** [comment]
@gseifert you can set the following config if you don't care about the parameter:
```groovy
generateParameterizedFieldsResolvers = false
```
or
```xml
<generateParameterizedFieldsResolvers>false</generateParameterizedFieldsResolvers>
```
By default, it is set to `true` which generates a separate Resolver class for each parametrized field.
If set to `false` then parametrized field will be added to the type definition and its field parameters will be ignored.
