### ISSUE TITLE
[Scala] Consider generating additional classes required for serialization of scala enumerations

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#479]
**Is your feature request related to a problem? Please describe.**
How to serialize Scala enumeration correctly?
Such as graphql schema
```graphql
enum Episode {
    NEWHOPE
    EMPIRE
    JEDI
}

type Human implements Character {
    id: ID!
    name: String!
    friends: [Character]
    appearsIn: [Episode]!
    homePlanet: String
    secretBackstory : String @deprecated(reason : "We have decided that this is not canon")
    email: Email!
}
```
need follow config  to add into ```customAnnotationsMapping```
```scala
  
  mapping.put("Human.appearsIn", util.Arrays.asList("@com.fasterxml.jackson.module.scala.JsonScalaEnumeration(classOf[io.github.dreamylost.EpisodeEnum])"))
```
**Describe the solution you'd like**
Generate ```EpisodeEnum.scala```

Most commonly, when using Jackson operation scala enumeration, if ```Episode``` is an enumeration type, an ```EpisodeEnum``` must be generated for ```Episode```. 
```EpisodeEnum``` as follow
```scala
class EpisodeEnum extends TypeReference[Episode.type]// codegen will only generate  Episode.scala
```
Also this can be called **EpisodeEnumType**?
But it only works if Jackson is the serialization tool.So it's not sure if it needs to be done.

**Describe alternatives you've considered**

**Additional context**

**Comment by kobylynskyi** [comment]
Will be released as part of v4.1.2
