### ISSUE TITLE
Kotlin - option to generate open class instead of data class

### ISSUE THREAD

**Issue by ntf** [kobylynskyi/graphql-java-codegen#524]
**Is your feature request related to a problem? Please describe.**
When evaluating Kotlin vs Java code generation, I found that the Java one generates ordinally non final POJO class while Kotlin one generates `data class` which are not inheritable. 

It would be great if we can generate model classes with `open class` instead or `interface` for even greater flexibility. 

**Describe the solution you'd like**
An option `kotlinGenerateModelInterfaces` or `kotlinGenerateModelOpenClasses` that generate `open class` or `interface` instead of `data class` which can not be inherited. 

**Describe alternatives you've considered**
Generate Java classes instead as models are not final classes. But it would be great to use Kotlin classes. 

**Additional context**

**Comment by jxnu-liguobin** [comment]
Both kotlin and scala can provide open classes, but we haven't encountered any examples so far, so I'm not sure if we need them.

btw, it takes some time to reconstruct the template. The most crude way is to add ```if dataclass else openclass``` to the original template.

**Comment by jxnu-liguobin** [comment]
According to the test, only kotlin needs it. If we judge by ```if  ... else ... ```(as follow), adding support to the existing template will lead to the template growing to hundreds of lines (it is difficult to maintain, which is the same as the scala toString method, although it is not urgent to solve at present). Is there a better way? @kobylynskyi 


if have no field
```class A```

else if enable data class
```data class A```

else 
```class A```

**Comment by kobylynskyi** [comment]
@jxnu-liguobin thanks for evaluating this. Sorry that I am not familiar with Kotlin, will you be able to share a sample of data class and open class? How different are they? Is it better to create a separate template file maybe?

**Comment by jxnu-liguobin** [comment]
Similar to Java POJO,but data class cannot be inherited. The constructor must have a parameter list and will  generated  automatically Some methods such as toString,equals,hashcode when compile time.Because it can't be inherited,this is the current problem. I'm wondering if I need to use a new file to store the template.

**Comment by jxnu-liguobin** [comment]
@ntf I have did it at pr https://github.com/kobylynskyi/graphql-java-codegen/pull/547. Please take a look.
There is also a small change for `xxxResponse`

**Comment by kobylynskyi** [comment]
Will be released as part of 4.1.4 soon.
