### ISSUE TITLE
BooleanTO class not generated (Version: 4.1.3")

### ISSUE THREAD

**Issue by PhilippS93** [kobylynskyi/graphql-java-codegen#555]
## Issue Description

I generated files containing this part

```
input UsersInput {
    paging: PagingInput
    sort: [SortInput]
    filter: UserFilterInput
    owner: Boolean = True
}
```

The generated class contains

```
public class UsersInputDTO implements java.io.Serializable {

    private PagingInputDTO paging;
    private java.util.List<SortInputDTO> sort;
    private UserFilterInputDTO filter;
    private Boolean owner = BooleanDTO.True;
```
and then `BooleanDTO` class is not found.

## Steps to Reproduce
*List in detail the exact steps to reproduce the unexpected behavior.*

## Expected Result
*Explain in detail what behavior you expected to happen.*

## Actual Result
Should just use `Boolean.TRUE`

## Your Environment and Setup

* **graphql-java-codegen**: *E.g.: 4.1.3*
* **Build tool**: *E.g.: Maven*
* **Java tool**: *E.g.: Oracle 8u241*
* **Mapping Config**: *E.g.:* 

```xml
graphqlCodegen {
    graphqlSchemas.includePattern = ".*\\.graphqls"
    outputDir = new File("$projectDir/src/main/generated/")
    packageName = "app.XY.server.Z.model"
    modelNameSuffix = "DTO"
    generateApis = true
}
```

## Additional context

Also, I am using `graphql-spring-boot-starter` from `com.graphql-java-kickstart` which takes default values automatically into account. Is there an option to disable the generation of classes with default values?

**Comment by kobylynskyi** [comment]
@PhilippS93 Please change your default value from:
```graphqls
    owner: Boolean = True
```
to:
```graphqls
    owner: Boolean = true
```

**Comment by PhilippS93** [comment]
Thank you, this solved the problem!
