### ISSUE TITLE
Missing support for query variables

### ISSUE THREAD

**Issue by SilverSheep** [kobylynskyi/graphql-java-codegen#559]
Hello,

Thanks for your time and engagement in making work with graphql easier.

However one missing feature is support for query variables.
Using graphql I write query like this:

```
query($name:String) { 
  user(name: $name) {
    id
    name
    surname
  }
}
```

and provide name's value :
`{"name": "random_name"}`

I would expect the same possibility using grapql-java-codegen lib.

Grapql query serialized to json may look like this:

```
{
    "query":
        "query($name:String) {
            user(name: $name) {
                id
                name
                surname
            }
        }"
    ,
    "variables": "{\"name\": \"random_name\"}"
}
```

**Comment by jxnu-liguobin** [comment]
As far as I know, this library puts parameters in query instead of independent variables.The library is not just a tool for building clients.

**Comment by kobylynskyi** [comment]
@SilverSheep, could you please explain a bit more why you need to provide parameters in the variables instead of the query?
Also, please provide an example of how you want to build the request object.
Thanks

**Comment by jxnu-liguobin** [comment]
This is related to the implementation of the graphql server(HTTP POST). Our graphql service is also like this, using
```
{
    "operationName": null,
    "variables": {},
    "query": "{\n  dataCenterUserIdentities {\n    id\n    name\n  matchType\n   creator\n    creatorId\n    createdAt\n    updater\n    updaterId\n    updatedAt\n    description\n    key\n  example\n  __typename\n  }\n}\n"
}
```

**Comment by kobylynskyi** [comment]
GraphQL codegen library in this repository is doing the serialization of request in the format mentioned above.
So I don’t see what else should be done here.

**Comment by jxnu-liguobin** [comment]
> GraphQL codegen library in this repository is doing the serialization of request in the format mentioned above.
> So I don’t see what else should be done here.

All the query parameters we generated are after the parameters, not independent.
LIke here:
```
Graphql http query {"query":"query { droid(id: \"2001\"){ id name __typename } }"}
Graphql query query { droid(id: "2001"){ id name __typename } }
```

But after my test, I can request the grapql server normally. Even if the parameters are not placed separately in `variables`.
If you put it in variables, then variables is a standard JSON, which is very important.

**Comment by kobylynskyi** [comment]
@jxnu-liguobin, Exactly. Request works perfectly if variables put directly in the query and not in the "variables" section. So I don't see any reason why they should be moved there.
@SilverSheep, Please clarify.

**Comment by jxnu-liguobin** [comment]
> @jxnu-liguobin, Exactly. Request works perfectly if variables put directly in the query and not in the "variables" section. So I don't see any reason why they should be moved there.
> @SilverSheep, Please clarify.
The client really doesn't care how to transfer parameters. Usually, the independent transmission is because the front end is more convenient for schema and data separation.

**Comment by jxnu-liguobin** [comment]
But I didn't test the `application/graphql` server. We all use `application/json`

**Comment by SilverSheep** [comment]
Sorry for no response for so long.
Thx for your comments.
We're using arrango db with foxx services and we have strict endpoints defined.
I could use http query parameters when calling arrango, but this would mean change of foxx microservice. Because of business priorities I cannot afford to make this change now.

However, we've managed to make a workaround by creating our own GraphQLRequest serializer which allows to pass a variable to variables section.

**Comment by jxnu-liguobin** [comment]
Strangely enough, our service is compatible with both protocols and only provides a POST API.
![image](https://user-images.githubusercontent.com/29496873/111150204-c598a200-85c8-11eb-90ca-3f734c6cbccb.png)
![image](https://user-images.githubusercontent.com/29496873/111150640-4e174280-85c9-11eb-99d7-06163a1c7303.png)

There is really no redundant code compatible with these two protocols.
![image](https://user-images.githubusercontent.com/29496873/111150410-0690b680-85c9-11eb-884d-1fb75171501f.png)
