### ISSUE TITLE
Automatically publish when the master is built successfully.

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#562]
I guess the problem here is the change of the version number of the example projects.

I forgot to release 4.1.2 and 4.1.3. I just released 4.1.3. 😅

**Comment by kobylynskyi** [comment]
Working on a script right now to update versions to release version and to snapshot version all over the project.
Also will change the GitHub Actions workflow:
So that once a new code to **develop** branch will be merged and we decide that library should be released, then just create a PR from develop to master and release will be performed automatically.

@jxnu-liguobin But I will need your help on how to automatically release sbt plugin.

**Comment by jxnu-liguobin** [comment]
> Working on a script right now to update versions to release version (and to -SNASHOT version as well) all over the project.
> Also will change the GitHub Actions workflow:
> So that once a new code to **develop** branch will be merged and we decide that library should be released, then just create a PR from develop to master and release will be performed automatically.
> 
> @jxnu-liguobin But I will need your help on how to automatically release sbt plugin.

SBT only needs to execute `sbt release` .But I don't know how the dependency of the example project can be modified automatically. Can Maven automatically modify the POM of the example project?

**Comment by jxnu-liguobin** [comment]
```sbt
    releaseProcess := Seq[ReleaseStep](
      checkSnapshotDependencies,
      inquireVersions,
      runClean,
      releaseStepCommandAndRemaining("^ scripted"),
      setReleaseVersion,
      commitReleaseVersion,
      tagRelease,
      releaseStepCommandAndRemaining("^ publishSigned"),
      setNextVersion, //This is a problem. If you need to make the master keep the next SNAPSHOT version. What about modifying the version in the example?
      commitNextVersion,
      pushChanges
    ),
```
This is the step of publishing SBT, which needs to be consistent with Gradle/Maven. Some steps may have to be deleted.

**Comment by kobylynskyi** [comment]
If I do `sbt "release with-defaults"` then it will automatically publish the plugin to artifactory? I think I will need to supply some sort of a token... that's how it is done in maven/gradle

**Comment by jxnu-liguobin** [comment]
> If I do `sbt "release with-defaults"` then it will automatically publish the plugin to artifactory? I think I will need to supply some sort of a token... that's how it is done in maven/gradle

Yes, also need to close the build on OSS and release it.

**Comment by jxnu-liguobin** [comment]
![image](https://user-images.githubusercontent.com/29496873/109906908-3512b580-7cdc-11eb-889c-14e3784d4010.png)
Because the library depends on the same version of the current plugin, plugin can only be released when they are released.

**Comment by jxnu-liguobin** [comment]
`sbt release with-defaults default-tag-exists-answer k`

It has been tested. If release version is ready, this command will automatically publish and ignore the known tags. At the same time, the version of the next iteration will be incremented and published to OSS. It should be noted that the version of example will not be updated.
