### ISSUE TITLE
Introduce integration tests for validating generated code

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#574]
Introduce integration tests, at least for `github.graphqls` need to be compiled and passed. Instead of just checking part of the file.Since we have not checked all the files after compilation, sometimes we may find compilation problems only when they are used.

**Comment by kobylynskyi** [comment]
That's why I created example-client and example-server.
In this sub-modules we already have exactly what you described.

**Comment by jxnu-liguobin** [comment]
That's not going to cover everything. I need to cover all GitHub API and three languages. I'm thinking about how to better implement a GitHub graphql client.

**Comment by kobylynskyi** [comment]
Ok, then maybe create a new repository called graphql-codegen-examples?
Where you could keep 3 different modules for example-client-java-github, example-client-kotlin-github, example-client-scala-github
Each will have all sorts of possible configurations and will check how things are compiling for generated client code for GitHub API.

**Comment by jxnu-liguobin** [comment]
not an example, but a usable client.

But we don't have a resolver that supports automatic implementation, so I wonder if our library can expose some tools that users can implement in this way. After all, it is acceptable for the client that the implementation is the default.

The problem here is that the field selection(projection) maybe needs to be passed in the method. If it's Scala, we can consider implicit.

**Comment by kobylynskyi** [comment]
How can you generate the implementation? It will be specific for everyone.
This library already generates the tools for building the request and parsing the response. Client code is already minimal: building request and calling an API.

**Comment by jxnu-liguobin** [comment]
I am using GitHub's API to build clients in three languages. Since we don't consider the performance impact, we can use this way which doesn't need to implement all resolver.

**Comment by jxnu-liguobin** [comment]
@kobylynskyi 
For writing a general clients, it is a waste of time to write each resolver implementation. Consider the separation of template and mode data, independent release? This may easy to support the implementation of the default resolver and it doesn't need to intrude into the library itself. And there is a possibility of supporting other strong types of languages.

Or we add a new method into resolver to implement this:
```java
    public SlicePaginationDto activeUsers(String projectId, String timeRange, Integer offset, Integer limit) throws Exception

    public SlicePaginationDto activeUsers(SlicePaginationResponseProjection projection, String projectId, String timeRange, Integer offset, Integer limit) throws Exception
```

The advantage is that when people use the library as a client, they can customize an important function: automatic resolver, and support field selection.(At present, i implement the default resolver in the fork library, using `all$()`). Of course, I only considered the client.

**Comment by jxnu-liguobin** [comment]
So far, it has been basically completed. Version 4.1.5 of the library is ok when test in  three languages with github.schema.

[![Scala CI](https://github.com/jxnu-liguobin/github-graphql-client/actions/workflows/scala.yml/badge.svg)](https://github.com/jxnu-liguobin/github-graphql-client/actions/workflows/scala.yml)

**Comment by kobylynskyi** [comment]
Awesome! ㊗️
