### ISSUE TITLE
[4.1.4] It generates error code when return type is a Query .

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#575]
## Issue Description

*Describe your bug in detail.*

I'm not sure if it's the problem.
## Steps to Reproduce

```
type xxx {
  relay: Query!  //return type is a Query
} 
```

When i set `mappingConfig.setModelNameSuffix("DTO");`
It will generate as follows:
```java
    QueryDTO relay() throws Exception;
```

But, cannot find a mode named `QueryDTO`.

Maybe it should ignore that when we change the name of the type which are in `Query`,`Mutation`,`Subscription`?

## Expected Result
*Explain in detail what behavior you expected to happen.*

## Actual Result
*Explain in detail what behavior actually happened.*

## Your Environment and Setup

* **graphql-java-codegen version**: *X.X.X*
* **Build tool**: *E.g.: Maven/Gradle/SBT*
* **Mapping Config**: *E.g.:* 

```xml
<configuration>
    <outputDir>${project.build.directory}/generated-sources/graphql</outputDir>
    <packageName>io.github.kobylynskyi.graphql.model</packageName>
</configuration>
```

**Comment by kobylynskyi** [comment]
@jxnu-liguobin set `generateModelsForRootTypes` to `true`
