### ISSUE TITLE
Multiple issues with FieldResolvers (Version: 1.5.0)

### ISSUE THREAD

**Issue by kobylynskyi** [kobylynskyi/graphql-java-codegen#58]
## Issue Description

1. `modelNameSuffix` and `modelNamePrefix` are not considered when generating FieldResolver interface which results in build failure.
2. Gradle plugin ignores some properties:
https://github.com/kobylynskyi/graphql-java-codegen/commit/0a28021e7ed7b5489f783ce961ed8cde0767efdd#diff-90e622d874a9fff19c74ff1d1c421f0dR38-R39

## Expected Result
```java
public interface ItemResolver {
    ProductTO product(ItemTO itemTO, DataFetchingEnvironment env) throws Exception;
}
```
## Actual Result
```java
public interface ItemResolver {
    ProductTO product(Item item, DataFetchingEnvironment env) throws Exception;
}
```

## Your Environment and Setup

* **graphql-java-codegen**: 1.5.0
* **Build tool**: Gradle
* **Mapping Config**:
```groovy
task graphqlCodegenOrderService(type: GraphqlCodegenGradleTask) {
    graphqlSchemaPaths = ["$projectDir/src/main/resources/schema.graphqls".toString()]
    outputDir = new File("$buildDir/generated-server")
    apiPackageName = "io.github.kobylynskyi.order.graphql.api"
    modelPackageName = "io.github.kobylynskyi.order.graphql.model"
    customTypesMapping = [
            DateTime: "java.util.Date"
    ]
    modelNameSuffix = "TO"
    fieldsWithResolvers = ["Item.product"]
}
```

**Comment by joffrey-bion** [comment]
I'm not sure this is how it should be. Resolvers are not model classes. Their suffix is currently "Resolver", which we may want to customize, but I believe it should be independent from model prefix/suffix.

**Comment by kobylynskyi** [comment]
You are taking about the Resolver class name?
Or the first argument in method signature?

**Comment by joffrey-bion** [comment]
Oh my bad, I thought the issue was about both.
I saw the model suffix in the the resolver class name, that's what I was arguing about.
Of course there is no question about the first argument in the methods, otherwise it doesn't build.

**Comment by kobylynskyi** [comment]
But thanks for your input regarding class name.
I will change it (not taking into account prefix/suffix).
