### ISSUE TITLE
[Scala] Upgrade Scala version on which Scala code generation depends, change 2.12.x -> 2.13.5

### ISSUE THREAD

**Issue by jxnu-liguobin** [kobylynskyi/graphql-java-codegen#582]
Fix expired API

**Comment by kobylynskyi** [comment]
@jxnu-liguobin do you want to do this as part of 5.0.0 release?

**Comment by jxnu-liguobin** [comment]
@kobylynskyi No, For compatibility reasons, it is not expected to be solved in the short term.

**Comment by jxnu-liguobin** [comment]
Since the scala community is certain that 2.14.x will not exist, 2.13 is the last version of scala2, so there is no need to fix this warning
