### ISSUE TITLE
Add custom fields to DTO

### ISSUE THREAD

**Issue by PhilippS93** [kobylynskyi/graphql-java-codegen#586]
**Is your feature request related to a problem? Please describe.**
The possibility to add additional property fields to the generated DTO classes which can be used internally by resolvers. These properties should be not available through the GraphQL API.

**Describe the solution you'd like**
An additional setting to specify the properties which are appended to the DTO and the types e.g.
```
customMappings = [
   "User.internalDate": "java.util.Date"
]
```

**Describe alternatives you've considered**
I searched the current configuration options, but did not find that capability. Is is supported in some way?

**Comment by jxnu-liguobin** [comment]
Seems to support? `fieldsWithoutResolvers`?

**Comment by PhilippS93** [comment]
Thanks for your quick answer!

Can you explain how this can solve the problem. In the end I want something like this:

GraphQL:
```
type User {
     name: String
     birthdate: Date
}
```

Java DTO (simplified):
```
public class User {
  String name;
  Date birthdate;
  String myInternalString;
  Object myInternalObject;
}
```

So I need to specify `myInternalString:String` and `myInternalObject:Object` but `fieldsWithoutResolvers` accepts only `Set<String>`

**Comment by jxnu-liguobin** [comment]
I have a look at the graphql specification. The `extend` needs to be defined in schema. At the same time, it needs a series of verification. I have doubts about whether this feature meets the requirements of archiving.

The graphql specification should be like this. If you donot want to expose it. Maybe the `Directives` should be used to handle it
```graphql
type User {
     name: String
     birthdate: Date
}

extend type User {
   myInternalString: String
   myInternalObject: Object
}
```

Consider skip and implement a custom Directive to achieve the same function? Our permission system also needs to calculate the detailed information of personnel in advance and use it in all interface authentication, and does not display some information of users.

**Comment by PhilippS93** [comment]
I think this has nothing to do with the graphql specification because it´s more like an internal plugin feature. For simple projects which do not need performance optimizations (pre-calculations and so) this feature is not needed but in business cases, this feature is crucial and blocks our company currently from using it..

**Comment by jxnu-liguobin** [comment]
yes,This is a plugin  feature. Maybe you can open a PR.

> I think this has nothing to do with the graphql specification because it´s more like an internal plugin feature. For simple projects which do not need performance optimizations (pre-calculations and so) this feature is not needed but in business cases, this feature is crucial and blocks our company currently from using it..

**Comment by kobylynskyi** [comment]
@PhilippS93 did you consider creating another schema that is extending your main schema (having custom additional fields) that is **not visible** to your application server, but **visible** to the codegen plugin

**Comment by jxnu-liguobin** [comment]
I also think that's what graphql recommended way. 👍 

> @PhilippS93 did you consider creating another schema that is extending your main schema (having custom additional fields) that is **not visible** to your application server, but **visible** to the codegen plugin

**Comment by PhilippS93** [comment]
Thanks, this is working!

I did not consider to separate the generation process and the API provisioning process. It looks a little bit odd to have private API definitions just for the generation process, but it is doing its job.

**Comment by kobylynskyi** [comment]
Glad it worked!
