### ISSUE TITLE
Default Kotlin mapped value for Double is not supported

### ISSUE THREAD

**Issue by aigyptios** [kobylynskyi/graphql-java-codegen#600]
Hello,

We are declaring a property to be a non-nullable `Float`:

```
type TheThing {
  someString: String!
  someFloat: Float!
}
```

And the generated Kotlin class is:
```
package mil.kr.direct.graphql.model


@javax.annotation.processing.Generated(
    value = ["com.kobylynskyi.graphql.codegen.GraphQLCodegen"],
    date = "2021-03-19T15:05:41-0400"
)
data class TheThing(
    var someString: String,
    var someFloat: Double
) {

    companion object {
        fun builder(): Builder = Builder()
    }


    class Builder {

        private lateinit var someString: String
        private var someFloat: Double = 0D

        fun setSomeString(someString: String): Builder {
            this.someString = someString
            return this
        }

        fun setSomeFloat(someFloat: Double): Builder {
            this.someFloat = someFloat
            return this
        }

        fun build(): TheThing {
            return TheThing(someString, someFloat)
        }
    }
}
```

However, the line `private var someFloat: Double = 0D` is not compiling as valid Kotlin:
```
Unsupported [literal prefixes and suffixes]
Unresolved reference: D
```

It expects the value to be `0.0` instead of `0D`. 

I'm guessing this is the source of that mapping?

https://github.com/kobylynskyi/graphql-java-codegen/blob/e306361fa0f6a2e755ee49b9fbaa306c99ae2151/src/main/java/com/kobylynskyi/graphql/codegen/kotlin/KotlinGraphQLTypeMapper.java#L52-L53

Is there something on our end (like a configuration) that I'm missing? Otherwise, could this be amended? I could also make a PR for it if it's just this method change.

Thank you!

**Comment by jxnu-liguobin** [comment]
Hi,@aigyptios thanks for report it,  There is indeed only this one code, and you can open a PR.
