### ISSUE TITLE
[Java] Directive on ARGUMENT_DEFINITION is not propagated to generated mutation interface

### ISSUE THREAD

**Issue by enttq** [kobylynskyi/graphql-java-codegen#602]
[Java] Custom directive for ARGUMENT_DEFINITION is not propagated to generated Java interface

## Issue Description
Hello team,

I'm trying to declare a custom directive that is mapped to Java annotation. However, when applied to mutation's argument it is not propagated to the generated Java's interface method.
Is there some important detail that I'm missing? 

Thank you!
## Steps to Reproduce
`schema.graphql`
```graphql

directive @valid on ARGUMENT_DEFINITION

input SampleInput {
    name: String
}

type Mutation {
   sampleAction(input: SampleInput! @valid): String!
}
```
## Expected Result
The generated method `sampleAction` has a parameter `input` annotated with `@javax.validation.Valid`.
```java
public interface SampleActionMutationResolver extends graphql.kickstart.tools.GraphQLMutationResolver {

    @javax.validation.constraints.NotNull
    String sampleAction(@javax.validation.Valid SampleInput input);
}
```

## Actual Result
The generated method `sampleAction` has a parameter `input` without `@javax.validation.Valid` annotation.

```java
public interface SampleActionMutationResolver extends graphql.kickstart.tools.GraphQLMutationResolver {

    @javax.validation.constraints.NotNull
    String sampleAction(SampleInput input);
}
```

## Your Environment and Setup

* **graphql-java-codegen version**: *4.1.5*
* **com.graphql-java-kickstart version**: *11.0.0*
* **Build tool**: *Gradle 6.8*
* **Mapping Config**:

```groovy
graphqlCodegen {
    generateApis = true
    generateApisWithThrowsException = false
    parentInterfaces {
        queryResolver = "graphql.kickstart.tools.GraphQLQueryResolver"
        mutationResolver = "graphql.kickstart.tools.GraphQLMutationResolver"
        subscriptionResolver = "graphql.kickstart.tools.GraphQLSubscriptionResolver"
        resolver = "graphql.kickstart.tools.GraphQLResolver<{{TYPE}}>"
    }
    directiveAnnotationsMapping = [
            'valid': ['javax.validation.Valid']
    ]
}
```

**Comment by enttq** [comment]
I did some investigation and it seems that annotations associated with mutation parameters are not processed.
The test case in codebase; the `@javax.validation.constraints.NotNull` annotation is not generated for `!`.
`test.graphqls`
```js
type Mutation {
    # Create a new event.
    createEvent(categoryId: String! @valid, createdBy: String!): Event!
    @auth(
        roles: ["admin", "moderator"],
        boo: [true, false, true],
        float: [12.0, null],
        int: 42,
        n: null)
}
```
generated class
```java
public interface CreateEventMutationResolver {

    /**
     * Create a new event.
     */
    @javax.validation.constraints.NotNull
    @com.example.CustomAnnotation(roles={"admin", "moderator"}, boo={true, false, true}, float={"12.0", "null"}, int=42, n="null")
    Event createEvent(String categoryId, String createdBy) throws Exception;

}
```

**Comment by kobylynskyi** [comment]
@enttq,
Thanks for the contribution!
I will soon release your changes as part of 4.1.6.

**Comment by jxnu-liguobin** [comment]
@kobylynskyi kotlin, scala maybe should also be needed.But I'm not sure if it works functionally though, I haven't used it that way.

**Comment by enttq** [comment]
My pleasure.

Sure, I will check how param annotations work in Kotlin & Scala and submit a PR with changes.

**Comment by jxnu-liguobin** [comment]
> My pleasure.

I tested the NotNull annotation in Scala and it seems to be useless. kotlin doesn't need the annotation ,so I didn't test
