### ISSUE TITLE
Add DataFetchingEnvironment parameter to main query resolver

### ISSUE THREAD

**Issue by joffrey-bion** [kobylynskyi/graphql-java-codegen#61]
**Is your feature request related to a problem? Please describe.**
When using GraphQL Java Tools, the main Query resolver, like other resolvers, can take an optional `DataFetchingEnvironment` parameter.
It is currently generated in all resolvers interfaces, but not for the root resolvers like `Query`.

**Describe the solution you'd like**
It'd be nice to provide this `DataFetchingEnvironment` argument to the query resolver's methods.
If we need backwards compatibility, we could use a config parameter to add or not the DataFetchingEnvironment argument in the generated interfaces.

**Describe alternatives you've considered**
There is no other way currently than to stop implementing the `Query` interface, which is a pain because changes to the schema don't make the compilation fail.

**Comment by kobylynskyi** [comment]
Good idea.
I think we definitely need a configuration parameter for this (which will default to ‘false’)

**Comment by joffrey-bion** [comment]
Should this param also affect field resolvers?

**Comment by kobylynskyi** [comment]
Yes, agree.

**Comment by joffrey-bion** [comment]
I tried to look into this one, but I realized that there is some duplication around operations VS field resolvers. They are currently treated differently, but the root Query object is just a special case of type that only needs a resolver and no POJO.

Technically `OperationDefinition` could be the same thing as `FieldResolverDefinition` (and thus would automatically solve the current issue). Would you like me to make this unification? Or do you prefer to keep changes to a minimum and maybe unify later as a separate effort?

**Comment by kobylynskyi** [comment]
Yes, we could definitely make the unification. Thanks for finding this.
But how will this automatically solve the issue?

**Comment by joffrey-bion** [comment]
By automatically I meant that if the code is not duplicated, adding the
DataFetchingEnvironment in one place solves the other one.

**Comment by kobylynskyi** [comment]
@joffrey-bion, will you be able to work on this feature? I would really appreciate it.
Otherwise, I can do it over the weekend.

**Comment by joffrey-bion** [comment]
Yes, I'll try to work on it tomorrow
