### ISSUE TITLE
Support for JDK 8

### ISSUE THREAD

**Issue by MalikKillian** [kobylynskyi/graphql-java-codegen#621]
Trying to utilize this plugin with a work project I ran into this error:
```
java.lang.UnsupportedClassVersionError: com/graphql_java_generator/gradleplugin/GraphqlPlugin has been compiled by a more recent version of the Java Runtime (class file version 57.0), this version of the Java Runtime only recognizes class file versions up to 52.0
```
I'm pretty sure that means the plugin was built with JDK 13. I hate to discourage anyone from using the latest and greatest, but a lot of the corporate world is still using JDK 8 since it's been supported since 2014 and will be supported until 2030. It's also highly unlikely for a corporation to use a non-LTS version and the next LTS version above JDK 13 isn't even released yet.

So if the goal is to have this plugin be as widely used as possible then I think backing down the JDK version (or having an alternate download) would be a good move.

**Comment by kobylynskyi** [comment]
I am pretty sure that it was built using jdk 8. Because I am using the plugin in one of my other projects (running jdk 8) and it works fine

**Comment by kobylynskyi** [comment]
And are you sure you are using graphql-java-codegen?
Based on your exception you are using a different plugin: https://github.com/graphql-java-generator

So I suggest you to use our graphql-java-codegen plugin.
