### ISSUE TITLE
Field resolvers should also be subject to async APIs configuration

### ISSUE THREAD

**Issue by joffrey-bion** [kobylynskyi/graphql-java-codegen#63]
## Issue Description
The generated field resolvers currently don't respect the `generateAsyncApis` configuration parameter, although they are part of the API just like top-level resolvers.

## Expected Result
When `generateAsyncApis` is enabled, field resolvers should have a return type wrapped in `CompletableFuture` as well.

## Actual Result
Field resolvers just have a plain java type as return type.

**Comment by vinaybedre** [comment]
@kobylynskyi I dont see any documentation on how to use `generateAsyncApis`
Can you please let me know if this option is supported?

**Comment by joffrey-bion** [comment]
@vinaybedre I think for more flexibility, this configuration has since been changed to `apiReturnType`, so you can specify any kind of return type, such as `CompletableFuture`:

This is what I have in my current Maven config:
```
<apiReturnType>java.util.concurrent.CompletableFuture</apiReturnType>
```

**Comment by vinaybedre** [comment]
@joffrey-bion Thanks for the hint.
Do you know is it possible to change return type of a specific field resolver?

**Comment by joffrey-bion** [comment]
@vinaybedre I don't believe this is possible at the moment. But I'll let @kobylynskyi confirm that, as I haven't contributed here in a while
