### ISSUE TITLE
GraphQL serialization of Map

### ISSUE THREAD

**Issue by kobylynskyi** [kobylynskyi/graphql-java-codegen#668]
Given GraphQL schema:
```graphqls
input FeeInput {
    feeType: String!,
    feeParams: JSON!
}
```

`graphqlCodegen` task has a section
```groovy
customTypesMapping = [
    JSON: "java.util.Map<java.lang.String,java.lang.String>"
]
```

Actual serialized string:
```
{ feeType: \"type\", feeParams: {k1=v1} }
```
Expected serialized string:
```
{ feeType: \"type\", feeParams: {k1: "v1"} }
```

---

Related to #663

**Comment by jxnu-liguobin** [comment]
> ```
> { feeType: \"type\", feeParams: {k1: "v1"} }
> ```

It seems strange why there are no quotation marks on Map key

**Comment by kobylynskyi** [comment]
Because a valid GraphQL request does not have quotes for keys
