### ISSUE TITLE
Response object does not have "has-a" object in case it is defined as parametrized input

### ISSUE THREAD

**Issue by bansal63** [kobylynskyi/graphql-java-codegen#676]
Query
```
A(aId: Long!): A
```

Response
```
type A {
    aId: Long!
    b: B
    cs(
        csId: Long,
    ): [CS]
}
```

Here A, B and CS are three objects.

When I run maven build. Object A is created and it has object B in it. But it does not have CS.
I see that ACSParametrizedInput class is created to define input structure of CS.
In response projection class created for the A, i also see a function to define parameterized projection and response projection for CS.

I wanted to check, if it is the issue with schema or a bug which can be fixed.

## Environment and Setup

* **graphql-java-codegen version**: *5.1.0*
* **Build tool**: *Maven*

```xml

<configuration>
             <graphqlSchemaPaths>
                     <graphqlSchemaPath>${project.basedir}/src/main/resources/graphql/schema.graphqls</graphqlSchemaPath>
             </graphqlSchemaPaths>
             <outputDir>${project.basedir}/src/main/java/</outputDir>
             <packageName>com..***</packageName>
             <customTypesMapping>
                                <Map>java.util.Map</Map>
                                <Long>java.lang.Long</Long>
                                <Timestamp>java.util.Date</Timestamp>
             </customTypesMapping>
             <generateApis>false</generateApis>
             <generateClient>true</generateClient>
</configuration>
```

**Comment by kobylynskyi** [comment]
@bansal63, please check the config option `generateParameterizedFieldsResolvers`. By default it is set to true meaning that all fields that have parameter will be excluded from POJO and will have a resolver method in the generated interface.
I think that you need this option to be set to false so that CS will be a part of A POJO.
Please let me know how it works.

**Comment by bansal63** [comment]
@kobylynskyi 
It worked like charm.
Thank you for quick response.

Should this be marked as false by default?

**Comment by kobylynskyi** [comment]
Created a new issue to track a request to change the default value of `generateParameterizedFieldsResolvers` to `false`: #677
