### ISSUE TITLE
[outputDir missing or invalid] (Version: [graphql-java-codegen 16.0])

### ISSUE THREAD

**Issue by ryan-zheng-teki** [kobylynskyi/graphql-java-codegen#68]
## Issue Description

Hi, I have configured the plugin in my pom XML file according to the guide. But I get exceptions when 
executing the generate goal of the plugin saying outputDir missing or invalid. Could you give some help?

## Steps to Reproduce
Then I execute the goal in command line
"mvn graphql-codegen:generate -X"

## Expected Result
I expect the generated folder should be created

## Actual Result
![image](https://user-images.githubusercontent.com/5105956/79318377-32ae3e00-7f07-11ea-982f-e6f2f9152635.png)

## Your Environment and Setup

* **graphql-java-codegen**: *E.g.: 1.6.0*
* **Build tool**: *E.g.: Maven*
* **Java tool**: *E.g.: openjdk 11*
* **Mapping Config**: *E.g.:* 

```xml
                        <configuration>
                            <graphqlSchemaPaths>${project.basedir}/src/main/resources/schema.graphqls</graphqlSchemaPaths>
                            <outputDir>${project.build.directory}/generated-sources/graphql</outputDir>
                            <packageName>com.qiusuo.springboottutorial.graphql.model</packageName>
                            <customTypesMapping>
                                <DateTime>java.util.Date</DateTime>
                                <Price.amount>java.math.BigDecimal</Price.amount>
                            </customTypesMapping>
                            <modelNameSuffix>TO</modelNameSuffix>
                        </configuration>
```

**Comment by kobylynskyi** [comment]
@ryan-zheng-teki please try the following maven goal:
`mvn clean generate-sources`

**Comment by joffrey-bion** [comment]
(unrelated) As a side note, your `<graphqlSchemaPaths>` is not necessary anymore since 1.6.0.
By default, `graphql-java-codegen` now picks up all `*.graphqls` files in the resources folder of the project.

**Comment by joffrey-bion** [comment]
(unrelated) As a side note, your `<graphqlSchemaPaths>` is not necessary anymore since 1.6.0.
By default, `graphql-java-codegen` now picks up all `*.graphqls` files in the resources folder of the project.

**Comment by ryan-zheng-teki** [comment]
> generate-sources

Hi, Thank you very much. It works! The goal is inside generate-sources phase.
