### ISSUE TITLE
Ability to provide a custom operation name in GraphQL request

### ISSUE THREAD

**Issue by robbertnoordzij** [kobylynskyi/graphql-java-codegen#681]
**Is your feature request related to a problem? Please describe.**
Currently we use the same generated code in different clients. However, we would like to distinguish between the sources of the request. An option would be to use the operation name as specified on https://graphql.org/learn/queries/#operation-name. At the moment this field seems to be static and final in the Request class. And the operation is also used as the actual field of the query. 

E.g. the currently the generated `HeroesQueryRequest` has the `OPERATION_NAME` set (final) to `hero`. In the `GraphQLRequestSerializer` this operation name is being used in the operation name and query part of the request.

Is this intentional?

**Describe the solution you'd like**
In this example, I would like to be able to set the operation name to `HeroNameAndFriends` and stil request the field hero from the query.

**Describe alternatives you've considered**
I have tried to use the alias. However, this only directs the output of the query to another field and this won't change the operation name as extracted by our graphql server.

**Comment by kobylynskyi** [comment]
@robbertnoordzij good point. This could be enhanced by providing a custom query/mutation name.
The changes should be done in `GraphQLRequest` by creating another constructor(s) with an additional `String` argument.

**Comment by robbertnoordzij** [comment]
@kobylynskyi not to put pressure on to the project or to push anything, do you have an estimated release date?

**Comment by kobylynskyi** [comment]
@robbertnoordzij, sorry for the delay. I've released 5.2.0 just now.

**Comment by robbertnoordzij** [comment]
No problem! Thank you!
