### ISSUE TITLE
ProductServiceGraphQLClient - retrieve list example

### ISSUE THREAD

**Issue by JustinBlandford** [kobylynskyi/graphql-java-codegen#69]
Hi @kobylynskyi , in the ProductServiceGraphQLClient class,  you have shown the ProductByIdQueryRequest,  Could you also share the equivalent implementation for ProductsByIdsQueryRequest?  I'm getting Cannot deserialize instance of `my class` out of START_ARRAY token - I think it's because RestTemplate doesn't handle Lists of objects being returned (https://www.baeldung.com/spring-rest-template-list).  I've tried a few things but not getting any success - the GraphQl call is successful , it's just deserialising into the list and I can see your schema -     productsByIds(ids: [ID!]!): [Product] returns a list of Products .

**Comment by kobylynskyi** [comment]
@JustinBlandford thank you for your question.
I've added an example as per your request. Take a look at: 
https://github.com/kobylynskyi/graphql-java-codegen/blob/master/plugins/maven/example-client/src/main/java/io/github/kobylynskyi/order/external/ProductServiceGraphQLClient.java#L62

Please let me know if you have any further questions

**Comment by JustinBlandford** [comment]
@kobylynskyi thanks.  A couple of questions.  I've noticed that for later versions of the plugin (after version 1.2.3), that for Float types in a GraphQl schema, they are now generated as doubles in the code.  Just wondered what the reason was behind that?  Just thinking that it may cause issues sending requests as the double is wider than the float?  Also, would it be possible to return more data about the response in GraphQLResult?  So the status of the response is one thing that would be useful.

**Comment by joffrey-bion** [comment]
@JustinBlandford this is actually a fix I proposed to match the GraphQL specification. They may be calling their type `Float` but it is in fact double-precision floating point numbers that they refer to with this.

**Comment by JustinBlandford** [comment]
@joffrey-bion thanks for clarifying
