### ISSUE TITLE
При генерации api возникают проблемы в многоуровневой схеме. 

### ISSUE THREAD

**Issue by knizamiev** [kobylynskyi/graphql-java-codegen#718]
```
schema {
    query: RootQuery
    mutation: RootMutation
}

type RootQuery {
    user: UserQuery
}

type RootMutation {
    user: UserMutation
}

```

```
type UserType {
    id: Int
    name: String
    working: Boolean
}
input UserInput {
    id: Int
    name: String
    working: Boolean
}

type UserQuery {
    getUser(id: Int): UserType
    getUsers: [UserType]
}

type UserMutation {
    createUser(input: UserInput): String
}
```

Результат генерации api 

 ```
UserTypeDTO getUser(UserQueryDTO userQueryDTO, Integer id) throws Exception;
 
     String createUser(UserMutationDTO userMutationDTO, UserInputDTO input) throws Exception;
```

1) В аргумент функции добавляется лишняя dto модель
2) В query api отсутствует метод  getUsers

Моя конфигурация генератора. 

```
   <plugin>
                <groupId>io.github.kobylynskyi</groupId>
                <artifactId>graphql-codegen-maven-plugin</artifactId>
                <version>5.1.0</version>
                <executions>
                    <execution>
                        <goals>
                            <goal>generate</goal>
                        </goals>
                        <configuration>
                            <graphqlSchemaPaths>
                                <graphqlSchemaPath>${project.basedir}/src/main/resources//graphql/user.graphqls</graphqlSchemaPath>
                                <graphqlSchemaPath>${project.basedir}/src/main/resources/graphql/global.graphqls</graphqlSchemaPath>
                            </graphqlSchemaPaths>
                            <outputDir>${project.build.directory}/generated-sources/graphql</outputDir>
                            <apiPackageName>io.github.kobylynskyi.product.graphql.api</apiPackageName>
                            <modelPackageName>io.github.kobylynskyi.product.graphql.model</modelPackageName>
                            <modelNameSuffix>DTO</modelNameSuffix>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
```

**Comment by kobylynskyi** [comment]
hey @knizamiev
I think your GraphQL schema should be changed to something like:
```graphql
schema {
    query: RootQuery
    mutation: RootMutation
}

type RootQuery {
    getUser(id: Int): UserType
    getUsers: [UserType]
}

type RootMutation {
    createUser(input: UserInput): String
}

type UserType {
    id: Int
    name: String
    working: Boolean
}
input UserInput {
    id: Int
    name: String
    working: Boolean
}
```

**Comment by knizamiev** [comment]
Мы не можем менять схему ) это нужно для группировки

Скачайте Outlook для iOS<https://aka.ms/o0ukef>
________________________________
От: Bogdan Kobylynskyi ***@***.***>
Отправлено: Monday, May 31, 2021 6:49:52 PM
Кому: kobylynskyi/graphql-java-codegen ***@***.***>
Копия: knizamiev ***@***.***>; Mention ***@***.***>
Тема: Re: [kobylynskyi/graphql-java-codegen] При генерации api возникают проблемы в многоуровневой схеме. (#718)


hey @knizamiev<https://github.com/knizamiev>
I think your GraphQL schema should be changed to something like:

schema {
    query: RootQuery
    mutation: RootMutation
}

type RootQuery {
    getUser(id: Int): UserType
    getUsers: [UserType]
}

type RootMutation {
    createUser(input: UserInput): String
}

type UserType {
    id: Int
    name: String
    working: Boolean
}
input UserInput {
    id: Int
    name: String
    working: Boolean
}

**Comment by knizamiev** [comment]
Я знаю что либа хорошо работает если реализована классическая схема. 

Но подразумевается ли что либа будет работать с моей схемой ?

**Comment by kobylynskyi** [comment]
Unfortunately, the plugin does not support such kinds of schemas.

**Comment by jxnu-liguobin** [comment]
This grouped schema needs to merge before this plug-ins task. We have this practice.
`https://github.com/growingio/growingio-graphql-javasdk/blob/master/src/test/scala/io/growing/graphql/schema/GraphqlSchemaScanner.scala`
