### ISSUE TITLE
Using the client code generator with RESTAssured

### ISSUE THREAD

**Issue by JustinBlandford** [kobylynskyi/graphql-java-codegen#74]
Hi @kobylynskyi  @joffrey-bion, I've seen the client code working now with the Spring rest template so all good there.  Just wondered if this would also work with RESTAssured for BDD testing?  RESTAssured gives that standard Given When Then BDD structure and would also be useful to be able to hook the client code generated by your plugin into that.  In your example, you build the request with a projection:-

        GraphQLRequest request = new GraphQLRequest(getProductRequest,
                new ProductResponseProjection()
                        .id()
                        .title()
                        .price());

.. and then use the Spring RestTemplate to issue the request using a ParameterizedTypeReference for the response.  As well as be able to  issue the request with the Spring Rest template, it would be useful to see how that may hook into a RESTAssured call in the structure :-

     response = request
            .given()
            .headers(headers)
            .body(payload)
            .contentType(ContentType.JSON)
            .when()
            .post(url)
            .then()
            .statusCode(status)
            .extract()
            .response();

Not sure if this is possible with RESTAssured - but ultimately all its doing is invoking a REST service, so if you have any ideas, then would be useful to hear what you think.

**Comment by kobylynskyi** [comment]
@JustinBlandford 
I've added `RestAssured` sample here:
https://github.com/kobylynskyi/graphql-java-codegen/blob/master/plugins/maven/example-client/src/test/java/io/github/kobylynskyi/order/service/CreateProductIntegrationTest.java

**Comment by mka92** [comment]
Hey @kobylynskyi I'm using your plugin with 
```
<resolverArgumentAnnotations>org.springframework.graphql.data.method.annotation.Argument</resolverArgumentAnnotations>
<useWrapperForNullableInputTypes>true</useWrapperForNullableInputTypes>
```
 and I've go an error in test like below: 
`Invalid syntax with ANTLR error 'token recognition error at: '.s'' at line 1 column 70`

I think the problem is that argument value is not unwrapped (parsed) to the request body. 
```
{"query":"query testTest { testTest: testTest(testInput: { testInput: org.springframework.graphql.data.ArgumentValue@6b0b9cb6 }){ result } }"}
```

Schema:
```
type Query {
    testTest(
        testInput: TestInput!
    ): TestResult

input TestInput {
    testInput: String
}

type TestResult {
    result: String
}

}```

Example test code:
```
        TestInputGQL testInputGQL = TestInputGQL.builder()
                .setTestInput(ArgumentValue.ofNullable("testValue"))
                .build();

        TestResultResponseProjection testResultResponseProjection = new TestResultResponseProjection().result();

        GraphQLRequest graphQLRequest = new GraphQLRequest(
                TestTestQueryRequest.builder().setTestInput(testInputGQL).build(),
                testResultResponseProjection
        );

        TestTestQueryResponse graphqlResponse = sendGraphQLQuery(
                graphQLRequest
        )
                .then()
                .statusCode(200)
                .extract()
                .body()
                .as(TestTestQueryResponse.class);
```

**Comment by kobylynskyi** [comment]
@mka92 this looks like an issue. Can you please create a ticket and someone can pick it up? Also, you are welcome to contribute since you have already investigated the root cause. Thank you!

**Comment by rwo-trackunit** [comment]
I'll have a look when its created, since I was working on `useWrapperForNullableInputTypes`.
