### ISSUE TITLE
Pagination support in version 5.2.0

### ISSUE THREAD

**Issue by ChopperlaAditya** [kobylynskyi/graphql-java-codegen#745]
### Discussed in https://github.com/kobylynskyi/graphql-java-codegen/discussions/744

<div type='discussions-op-text'>

<sup>Originally posted by **ChopperlaAditya** July 16, 2021</sup>
I want to implement pagination and tried by keeping generateParameterizedFieldsResolvers as false, but it didn't help me. We can see generated DTO's but 
1.From where I can send the cursor value for pagination.
2.For DTO's we are using separate project and using this as dependency in another project, when kept field with parameter, GraphQL server is not starting and throwing below error :

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'schemaParser' defined in class path resource [graphql/kickstart/tools/boot/GraphQLJavaToolsAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [graphql.kickstart.tools.SchemaParser]: Factory method 'schemaParser' threw exception; nested exception is graphql.kickstart.tools.FieldResolverError: No method found as defined in schema :18 with any of the following signatures (with or without one of [interface graphql.schema.DataFetchingEnvironment] as the last argument), in priority order:

com.xxx.xxx.service.query_resolver.EmpInfoGraphQLDtoResolver.observationHistory(com.xxx.xxx.service.models.EmpInfoGraphQLDto, ~cursor)
com.xxx.xxx.query_resolver.EmpInfoGraphQLDtoResolver.getObservationHistory(com.xxx.xxx.service.models.EmpInfoGraphQLDto, ~cursor)
com.xxx.xxx.models.EmpInfoGraphQLDto.observationHistory(~cursor)
com.xxx.xxx.models.EmpInfoGraphQLDto.getObservationHistory(~cursor)_

**My GraphQL Schema**
```
type Query {
    empInfo(id: String!, type: String!): EmpInfo!
}

type EmpInfo {
    observationHistory(**cursor**: String): ObservationHistory!
}

type ObservationHistory {
    observations: [String!]
}
```
**My code base**
```
public class EmpInfoQueryResolver implements GraphQLQueryResolver {

public EmpInfoGraphQLDto empInfo(String id, String type){
    //EmpInfoGraphQLDto generated by graphql-codegen-maven-plugin 

    // my business logic

   }

}
```

I have used version 5.2.0, if I'm missing any config or anything, can you let me know.</div>

**Comment by kobylynskyi** [comment]
The plugin can't generate something "extra" which you don't have in your schema.
Therefore I  recommend you to add the [desired way of pagination](https://graphql.org/learn/pagination/#pagination-and-edges) to your schema file and `graphql-java-codegen` will be able to generate DTO classes with the data-types you specified there.
You can also consider [Relay](https://www.graphql-java-kickstart.com/tools/relay/). `graphql-java-codegen` supports it via [`relayConfig`](https://github.com/kobylynskyi/graphql-java-codegen/blob/master/docs/codegen-options.md#option-relayconfig).
Hope this helps.
