### ISSUE TITLE
Example of mutation in client code

### ISSUE THREAD

**Issue by JustinBlandford** [kobylynskyi/graphql-java-codegen#75]
Hi @kobylynskyi @joffrey-bion  would it be possible for you to add a mutation request example to client code sample?

**Comment by kobylynskyi** [comment]
@JustinBlandford I've added an example of the GraphQL mutation request.
Please take a look here: https://github.com/kobylynskyi/graphql-java-codegen/blob/master/plugins/maven/example-client/src/main/java/io/github/kobylynskyi/order/external/ProductServiceGraphQLClient.java#L83
