### ISSUE TITLE
Resolvers that return custom types

### ISSUE THREAD

**Issue by estet90** [kobylynskyi/graphql-java-codegen#766]
I use [vertx-web-graphql](https://vertx.io/docs/vertx-web-graphql/java/) and I want to use this codegen for generate API. But I can't customize response. Are there any plans to add such a feature?
For example:
**build.gadle**
```groovy
graphqlCodegen {
  responseTypesMapping = [
    "my.custom.Response": "io.smallrye.mutiny.Uni<my.custom.Response>"
  ]
}
```

**Comment by kobylynskyi** [comment]
@estet90 could you please provide a bit more context including your schema and expected generated class?
Thanks.

**Comment by estet90** [comment]
**tasks.graphqls**
```
type Task {
    id: String
    description: String
    completed: Boolean
}

type Query {
    allTasks(uncompletedOnly: Boolean = true): [Task]
}

type Mutation {
    complete(id: String!): Boolean
}
```

**build.gradle**
```groovy
graphqlCodegen {
    graphqlSchemas.includePattern = "tasks.graphqls"
    outputDir = new File("$buildDir/generated/sources/graphql")
    packageName = "ru.tsc.crm.vertxdemoservice.graphql.model"
    modelValidationAnnotation = "jakarta.validation.constraints.NotNull"
    generateApisWithThrowsException = false
}
```

**generated interface for query**
```java
package ru.tsc.crm.vertxdemoservice.graphql.model;


@javax.annotation.processing.Generated(
    value = "com.kobylynskyi.graphql.codegen.GraphQLCodegen",
    date = "2021-08-06T14:12:34+0400"
)
public interface QueryResolver {

    java.util.List<Task> allTasks(Boolean uncompletedOnly);

}
```

**I want to generate**
```java
package ru.tsc.crm.vertxdemoservice.graphql.model;


@javax.annotation.processing.Generated(
    value = "com.kobylynskyi.graphql.codegen.GraphQLCodegen",
    date = "2021-08-06T14:12:34+0400"
)
public interface QueryResolver {

    io.smallrye.mutiny.Uni<java.util.List<Task>> allTasks(Boolean uncompletedOnly);

}
```

**Comment by kobylynskyi** [comment]
@estet90 this is already supported.
Take a look at `apiReturnType` / `apiReturnListType`.
In your case I think you should add the following configs to your `build.gradle`:
```groovy
graphqlCodegen {
    ...
    apiReturnType = "io.smallrye.mutiny.Uni"
    apiReturnListType = "io.smallrye.mutiny.Multi"
}
```
Or in case you want to use `Uni` for `List`s as well (`Uni<List<Task>>` instead of `Multi<Task>`), then just:
```groovy
graphqlCodegen {
    ...
    apiReturnType = "io.smallrye.mutiny.Uni"
}
```

**Comment by estet90** [comment]
> @estet90 this is already supported.
> Take a look at `apiReturnType` / `apiReturnListType`.
> In your case I think you should add the following configs to your `build.gradle`:
> 
> ```groovy
> graphqlCodegen {
>     ...
>     apiReturnType = "io.smallrye.mutiny.Uni"
>     apiReturnListType = "io.smallrye.mutiny.Multi"
> }
> ```
> 
> Or in case you want to use `Uni` for `List`s as well (`Uni<List<Task>>` instead of `Multi<Task>`), then just:
> 
> ```groovy
> graphqlCodegen {
>     ...
>     apiReturnType = "io.smallrye.mutiny.Uni"
> }
> ```
thank you!
