### ISSUE TITLE
Support @JvmStatic on generated Kotlin builders

### ISSUE THREAD

**Issue by kbrooks** [kobylynskyi/graphql-java-codegen#767]
**Is your feature request related to a problem? Please describe.**
I want to convert a project that is using the Java code generation to Kotlin in a codebase that relies heavily on generated builders. In order for the Kotlin code to be backwards compatible with the old Java code, the generated builders need a @JvmStatic annotation so they can be referenced like static methods from Java.

**Describe the solution you'd like**

Is there a way to configure the code generation to place a @JvmStatic annotation on the builder in the generated companion object?

**Comment by jxnu-liguobin** [comment]
Not supported. In general, scala/kotlin do not use the builder pattern. So I didn't consider compatibility with java at first, just for functional consistency. 

But I agree to add this annotation to these methods by default, It's very simple. What about you? It would be better if you could create a pr. (add `@JvmStatic` on builder method).

**Comment by kbrooks** [comment]
I will give it a shot. Where is the kotlin builder code generated?

**Comment by jxnu-liguobin** [comment]
`kotlinClassGraphqlRequest.ftl`  request
`kotlinClassGraphqlType.ftl`   type

**Comment by kobylynskyi** [comment]
Will soon be released as part of 5.3.0. Thanks for your patience.
