### ISSUE TITLE
Multiple .graphql or .graphqls files not supported

### ISSUE THREAD

**Issue by andritch** [kobylynskyi/graphql-java-codegen#774]
## Issue Description

This make this plugin pretty much unusable for multiple schema files. I think the offending code is in `com.kobylynskyi.graphql.codegen.GraphQLDocumentParser` in the `com.kobylynskyi.graphql.codegen.GraphQLDocumentParser.populateDefinition(...)` method.

In he block below schema files with Query / Mutations always fall into the else statement which overwrites any previously processed files.

```java
if (extensionDefinitionClass.isAssignableFrom(definition.getClass())) {
    extendedDefinition.getExtensions().add((E) definition);
} else {
    extendedDefinition.setDefinition((B) definition);
}
```

## Steps to Reproduce

1. Have more than one Query ? Mutations contained in schema1.graphqls and schema2.graphqls in the ../resources folder 
2. Run mvn generate-sources with defaults ( OR with specific settings to generate based on file or folder name)
```xml
<configuration>
	<outputDir>${project.build.directory}/generated-sources/graphql</outputDir>
	<apiInterfaceStrategy>DO_NOT_GENERATE</apiInterfaceStrategy>
	<apiRootInterfaceStrategy>INTERFACE_PER_SCHEMA</apiRootInterfaceStrategy>
	<apiNamePrefixStrategy>FILE_NAME_AS_PREFIX</apiNamePrefixStrategy>
</configuration>

```

## Expected Result

That multiple API interfaces get generated per schema files as documented.
 > ...following schemas: resources/schemas/order-service.graphql, resources/schemas/product-service.graphql
 will result in: OrderServiceQueryResolver.java, ProductServiceQueryResolver.java, etc

> ... following schemas: resources/order-service/schema1.graphql, resources/order-service/schema2.graphql
 will result in: OrderServiceQueryResolver.java, OrderServiceGetOrderByIdQueryResolver.java, etc

## Actual Result

Only the LAST schema containing Query / Mutation is taken into account and generated Java class generated

## Your Environment and Setup

* **graphql-java-codegen version**: *5.2.0*
* **Build tool**: *Maven*

**Comment by jxnu-liguobin** [comment]
Hey @andritch 
Are you using configuration [graphqlSchemas](https://github.com/kobylynskyi/graphql-java-codegen/blob/master/docs/codegen-options.md#option-graphqlschemas)?

**Comment by kobylynskyi** [comment]
@andritch, also please share two schemas that do not work together

**Comment by andritch** [comment]
> Are you using configuration [graphqlSchemas](https://github.com/kobylynskyi/graphql-java-codegen/blob/master/docs/codegen-options.md#option-graphqlschemas)?

No I don't have that configuration setup. Doc states it defaults to .graphql and .graphqls which was sufficient for my use case.

**Comment by andritch** [comment]
@kobylynskyi 
> @andritch, also please share two schemas that do not work together
The one that gets processed last wins.

_activity_service_api.graphqls_
```graphql
input Create2Input {
    aliasModel: AliasModelInput
}
input Delete2Input {
    aliasId: Int!
}
input Update2Input {
    aliasId: Int!,
    aliasModel: AliasModelInput
}
input UpdateM2appingsInput {
    aliasId: Int!,
    updateMappingModel: [UpdateMappingModelInput]
}
type Query {
    DashboardWidgets: TodoObjectMapping
    GetOverview: TodoObjectMapping
    GetOverview1(start: String!, end: String!, accounts: String!, scale: String!): TodoObjectMapping
}
```
_alias_service_api.graphqls_
```graphql
input Create1Input {
    aliasModel: AliasModelInput
}
input Delete1Input {
    aliasId: Int!
}
input Update1Input {
    aliasId: Int!,
    aliasModel: AliasModelInput
}
input UpdateMappingsInput {
    aliasId: Int!,
    updateMappingModel: [UpdateMappingModelInput]
}
type Mutation {
    Create1(input: Create1Input!): Int!
    Delete1(input: Delete1Input!): Boolean
    Update1(input: Update1Input!): Boolean
    UpdateMappings(input: UpdateMappingsInput!): Boolean
}
type Query {
    GetAll: AliasView
    GetById(aliasId: Int!): AliasView
    GetMappings(aliasId: Int!): AliasView
    GetSubscribersFieldNames: String!
}
```

**Comment by kobylynskyi** [comment]
@andritch if you have multiple schemas, then replace "type Query" with "extend type Query". Same for Mutation/Subscription.

**Comment by andritch** [comment]
@kobylynskyi Thanks! That seems to have solved it.

**Comment by YarLyashenko** [comment]
@kobylynskyi thanks! been looking why only one query is generated from the multiple files.
