### ISSUE TITLE
classes for Query and Mutation not being generated together

### ISSUE THREAD

**Issue by jyjyj** [kobylynskyi/graphql-java-codegen#79]
For my schemas, I have a root file containing a root Query, Mutation and Subscription:

`Query { 
    root : String 
}`

then I have `extend Query` etc. in later files, all of which (in order, root file first) I am feeding into the build.gradle's `graphqlSchemaPaths`. However, when I define `extend Query` and `extend Mutation`, one of these is not being generated, namely whichever I put second a.k.a. I either only get the Query classes or the Mutation classes generated. This occurs if I put them in the same file or in different files.

I'm also getting errors when I try to gradle build like FileAlreadyExists exception when I have multiple schema files. Do I necessarily need to gradle build when I want to re-generate the classes (e.g. when I change my GraphQL schema), and how do I get around these errors?

Not sure if this is a bug per se, but any help would be much appreciated. Thanks!

**Comment by joffrey-bion** [comment]
Might be related to this: https://github.com/graphql-java/graphql-java/issues/406

It looks like `graphql-java-codegen` is using GraphQL Java version `3.0`.
@kobylynskyi is there anything preventing the upgrade to a more recent version?

**Comment by jyjyj** [comment]
Thanks! Would also like to add that sometimes I get quite buggy results with the generated classes. For example, now my model files are not being generated at all while the APIs are (hence causing errors since the APIs are based on non-existent model classes).

**Comment by joffrey-bion** [comment]
It would be great if you could open a separate issue for each problem with some minimal config to reproduce the issue. As of now it's a bit hard to both reproduce and track.

I'm not sure whether we are talking about missing generated files in the case of `extends` or in the case of `Query` + `Mutation`, or because of duplicate processes of code generation.

**Comment by kobylynskyi** [comment]
@jyjyj I think you are mixing up several issues.
> extend Query

This will be done as part of #81 .

> Do I necessarily need to gradle build when I want to re-generate the classes (e.g. when I change my GraphQL schema), and how do I get around these errors?

It is up to you how you handle `graphqlCodegen` task. You can run it always (as shown in the README or in the example projects) or you can [skip it](https://stackoverflow.com/questions/47192746/how-can-i-disable-a-task-in-build-gradle) or you can make it dependent on some other Gradle task. 

> when I try to gradle build like FileAlreadyExists exception when I have multiple schema files

Please create a separate issue with same schemas and steps to reproduce.

> For example, now my model files are not being generated at all while the APIs are (hence causing errors since the APIs are based on non-existent model classes).

Please create a separate issue with same schemas and steps to reproduce.

Thank you!
