### ISSUE TITLE
Add support for extensions

### ISSUE THREAD

**Issue by joffrey-bion** [kobylynskyi/graphql-java-codegen#81]
**Is your feature request related to a problem? Please describe.**

[Type extensions](http://spec.graphql.org/draft/#TypeExtension) are part of the specification, and should therefore be supported. Type extensions, according to the linked spec, can be of the following types:

- ScalarTypeExtension (`extend scalar X`)
- [ObjectTypeExtension](http://spec.graphql.org/draft/#ObjectTypeExtension) (`extend type X`)
- InterfaceTypeExtension (`extend interface X`)
- UnionTypeExtension (`extend union X`)
- EnumTypeExtension (`extend enum X`)
- InputObjectTypeExtension (`extend input X`)

**Describe the solution you'd like**

When defining type extensions in the SDL schema, they should be taken into account and "merged" with the extended type so that the code generation matches the actual schema.

We could (should?) also provide an option (`generateExtensionFieldsResolvers`?) to consider all fields from Object Type Extensions as fields with resolvers, because it is likely that these fields require a special resolver implementation with a service call. (Should it be true by default? Maybe not.)

If we do this, maybe we should add a new option to do the opposite of `fieldsWithResolvers`, like `fieldsWithoutResolvers`, blacklisting some fields so that they are part of the generated POJO instead of being generated as part of the resolver interface.
The reason why I think we should do this is because if the user decides to generate resolvers for *most* fields that are part of extensions, but not all, it would be painful to list all of them in `fieldsWithResolvers`. Instead, we should allow declaring `generateExtensionFieldsResolvers` to handle the general case, and add some exceptions via `fieldsWithoutResolvers`.

**Describe alternatives you've considered**

The alternative (current situation) is to force the user to declare all their types in the same schema, which is not ideal and sometimes impossible (in case of remote schema using federation).

**Comment by Lukas-Kullmann** [comment]
I ran into the same issue today when I wanted to extend an enum type. So when implementing this, it would be super nice if all type extensions would be supported.

- `extend scalar X`
- `extend type X`
- `extend interface X`
- `extend union X`
- `extend enum X`
- `extend input X`

I just wanted to mention this since the issue description suggests that there is only `extend type X`.

**Comment by kobylynskyi** [comment]
Thanks for your feature request. 
Current implementation of the library is not supporting extensions.
I will work on this soon.

**Comment by joffrey-bion** [comment]
@Lukas-Kullmann yes, I actually meant all extensions, sorry for the confusion. I used the specification's names, but I admit they are quite confusing.

In the spec's grammar, what they call `TypeExtension` actually encompasses all of them. And the `extend type X` expression is what they call an `ObjectTypeExtension`. That's why I said "especially object type extensions". But I should remove the beginning of my description, which is misleading.

**Comment by joffrey-bion** [comment]
I updated the description to be clearer about all types of extensions and also suggest some config options.

**Comment by jyjyj** [comment]
Hi, not sure if this has been / is being addressed, but could you guys also state the preferred way to handle the base Query / Mutation etc. vs. extending them? From my understanding, there needs to be a base `type Query` before any further `extend type Query`, so am hoping you guys would also explain how to cope with this after you are done implementing the extend stuff. Thanks!

**Comment by kobylynskyi** [comment]
@jyjyj AFAIK, the order of `type query` and `extend type Query` does not matter. If that's what you asked.
Extensions will be handled by the library in the following way:
GIVEN schema:
```graphqls
type Query {
    events: [Event!]
}
type Mutation {
    createEvent(input: EventInput!): Event!
}
```
AND schema extension (could be in the same schema or different one):
```graphqls
extend type Query {
    assets: [Asset!]
}
extend type Mutation {
    createAsset(input: AssetInput!): Asset!
}
```

WHEN executing the code generation using graphql-java-codegen 
THEN resulting classes will look like:
``` java
public interface EventsQuery {
    Collection<Event> events() throws Exception;
}

public interface AssetsQuery {
    Collection<Asset> assets() throws Exception;
}

public interface CreateAssetMutation {
    Asset createAsset(AssetInput input) throws Exception;
}

public interface CreateEventMutation {
    Event createEvent(EventInput input) throws Exception;
}

// and combined interfaces with all queries and mutations:
public interface Query {
    Collection<Event> events() throws Exception;
    Collection<Asset> assets() throws Exception;
}

public interface Mutation {
    Event createEvent(EventInput input) throws Exception;
    Asset createAsset(AssetInput input) throws Exception;
}

```

**Comment by jyjyj** [comment]
Ok thank you! Is this issue hence fully addressed? Also, do I need to do anything other than refresh my gradle (I'm using the plugin) to get this update?

**Comment by joffrey-bion** [comment]
@jyjyj When a new version of the plugin is released, you will just have to change the plugin version in your gradle file

**Comment by kobylynskyi** [comment]
@jyjyj no changes are required from your side except from updating the version of the plugin once I will release it (probably by the end of this week)

**Comment by Lukas-Kullmann** [comment]
@kobylynskyi I don't know how your GraphQL parser works, but please keep in mind, that all of the member types are optional. So this is perfectly valid syntax:

```graphql
type Query

extend type Query {
    events: [Event!]
}

extend type Query {
    assets: [Asset!]
}
```

The same goes for enums, unions, interfaces, and scalars.

**Comment by joffrey-bion** [comment]
@Lukas-Kullmann Thanks for pointing out some edge cases, it is definitely something we should consider adding to the tests.

As a side note, this library uses the GraphQL parser from the [`graphql-java`](https://github.com/graphql-java/graphql-java) library, which is the official-ish Java implementation of GraphQL AFAIU. So all the edge cases in terms of schema syntax itself should not really be a problem.

That being said, the codegen library still needs to be careful in how it uses the `Document` that the parser provides, because a type could have no members. As far as I could see in the current implementation, these cases are correctly taken into account so far.
