### ISSUE TITLE
generateToString = false still generates toString() methods in models

### ISSUE THREAD

**Issue by skataryna** [kobylynskyi/graphql-java-codegen#848]
I had been using Gradle with codegen parameters listed below
```
graphqlCodegen {
    graphqlSchemas.includePattern = "schema\\.graphql"
    outputDir = new File("$projectDir/src/main/java/")
    apiPackageName = "app.api"
    modelPackageName = "app.model"
    typeResolverSuffix = "res"

    addGeneratedAnnotation = false
    generateClient = true
    generateApis = true
    generateBuilder = true
    generateToString = true
    generateModelsForRootTypes = true
    generateExtensionFieldsResolvers = false
    generateJacksonTypeIdResolver = true
}
```

After changing `generateToString` parameter from `true` to `false` - `toString()` methods were still generated in model classes after running `gradlew graphqlCodegen`. Removing/commenting `generateToString` from build.gradle didn't help.

* **graphql-java-codegen version**: *5.3.0*
* **Build tool**: *Gradle*

**Comment by bpossolo** [comment]
experiencing this as well with Maven plugin 5.3.0

**Comment by kobylynskyi** [comment]
Right now `generateToString` is always **true** for client-side code generation because it is required for request serialization. It can be set to true or false for server-side code generation though.
