### ISSUE TITLE
Configure apiReturnType to be a complex type?

### ISSUE THREAD

**Issue by mivanov12** [kobylynskyi/graphql-java-codegen#861]
Is it possible to configure apiReturnType to return complex types?
For example: `CompletableFuture<DataFetcherResult <T>>`

**Comment by kobylynskyi** [comment]
Suggested solution is ok with me.

**Comment by romash1408** [comment]
According to [this code](https://github.com/kobylynskyi/graphql-java-codegen/blob/master/src/main/java/com/kobylynskyi/graphql/codegen/mapper/GraphQLTypeMapper.java#L128) you can get what you want with
```
    apiReturnType = "java.util.concurrent.CompletableFuture<graphql.execution.DataFetcherResult<%s>>"
```
It works for me in 5.4.0

**Comment by kobylynskyi** [comment]
Thanks @romash1408 for pointing this out.
