### ISSUE TITLE
Support "sealed" keyword on interfaces and unions in Kotlin

### ISSUE THREAD

**Issue by kbrooks** [kobylynskyi/graphql-java-codegen#868]
**Is your feature request related to a problem? Please describe.**
Add `sealed` keyword` to generated interfaces and unions in order to enable exhaustive type-checking in written code. For example
```
sealed interface Animal {}
data class Cat(val foo: String): Animal  
data class Dog(val bar: String): Animal  

fun cases(obj: Animal) {                                
    return  when (obj) {
        is Cat -> "foo"
        is Dog -> "bar"; // Removing this line will fail compilation 
    }   
}
```
The Kotlin language will default to exhaustive `when` _statements_ (expressions are already exhaustive) in version 1.7, which will make it easier to take advantage of this feature. https://kotlinlang.org/docs/whatsnew1530.html#exhaustive-when-statements-for-sealed-and-boolean-subjects

**Describe the solution you'd like**
A `generateSealedInterfaces` build parameter that if true will add the `sealed` keyword to generated interfaces in Kotlin

**Describe alternatives you've considered**
n/a

**Comment by kbrooks** [comment]
I noticed Scala has a sealed class option as well, but it looks like you have to make sure the classes are in the same file as the interface which seems like a non-starter

**Comment by jxnu-liguobin** [comment]
> I noticed Scala has a sealed class option as well, but it looks like you have to make sure the classes are in the same file as the interface which seems like a non-starter

Yes, so I don't think Scala applies.

**Comment by kbrooks** [comment]
It looks like Java actually added support for this feature in v15. I can add this as well https://openjdk.java.net/jeps/409

**Comment by kbrooks** [comment]
Since Java's sealed interfaces have a more complex syntax that requires listing the implementing classes in the interface definition, it is significantly harder to add support; we can track it in another issue
