### ISSUE TITLE
Add `skip` parameter to skip execution when true

### ISSUE THREAD

**Issue by Rugal** [kobylynskyi/graphql-java-codegen#961]
**Is your feature request related to a problem? Please describe.**
Just like many other plugins, a `skip` parameter is welcomed to be there. When set as `true`, the current execution shall be ignored as it is.  
The use case is, I created a `parent` pom which has all the configurations and executions in it. By doing so, I do not have to do repeatted configuration thing anymore, given there is not much configurational change from project to project.  
But when comes to`graphql-java-codegen-maven-plugin`, when I do the same, because there is no `skip` parameter, it always generate whatever I configured in parent.  

**Describe the solution you'd like**
One `skip` boolean parameter, to skip the current execution when set as `true`

**Describe alternatives you've considered**
We may name the `skip` the other way, but the feature itself has no alternative.

**Comment by kobylynskyi** [comment]
Added a new `skip` parameter to Gradle/Maven/SBT plugins. WIll be released as part of 5.5.0 soon.
