### ISSUE TITLE
Not all the files get generated if you use multiple graphql schema files from different api's.

### ISSUE THREAD

**Issue by DeruytterA** [kobylynskyi/graphql-java-codegen#962]
## Issue Description

If you use multiple schema.graphql files. For example multiple microservices that you want to call from 1 application.
Not all the ...MutationRequest or ... QueryRequest files get generated. Only the files form 1 of the schema's. This does not happen with all the other kinds of generated files.

I don't know if I'm doing something wrong or if this is actually a bug.

## Steps to Reproduce

1. Place multiple schema.graphql files in resources folder (all with query and mutation endpoints)
2. maven clean
3. maven compile (and let the files get generated)
4. Not all the  ...MutationRequest or ... QueryRequest files will be generated.

## Expected Result

All of the  ...MutationRequest and ...QueryRequest files to be generated. Not only the ones from 1 of the files.

## Actual Result

The  ...MutationRequest and ...QueryRequest files from only 1 of the schema.graphql files are generated.

## Your Environment and Setup

* **graphql-java-codegen version**: *5.4.0*
* **Build tool**: *Maven*
* **Mapping Config**: *E.g.:*

```xml

<configuration>
  <graphqlSchemas>
    <includePattern>.+.graphql</includePattern>
  </graphqlSchemas>
  <outputDir>${project.build.directory}/generated-sources/graphql</outputDir>
  <packageName>com.example.microservices</packageName>
  <customTypesMapping>
    <DateTime>java.util.Date</DateTime>
    <Price.amount>java.math.BigDecimal</Price.amount>
  </customTypesMapping>
  <customAnnotationsMapping>
    <EpochMillis>
      <annotation>com.fasterxml.jackson.databind.annotation.JsonDeserialize(using = com.example.json.EpochMillisScalarDeserializer.class)</annotation>
    </EpochMillis>
  </customAnnotationsMapping>
  <modelNameSuffix>GTO</modelNameSuffix>
  <generateApis>false</generateApis>
  <generateClient>true</generateClient>
  <addGeneratedAnnotation>false</addGeneratedAnnotation>
</configuration>
```

**Comment by kobylynskyi** [comment]
@DeruytterA
If your files have `type Query` / `type Mutation`, then graphql library will not be able to "merge" operations.
So make sure all your files have `extends Query` / `extends Mutation`.
Sample:
https://github.com/kobylynskyi/graphql-java-codegen/blob/master/src/test/resources/schemas/extend2.graphqls#L8-L14
