### ISSUE TITLE
graphqlCodegen task does not validate interface implementations prior to generating classes

### ISSUE THREAD

**Issue by andrewflbarnes** [kobylynskyi/graphql-java-codegen#965]
## Issue Description

A type which implements an interface and does not have all fields declared will still result in the `graphqlCodegen` successfully running and creating classes even though the schema is incorrect.

If this is functioning as designed and better raised as a feature request (for example to add a `strict` flag to the mapping config) I can do that.

Wouldn't it be preferable to fail during codegen to give devs early, automatic feedback on schema issues, rather than them having to manually diagnose, or miss, the issue.

## Steps to Reproduce

Configure  a project with a `schema.graphqls` like below in `src/main/resources`.
```graphql
interface Base {
    item: String
}

type Concrete implements Base {
    itme: String
}
```

Run the codegen task e.g.
```bash
./gradlew graphqlCodegen
```

## Expected Result

The codegen task fails to generate the required classes as the `Concrete` type does not have an `item` field from the `Base` interface.

## Actual Result

The codegen task completes successfully, creating a ConcreteDTO class which has both an `item` and `itme` field. e.g.
```java
@javax.annotation.processing.Generated(
    value = "com.kobylynskyi.graphql.codegen.GraphQLCodegen",
    date = "2022-03-04T11:03:14+0000"
)
public class ConcreteDTO implements java.io.Serializable, BaseDTO {

    private static final long serialVersionUID = 1L;

    private String itme;
    private String item;
...
```

## Your Environment and Setup

* **graphql-java-codegen version**: 5.4.0
* **Build tool**: Gradle
* **Mapping Config**: 

```groovy
graphqlCodegen {
    outputDir = file("${buildDir}/generated")
    packageName = "my.app.graphql"

    parentInterfaces {
        queryResolver = "graphql.kickstart.tools.GraphQLQueryResolver"
        mutationResolver = "graphql.kickstart.tools.GraphQLMutationResolver"
        subscriptionResolver = "graphql.kickstart.tools.GraphQLSubscriptionResolver"
        resolver = "graphql.kickstart.tools.GraphQLResolver<{{TYPE}}>"
    }

    customTypesMapping = [
        "BigDecimal": "java.math.BigDecimal"
    ]
    apiReturnType = "java.util.concurrent.CompletableFuture"
    fieldsWithResolvers = ["@withCustomResolver"]
    generateToString = true
    modelNameSuffix = "DTO"
    generateApis = true
    generateClient = true
    supportUnknownFields = true
    unknownFieldsPropertyName = "additionalFields"
}
```

**Comment by kobylynskyi** [comment]
We are using graphql-Java library under the hood. It does not have such validations.
