### ISSUE TITLE
when field is class has failed

### ISSUE THREAD

**Issue by doesDWQ** [kobylynskyi/graphql-java-codegen#974]
//  Constructor function
public ATO(String revise, String action, String role, String context, String Class, String detail) {
        this.Class = Class;
 }

// generate function
public String getClass() {
      return Class;
  }

failed message: override getClass() in java.lang.Object

**Comment by jxnu-liguobin** [comment]
it capitalizes `class`, then, `getClass` on method name.
https://github.com/kobylynskyi/graphql-java-codegen/blob/06b83bea41d182f0c5cbbe2a2fdaa95682f0e8fc/src/main/resources/templates/java-lang/type.ftl#L76

**Comment by kobylynskyi** [comment]
It's not a bug. getClass is a final method in Object class. Means you can't override it. Please rename your attribute name.

**Comment by doesDWQ** [comment]
> It's not a bug. getClass is a final method in Object class. Means you can't override it. Please rename your attribute name.

Hello, it's not that I don't want to rename the field property name, but because the changed field has been used in clients in other languages, so I can't modify it here at will. Thank you for replying to the email in your busy time
