### ISSUE TITLE
@skipcodegen directive

### ISSUE THREAD

**Issue by JamesPeters98** [kobylynskyi/graphql-java-codegen#986]
I moved away from Netflix's DGS framework which has it's own codegen and one of the nice features it has is the ability to add @skipcodegen directives in the schema so you can restrict certain fields that you don't want in your model.

It could be used to prevent one-to-many types from showing up in types that get resolved separately by a DataFetcher.

**Comment by kobylynskyi** [comment]
@JamesPeters98 have you tried following codegen options? `fieldsWithResolvers` / `fieldsWithResolvers` You can supply a directive name (in your case it is `@skipcodegen`). Please let me know if it works out.

**Comment by JamesPeters98** [comment]
@kobylynskyi Thanks that worked perfectly using 
```
"fieldsWithResolvers": [
    "@skipcodegen"
  ]
```
