### ISSUE TITLE
Local Development issue - UnableToDeleteDirectoryException

### ISSUE THREAD

**Issue by JamesPeters98** [kobylynskyi/graphql-java-codegen#987]
## Issue Description

I've just been trying to build the project locally on Windows with Intellij. All tests appear to fail though and throw UnableToDeleteDirectoryException when running tests.

Not sure what's causing the problem, have I missed anything I need to set up?

## Your Environment and Setup

* **graphql-java-codegen version**: *develop*

**Comment by jxnu-liguobin** [comment]
Directory permissions may be a problem?

**Comment by JamesPeters98** [comment]
Turns out there's a FileWriter not being closed in FreeMarkerTemplateFilesCreator.java

It needs to be this, I can make a PR for it
```
            FileWriter fileWriter = new FileWriter(javaSourceFile);
            template.process(dataModel, fileWriter);
            fileWriter.close();
```

**Comment by kobylynskyi** [comment]
Thanks @JamesPeters98 for working on this.
WIll be part of the next release.
