### ISSUE TITLE
Fluent setters

### ISSUE THREAD

**Issue by gzak** [kobylynskyi/graphql-java-codegen#993]
Right now the generated classes require you to do something like this:
```
var myObj = new MyObj();
myObj.setA(...);
myOjb.setB(...);
```
It would be nice if there was a fluent option (should be backwards compatible to introduce this):
```
var myObj = new MyObj().setA(...).setB(...);
```

**Comment by kobylynskyi** [comment]
You can use _generateBuilder_ for this.
